// =====================================================================
//  tuned_configs.h — autotune output (defaults until autotune is run)
//
//  Per-(kernel, arch, shape-bucket) launch parameters and tile sizes.
//  Generated by autotune/tune.py; committed to the repo so the build is
//  deterministic and reproducible.
//
//  The values in this file are DEFAULT placeholders chosen to match the
//  current hand-coded __launch_bounds__ in the kernels (BLOCK_SIZE=256,
//  MIN_BLOCKS_PER_SM=2 or 8 depending on optimizer). Run autotune on
//  hardware to overwrite with measured winners:
//
//      python autotune/tune.py --arch sm_90 --output csrc/common/tuned_configs.h
//
//  Schema: a small struct LaunchConfig per kernel; per-arch overrides via
//  arrays indexed by sg_arch_index(). Lookup helper get_launch_config()
//  picks the right entry by (kernel id, arch id, N bucket).
// =====================================================================

#pragma once

#include <cstdint>
#include <stdexcept>

namespace sg {

// ---------------------------------------------------------------------
// Arch identifiers used to index the tables. Must match the values
// returned by csrc/bindings/dispatch.cpp::detect_arch().
// ---------------------------------------------------------------------

enum ArchId : int {
    ARCH_SM80   = 0,
    ARCH_SM90   = 1,
    ARCH_SM100  = 2,
    ARCH_GFX942 = 3,
    NUM_ARCHES  = 4,
};

inline ArchId arch_id_from_int(int a) {
    switch (a) {
        case 80:  return ARCH_SM80;
        case 90:  return ARCH_SM90;
        case 100: return ARCH_SM100;
        case 942: return ARCH_GFX942;
        default:
            throw std::runtime_error(
                "arch_id_from_int: unsupported arch " + std::to_string(a));
    }
}

// ---------------------------------------------------------------------
// LaunchConfig — what every per-arch kernel pulls in for its template
// parameters and __launch_bounds__.
// ---------------------------------------------------------------------

struct LaunchConfig {
    int  block_size;          // threads per block
    int  min_blocks_per_sm;   // hint for __launch_bounds__
    int  block_m;             // tile M dim (GEMM); 0 if N/A
    int  block_n;             // tile N dim (GEMM); 0 if N/A
    int  stages;              // pipeline depth (cp.async/TMA); 0 if N/A
    bool vec4;                // float4 vectorized fast path
};

// Default config when autotune has not been run for this kernel/arch yet.
inline constexpr LaunchConfig DEFAULT_CONFIG = {
    /* block_size        */ 256,
    /* min_blocks_per_sm */ 2,
    /* block_m           */ 0,
    /* block_n           */ 0,
    /* stages            */ 0,
    /* vec4              */ true,
};

// ---------------------------------------------------------------------
// Per-kernel tables. Indexed by [arch_id][shape_bucket].
//
// The default tables below are chosen to match the hand-coded
// __launch_bounds__ in the existing per-arch kernels. Autotune
// overwrites them with measured winners.
// ---------------------------------------------------------------------

// For per-element optimizer steps, the kernel is bandwidth-bound and the
// shape buckets are (small, medium, large, xlarge, xxlarge) of N. One
// LaunchConfig per (arch, bucket).
//
// shape_bucket index: 0=N<=4096, 1=N<=65k, 2=N<=512k, 3=N<=4M, 4=N<=32M+

inline constexpr LaunchConfig GROKADAMW_CONFIGS[NUM_ARCHES][5] = {
    /* sm_80   */ {DEFAULT_CONFIG, DEFAULT_CONFIG, DEFAULT_CONFIG, DEFAULT_CONFIG, DEFAULT_CONFIG},
    /* sm_90   */ {DEFAULT_CONFIG, DEFAULT_CONFIG, DEFAULT_CONFIG, DEFAULT_CONFIG, DEFAULT_CONFIG},
    /* sm_100  */ {DEFAULT_CONFIG, DEFAULT_CONFIG, DEFAULT_CONFIG, DEFAULT_CONFIG, DEFAULT_CONFIG},
    /* gfx942  */ {DEFAULT_CONFIG, DEFAULT_CONFIG, DEFAULT_CONFIG, DEFAULT_CONFIG, DEFAULT_CONFIG},
};

// Helper to pick the bucket from N.
inline int bucket_for_N(int N) {
    if (N <= 4096)   return 0;
    if (N <= 65536)  return 1;
    if (N <= 524288) return 2;
    if (N <= 4194304) return 3;
    return 4;
}

inline LaunchConfig get_grokadamw_config(int arch, int N) {
    return GROKADAMW_CONFIGS[arch_id_from_int(arch)][bucket_for_N(N)];
}

// ---------------------------------------------------------------------
// TODO(autotune): add per-kernel tables for grokfast, lion, prodigy,
// neuralgrok, looksam, sg11, sg15, sg2 fwd/bwd. For SG2 projection GEMMs
// and Muon NS GEMMs the tables come from the CUTLASS profiler (a separate
// schema with threadblock_shape, warp_shape, instruction_shape, stages,
// split_k_slices). Those land in tuned_configs_cutlass.h sibling header.
// ---------------------------------------------------------------------

} // namespace sg
