export const meta = {
  name: 'supergrok-distributed-scope',
  description: 'Parallel READ-ONLY scope of the 4D+ZeRO-3 distributed flagship: distributed-step integration gap, in-megakernel device-NVSHMEM all-reduce, and the 8-GPU torchrun run harness + per-rank memory/Nmax math',
  phases: [{ title: 'Scope', detail: '3 agents map the 4D+ZeRO-3 state and emit apply-ready specs to /workspace/impl_diffs/' }],
}
const SCHEMA = {
  type: 'object', additionalProperties: false,
  required: ['area', 'spec_path', 'files_changed', 'gate_commands', 'confidence', 'risks', 'summary'],
  properties: {
    area: { type: 'string' }, spec_path: { type: 'string' },
    files_changed: { type: 'array', items: { type: 'string' } },
    gate_commands: { type: 'array', items: { type: 'string' } },
    confidence: { type: 'string' }, risks: { type: 'array', items: { type: 'string' } },
    summary: { type: 'string' },
  },
}
const COMMON = `You are READ-ONLY on /workspace/SuperGrok1.5 (Read/Grep/Glob; do NOT edit/build/run). Write /workspace/impl_diffs/<AREA>.md as APPLY-READY edits (VERBATIM OLD snippet copied from the live file + NEW; new files in full).
VERIFIED CONTEXT (this session): The FLAGSHIP 1.5B decoder (d=1600, L=48, 1,475,884,899 params) NOW RUNS end-to-end single-GPU (fwd→bwd→AdamW, loss=ln(99)=4.585 at random init, grad finite, A/A/A bit-identical) after we (1) generalized the decoder TC backward dW-spec/LN-vec/Muon enumeration to dec::kLayers (model_stage_decoder_tc.cuh + fused_decoder_megakernel.cuh + pp_stage_decoder_tc.cuh; L=2 gate 19/19, L=48 compiles+fits 1 CTA/SM at 24.8KB static smem), and (2) emitted decoder_flagship_layout.cuh via megakernel_codegen.py --decoder-layout-flagship. The production path is the L3-TC PERSISTENT wgmma megakernel (1 CTA/SM, hand GridBarrier, fwd→bwd→AdamW fused in ONE __global__ launch). The single-GPU flagship needed: AdamW-only with SG_DEC_BENCH_LAYOUT=1 to ELIDE the 4 staged-opt scratch regions (SG2's per-CTA meta-net scratch dec_tc_sg2_floats = O(50·Nmax)·nCTA ≈ 509 GB at d=1600 — a documented KNOWN DEEP LIMIT) and ncta_cap=8 (the workspace dec_tc_workspace_floats has nCTA-scaled per-CTA tile scratch). So the flagship GENUINELY REQUIRES 4D+ZeRO-3 sharding to saturate 8 GPUs AND to make the staged optimizers fit (TP shrinks the largest per-rank tensor Nmax → shrinks the SG2 scratch; ZeRO-3 shards params+state). The 4D code EXISTS: ParConfig<DP,TP,PP,SP,Z> (grokking_optimizers/parallel/ + parallel_config.cuh), ZeRO3Sharder, sharded_optimizer_kernel.cuh, tp_transport.cuh (LoopbackTransport + NvshmemTransport gated -DSG_HAS_NVSHMEM=1), fused_train_step_distributed; 84 parallelism CPU tests pass; 14/15 GPU tests pass. The USER WANTS the distributed all-reduce done IN-KERNEL via device NVSHMEM (keeps the megakernel fusion) NOT a CUDA graph. Read the cited files IN FULL first. gfx942/tpu untouched.`

const agents = [
  { name: 'dist_step', label: 'distributed-step integration gap', prompt: `${COMMON}
AREA: grokking_optimizers/parallel/distributed_step.py + grokking_optimizers/distributed.py + the C++ seam (sharded_optimizer_kernel.cuh, parallel_config.cuh). GOAL: produce the EXACT integration gap + apply-ready edits to drive the FLAGSHIP decoder TC megakernel (mega_decoder_real_adamw_tc, flagship layout) under 4D+ZeRO-3 across 8 GPUs. Map IN FULL: what fused_train_step_distributed currently does (DP all-reduce? TP column/row shard? PP micro-batch? SP sequence shard? ZeRO-3 reduce-scatter/all-gather of params+state?), which axes are WIRED end-to-end vs stubbed, and EXACTLY what is missing to: (a) shard the 1.476B params + 3× AdamW state across ranks (ZeRO-3), (b) TP-shard the large weight tensors (in_proj 3d×d, ff 4d×d) so per-rank Nmax shrinks (this is what makes the SG2/staged-opt scratch fit), (c) keep the single fused megakernel per rank. Identify the ONE GPU test that fails (grokfast dp2 parity 3.77e-5 vs 3e-5) and whether it's a real bug or tolerance. Deliver apply-ready edits (or, where a full impl is too large to be byte-exact read-only, a precise step-by-step impl plan with exact insertion points + signatures). gate_commands: ['python -m pytest tests/ -k "parallel or distributed or zero3" -q', 'python -c "import grokking_optimizers.parallel"']. Spec -> /workspace/impl_diffs/dist_step.md.` },

  { name: 'tp_nvshmem', label: 'in-megakernel device-NVSHMEM all-reduce', prompt: `${COMMON}
AREA: csrc/.../tp_transport.cuh + the megakernel TP-reduce seam + parallel_config.cuh. GOAL: spec the IN-KERNEL device-NVSHMEM all-reduce the USER explicitly wants (TP/SP cross-rank reduction done INSIDE the persistent megakernel via nvshmem device APIs — nvshmemx_float_sum_reduce / nvshmem_float_p / nvshmem_barrier_all_block — so the fusion is preserved, NOT a host CUDA-graph stitch of per-rank launches). Read tp_transport.cuh IN FULL (LoopbackTransport + the gated NvshmemTransport, -DSG_HAS_NVSHMEM=1) + where the megakernel would call the TP reduce (the attn/ff column-parallel boundary + the SP sequence reduction). Determine: (1) is NVSHMEM installable here (check for libnvshmem / headers; if absent, say what the user must install — this is an environment gate like ncu), (2) the EXACT device-side call sequence to all-reduce the TP-partitioned activation at the megakernel's GridBarrier boundary (the partials are already in the workspace; the reduce must be ascending-rank deterministic to preserve A/A/A + fp64 parity), (3) how it composes with the hand GridBarrier (cross-RANK barrier vs cross-CTA barrier — nvshmem_barrier_all is grid+device-wide). BE HONEST: device NVSHMEM in a persistent 1-CTA/SM kernel is hard; flag the symmetric-heap allocation requirement (operands must live in the NVSHMEM symmetric heap, not a plain cudaMalloc workspace) — that may force a workspace-allocator change. gate_commands: ['grep -rn nvshmem /usr/lib /usr/local 2>/dev/null | head', 'bash scripts/compile_to_object.sh <a TP TU> -DSG_HAS_NVSHMEM=1 (if installable)']. Spec -> /workspace/impl_diffs/tp_nvshmem.md.` },

  { name: 'run_harness', label: '8-GPU flagship torchrun harness + memory math', prompt: `${COMMON}
AREA: NEW files only (an 8-GPU run harness) + the per-rank memory/Nmax arithmetic. GOAL: deliver a RUNNABLE torchrun harness (e.g. tuning/flagship_distributed.py) that launches the flagship 1.5B decoder under 4D+ZeRO-3 across all 8 H100s, AND the exact per-rank memory budget proving it fits. Compute: at TP=t, the per-rank largest tensor Nmax shrinks from 10,240,000 (ff = 6400×1600) to ~Nmax/t → the SG2 staged-opt scratch dec_tc_sg2_floats = O(50·Nmax/t)·nCTA: find the (TP,ZeRO-3) config where the staged optimizers FIT 80 GB/GPU (so the full 11-optimizer benchmark — not just AdamW — runs at flagship). Give the per-rank params/state/workspace breakdown for a few (DP,TP,PP,SP) configs (e.g. TP8, TP4×DP2, TP2×PP2×DP2) and recommend the config that (i) saturates all 8 GPUs, (ii) fits the staged-opt scratch, (iii) keeps the fused megakernel. Specify HOW the harness builds the flagship TC module per rank (the flagship -include + which staged-opt gate), seeds identically, and verifies cross-rank loss agreement + A/A/A. The user's NORTH STAR: ONE 1.5B model across all 8 GPUs constantly working, the 11-optimizer ranking benchmark on real data. gate_commands: ['python tuning/flagship_distributed.py --help', 'torchrun --nproc_per_node=8 tuning/flagship_distributed.py --steps 2 --dry-run']. Spec -> /workspace/impl_diffs/run_harness.md.` },
]

phase('Scope')
const results = await parallel(agents.map(a => () =>
  agent(a.prompt, { label: a.label, phase: 'Scope', schema: SCHEMA })
    .then(r => ({ name: a.name, ...(r || { area: a.name, spec_path: '', files_changed: [], gate_commands: [], confidence: 'AGENT NULL', risks: ['agent died'], summary: 'null' }) }))))
log(`Distributed scope specs: ${results.filter(r => r && r.spec_path).length}/${agents.length}`)
return results
