export const meta = {
  name: 'supergrok-next-phase',
  description: 'Parallel READ-ONLY: 3 agents each produce an apply-ready spec — flagship dW-spec layer-generalization, no-ncu phase-resolved decoder profiler, and TMA step-4 GEMM-load rewrite',
  phases: [{ title: 'Investigate', detail: '3 agents read code and emit precise apply-ready edit specs to /workspace/impl_diffs/' }],
}
const SCHEMA = {
  type: 'object', additionalProperties: false,
  required: ['area', 'spec_path', 'files_changed', 'gate_commands', 'confidence', 'risks', 'summary'],
  properties: {
    area: { type: 'string' },
    spec_path: { type: 'string', description: '/workspace/impl_diffs/<area>.md — the exact-edit spec the lead applies.' },
    files_changed: { type: 'array', items: { type: 'string' } },
    gate_commands: { type: 'array', items: { type: 'string' }, description: 'Exact command(s) the lead runs to build + gate after applying.' },
    confidence: { type: 'string', description: 'high/med/low that this applies+builds+gates cleanly, + why.' },
    risks: { type: 'array', items: { type: 'string' } },
    summary: { type: 'string', description: '3-5 sentence plain summary of the finding + what the spec does.' },
  },
}
const COMMON = `You are READ-ONLY on the repo at /workspace/SuperGrok1.5 (Read/Grep/Glob freely; do NOT edit the repo, do NOT build/run — the lead applies+builds+gates). Deliverable: write /workspace/impl_diffs/<AREA>.md as APPLY-READY edits — for EACH file to change give the EXACT current snippet to replace (copy it VERBATIM from the live file, enough lines to be unique) and the replacement, as clearly-delimited OLD/NEW blocks; give any NEW files in full. A mismatched OLD block fails to apply, so be precise.
PROJECT FACTS (verified this session): production path = the L3-TC PERSISTENT wgmma megakernel (1 CTA/SM, hand-built sense-reversing GridBarrier, fwd->bwd->AdamW fused in ONE __global__ launch, ascending-CTA/ascending-k fp32 determinism, work-stealing TaskQueue over dW tiles). The GEMM engine is csrc/backends/cuda/sm_90/wgmma.cuh; the CuTe-atom rewrite (steps 1-3: GmmaDescriptor + MMA_64xNx16_F32BF16BF16_SS::fma + warpgroup_*) is ALREADY IN behind SG_TUNED_GEMM_ENGINE (default 0 = hand PTX; 1 = CuTe), VALIDATED bit-identical + fp64-correct end-to-end through mega_decoder_real_adamw_tc. The decoder TC consumer is csrc/fused/sm_90/model_stage_decoder_tc.cuh; the megakernel driver is csrc/fused/sm_90/fused_decoder_megakernel.cuh; the TU is csrc/fused/sm_90/mega_decoder_real_adamw_tc.cu (self-defines SG_TUNED_GEMM_IMPL=1).
HARD GATE every change must hold: fp64 parity (decoder _TC_LOSS_REL=1e-4, grad rel<=0.15 weights / 0.08 biases vs the bf16-faithful oracle) + A/A/A bit-determinism (torch.equal across 3 identical runs). Gate driver: tests/hw/test_decoder_tc.py (CUDA_VISIBLE_DEVICES=0 GATE_SEED=42 python -m pytest tests/hw/test_decoder_tc.py -q). Legal kernel rewrites are TRANSPORT-ONLY (preserve the exact ascending-k fp32 accumulation order); NEW compile knobs must be BYTE-IDENTICAL when OFF (#if-erase to the pre-knob kernel — same PTX/smem/regs). gfx942 + tpu_v6e trees must stay untouched. ncu HW counters are DENIED in this container (no CAP_SYS_ADMIN) — nsys, cuobjdump, ptxas -v, CUDA-event wallclock, and in-kernel clock64() ARE available. Read the cited files IN FULL before writing.`

const agents = [
  { name: 'flagship_dw', label: 'flagship dW-spec L-generalization', prompt: `${COMMON}
AREA: csrc/fused/sm_90/model_stage_decoder_tc.cuh (+ any pinned call sites in fused_decoder_megakernel.cuh). GOAL: generalize the decoder BACKWARD dW-spec enumeration from the HARDCODED 2-layer form to a general kLayers form, so the flagship TC megakernel (d=1600, L=48 — layout header csrc/fused/sm_90/decoder_flagship_layout.cuh, kDecNumTensors=582) FUNCTIONALLY processes all 48 layers. The smem ALREADY fits 1 CTA/SM at L=48 (DecTcSmem is layer-independent: 25,360 B static, ptxas-verified) and the forward weight-cache ALREADY uses the layer-general stride kDecOffsets[wi + li*12] — so this is the ONE remaining functional blocker.
SPECIFICS to fix (read each IN FULL + find ALL siblings):
 (1) dectc_build_dw_specs(... DecDwSpec spec[9] ...) at ~line 2024-2074: it hardcodes wi[9]={2,4,10,12,14,16,22,24,28}, bi[9]={3,5,11,13,15,17,23,25,29}, loop s<8 with li=s/4, kind=s%4, and head spec[8] grad_off=kDecOffsets[28]/bias_off=kDecOffsets[29]. Generalize to 4*L+1 specs: weight tidx(li,kind) = 2 + li*12 + {0,2,8,10}[kind], bias = +1; head out.weight tidx = 2 + 12*L + 2, bias +1 (norm.w/b are 2+12*L,+1; out.w/b are +2,+3). Verify this formula reproduces {2,4,10,12,...,28/29} EXACTLY at L=2 (it must be byte-identical at L=2 so the existing d=128/L=2 gate is unchanged).
 (2) The DecDwSpec spec[9] STACK ARRAY size + every signature/local that says spec[9] (dectc_dw_transpose_operands, dec_dw_transpose_elems, the back-compat overload, the dW phase loop in fused_decoder_megakernel.cuh, the TaskQueue work-item count). Generalize 9 -> (4*kLayers+1). Pick a compile-time bound (dec::kLayers is constexpr) so the array is DecDwSpec spec[4*dec::kLayers+1] (or a constexpr kDecNumDwSpecs). Confirm stack/smem impact is acceptable (at L=2 it MUST stay 9 -> byte-identical).
 (3) kDecMuon2D table (~line 364) lists 2D-weight tensor indices up to 28 for the Muon optimizer 2D-orthogonalization — generalize to all L layers' 2D weights + head. Check kDecNumMuon2D.
 (4) dectc_wbf_convert / the forward weight-bf16 cache (uses kDecOffsets[wi + li*12], li in {0,1}) — confirm its layer loop bound is dec::kLayers (general) or fix it.
 (5) Any other literal 2 / literal 9 / literal 28/29 / li<2 tied to layer count in the decoder TC path. Grep exhaustively.
CRITICAL: every edit MUST be byte-identical at L=2 (dec::kLayers==2) so tests/hw/test_decoder_tc.py is unaffected. The win is purely that at L=48 the SAME code now enumerates 193 specs instead of 9. gate_commands: ['CUDA_VISIBLE_DEVICES=0 GATE_SEED=42 python -m pytest tests/hw/test_decoder_tc.py -q', 'bash scripts/compile_to_object.sh csrc/fused/sm_90/mega_decoder_real_adamw_tc.cu -DWITH_CUTLASS -DSG_TUNED_GEMM_IMPL=1 -DSG_DEC_SCALAR_MEGAKERNEL=0 -DSG_FUSED_SM90_DECODER_LAYOUT_CUH_=1 -include csrc/fused/sm_90/decoder_flagship_layout.cuh']. In risks: note whether the dW WORKSPACE (HBM acts/transpose scratch) carve also needs an L-general size, and whether the launcher computes per-step work from a 2-pinned count. Spec -> /workspace/impl_diffs/flagship_dw.md.` },

  { name: 'profiler', label: 'no-ncu phase-resolved decoder profiler', prompt: `${COMMON}
AREA: NEW files only (a profiling harness) + identify (do NOT edit) any in-kernel timing already present. GOAL: give the lead a RUNNABLE way to get a PHASE-RESOLVED time breakdown of ONE decoder megakernel step (fwd / attn / LN+softmax / bwd / dW-GEMM / optimizer-tail) at the d=2048 bench scale (SG_DEC_BENCH_LAYOUT) WITHOUT ncu (counters denied). The megakernel is a SINGLE launch, so nsys shows one kernel — the breakdown must come from EITHER (a) existing in-kernel clock64() phase counters, OR (b) a new, BYTE-IDENTICAL-WHEN-OFF clock64() instrumentation that accumulates per-phase SM-cycle counts into a __device__ buffer, OR (c) a CUDA-event A/B that toggles phases via existing knobs. FIRST exhaustively search for existing instrumentation: grep clock64, SG_*_PROFILE, SG_*_TIMING, phase timers, smem cycle counters, nsys markers, NVTX, dec bench harness (tuning/decoder_bench.py), the d=2048 build/run path. Report what EXISTS. THEN spec the minimal addition (if needed) behind a new SG_DEC_TC_PHASE_PROF macro (default 0 = byte-identical: the clock64 reads + buffer writes #if-erase entirely — PTX/regs/smem unchanged). Provide the FULL new harness file (e.g. tuning/decoder_phase_profile.py) that builds the d=2048 bench TU with the macro, runs N steps, and prints a per-phase ms + %-of-step table, 8-GPU-idle-aware. Also give the nsys command for the single-launch timeline + occupancy-API (cudaOccupancyMaxActiveBlocksPerMultiprocessor) probe for the achieved CTAs/SM. The DELIVERABLE answers the user's literal question: 'where are the bottlenecks currently, and why'. gate_commands: ['python tuning/decoder_phase_profile.py --help', 'CUDA_VISIBLE_DEVICES=0 python tuning/decoder_phase_profile.py --steps 20']. Spec -> /workspace/impl_diffs/profiler.md.` },

  { name: 'tma', label: 'TMA step-4 GEMM-load rewrite', prompt: `${COMMON}
AREA: csrc/backends/cuda/sm_90/wgmma.cuh (+ minimal host-side tensormap plumbing ONLY if unavoidable). GOAL: spec CuTe step 4 — replace the hand cp.async ring that stages A/B tiles into smem with TMA (cute::SM90_TMA_LOAD / cp.async.bulk.tensor) behind a NEW macro SG_TUNED_GEMM_TMA (default 0 = the current cp.async path, BYTE-IDENTICAL; requires SG_TUNED_GEMM_ENGINE=1 to enable). Read /workspace/cute_plan/{IMPLEMENTATION_PLAN,CUTE_GEMM_SYNTHESIS,WGMMA_ENGINE_SEAM}.md + wgmma.cuh IN FULL + the cp.async staging in csrc/backends/cuda/sm_90/tile_pipeline.cuh + the relevant CuTe headers under third_party/cutlass/include/cute/arch/ (copy_sm90_tma.hpp, copy_sm90_desc.hpp). BE HONEST about the KNOWN BLOCKER documented in the plan: CuTe builds CUtensorMap host-side only (cuTensorMapEncodeTiled), but the persistent megakernel CARVES its A/B operands from a runtime workspace at step time — so TMA needs host-built tensormaps over STEP-STABLE workspace base pointers passed grid-constant (__grid_constant__ const CUtensorMap). Determine whether the decoder's operand bases ARE step-stable (the params blob + the acts/wbf workspace are allocated once and reused every step — verify), and if so spec the host-side map construction (where the launcher lives) + the device-side cute::copy(tma, ...) issue. If the bases are NOT step-stable for some operand (e.g. the dW transposed scratch), say so and scope TMA to ONLY the operands that are stable (fwd/dX A/B), leaving dW on cp.async. The dW transposed-strided gather is the single biggest hand-cp.async cost, so note explicitly whether TMA can reach it. This must stay TRANSPORT-ONLY: TMA changes WHERE/HOW bytes arrive in smem, NOT the wgmma's ascending-k fp32 accumulation — so fp64 parity + A/A/A must be preserved bit-for-bit. gate_commands: ['CUDA_VISIBLE_DEVICES=0 bash scripts/compile_to_object.sh csrc/backends/cuda/sm_90/wgmma_selftest.cu -DSG_TUNED_GEMM_ENGINE=1 -DSG_TUNED_GEMM_TMA=1', 'CUDA_VISIBLE_DEVICES=0 GATE_SEED=42 python -m pytest tests/hw/test_decoder_tc.py -q']. Be honest in confidence (TMA in a persistent runtime-carved kernel is the hardest piece). Spec -> /workspace/impl_diffs/tma.md.` },
]

phase('Investigate')
const results = await parallel(agents.map(a => () =>
  agent(a.prompt, { label: a.label, phase: 'Investigate', schema: SCHEMA })
    .then(r => ({ name: a.name, ...(r || { area: a.name, spec_path: '', files_changed: [], gate_commands: [], confidence: 'AGENT NULL', risks: ['agent died'], summary: 'agent returned null' }) }))))
log(`Specs complete: ${results.filter(r => r && r.spec_path).length}/${agents.length}`)
return results
