export const meta = {
  name: 'supergrok-parallel-tracks',
  description: 'Five parallel READ-ONLY tracks producing apply-ready specs: TP kernel Par-template + in-kernel NVSHMEM all-reduce, TMA megakernel wiring, ViT flagship, Mamba flagship, datasets Layer-A',
  phases: [{ title: 'Tracks', detail: '5 agents each emit an apply-ready exact-edit spec to /workspace/impl_diffs/' }],
}
const SCHEMA = {
  type: 'object', additionalProperties: false,
  required: ['area', 'spec_path', 'files_changed', 'gate_commands', 'confidence', 'risks', 'summary'],
  properties: {
    area: { type: 'string' }, spec_path: { type: 'string' },
    files_changed: { type: 'array', items: { type: 'string' } },
    gate_commands: { type: 'array', items: { type: 'string' } },
    confidence: { type: 'string' }, risks: { type: 'array', items: { type: 'string' } },
    summary: { type: 'string' },
  },
}
const COMMON = `You are READ-ONLY on /workspace/SuperGrok1.5 (Read/Grep/Glob; do NOT edit/build/run). Write /workspace/impl_diffs/<AREA>.md as APPLY-READY edits: for EACH file give the EXACT current snippet (copy VERBATIM from the live file, enough to be unique) as OLD + the NEW replacement; new files in full. A mismatched OLD fails to apply, so be precise.
VERIFIED CONTEXT (this session): production path = the L3-TC PERSISTENT wgmma megakernel (1 CTA/SM, hand GridBarrier, fwd→bwd→AdamW fused in ONE __global__ launch, ascending-CTA/ascending-k fp32 determinism). The FLAGSHIP 1.5B decoder (d=1600,L=48) NOW RUNS single-GPU (loss=ln(99), A/A/A deterministic) after we generalized the decoder TC backward (dW-spec/LN-vec/Muon) to dec::kLayers and emitted decoder_flagship_layout.cuh via megakernel_codegen.py --decoder-layout-flagship. The decoder pattern is the TEMPLATE for ViT/Mamba. CuTe atoms are IN behind SG_TUNED_GEMM_ENGINE (default 0=hand PTX; 1=CuTe), validated bit-identical. NVSHMEM 3.7.0 is INSTALLED (NVSHMEM_HOME=/usr/local/lib/python3.11/dist-packages/nvidia/nvshmem; sm_90 device bitcode libnvshmem_device_sm_90.bc present; compiles with -rdc=true -I$NVSHMEM_HOME/include). The winning distributed mesh is TP8·ZeRO-3.
HARD GATE every change must hold: fp64 parity (decoder _TC_LOSS_REL=1e-4, grad rel<=0.15w/0.08b) + A/A/A bit-determinism. NEW compile knobs BYTE-IDENTICAL when OFF (#if-erase to pre-knob kernel). gfx942/tpu untouched. Read the cited files + the prior specs in /workspace/impl_diffs/ IN FULL first.`

const agents = [
  { name: 'tp_kernel', label: 'TP kernel Par-template + in-kernel NVSHMEM all-reduce', prompt: `${COMMON}
AREA: csrc/fused/sm_90/{fused_decoder_megakernel.cuh, model_stage_decoder_tc.cuh, tp_transport.cuh, parallel_config.cuh} + the launcher csrc/fused/sm_90/mega_decoder_real_adamw_tc_launcher.cu. GOAL: produce APPLY-READY exact edits to (1) template the production decoder megakernel + launcher on ParConfig<DP,TP,PP,SP,Z> + a trailing par::CommCtx (template<OptId Opt, class Par>), with Par=SingleGPU (identity) BYTE-IDENTICAL to today's single-GPU kernel (the design's PTX-diff gate — SingleGPU must emit the SAME PTX). (2) Megatron column/row-shard the in_proj (3d×d) + ff (4d×d, 6400×1600 at flagship) weights per TP rank so per-rank Nmax = kDecMaxTensorNumel/TP (this is what shrinks the SG2 scratch). (3) Wire the IN-KERNEL device-NVSHMEM tp_allreduce_sum_fixed_order (ascending-rank deterministic, preserves A/A/A + fp64 parity) after the row-parallel GEMMs, at the GridBarrier boundary — ONE CTA/GPU enters nvshmemx team-barrier (nest: bar.sync → one-CTA nvshmem_quiet+team_barrier → bar.sync, NOT interleaved or it deadlocks). Consume the step-by-step plan in /workspace/impl_diffs/{dist_step.md §6.C/6.D, tp_nvshmem.md} (now that NVSHMEM is installed, turn the plan into EXACT edits). Address the symmetric-heap requirement: TP comm slots must move from the cudaMalloc workspace to a dedicated nvshmem_malloc symmetric heap (spec the allocator split — a ~216MB/GPU symmetric TP-slot region; acts/grad/state stay on cudaMalloc). All behind SG_HAS_NVSHMEM / Par!=SingleGPU so the default build is byte-identical. gate_commands: ['CUDA_VISIBLE_DEVICES=0 GATE_SEED=42 python -m pytest tests/hw/test_decoder_tc.py -q (SingleGPU byte-identity)','bash scripts/compile_to_object.sh tests/hw/tp_loopback_binding.cu','NVSHMEM_HOME=/usr/local/lib/python3.11/dist-packages/nvidia/nvshmem; bash scripts/compile_to_object.sh tests/hw/tp_loopback_binding.cu -DSG_HAS_NVSHMEM=1 -rdc=true -I$NVSHMEM_HOME/include']. Spec -> /workspace/impl_diffs/tp_kernel.md. Be honest: this is the hardest track.` },

  { name: 'tma_wire', label: 'TMA megakernel wiring (close the 72%/15x GEMM)', prompt: `${COMMON}
AREA: csrc/backends/cuda/sm_90/{wgmma.cuh, tile_pipeline.cuh} + the decoder fwd/dX producer in csrc/fused/sm_90/model_stage_decoder_tc.cuh + PersistentContext + the launcher. GOAL: turn the DOCUMENTED-BUT-DEFERRED §5 of /workspace/impl_diffs/tma.md into APPLY-READY exact edits: wire the gated device TMA-load primitive (already specced in tma.md §2-4, SG_TUNED_GEMM_TMA, requires SG_TUNED_GEMM_ENGINE=1) into the megakernel's fwd/dX A/B staging, replacing the hand cp.async ring for the STEP-STABLE operands (fwd/dX; dW stays cp.async unless DW_STAGE on). Add the CUtensorMap field to PersistentContext, build the descriptors host-side in the launcher over the step-stable workspace bases (tma.md §1 verified they ARE step-stable), pass them grid-constant. ALL byte-identical when SG_TUNED_GEMM_TMA=0 (the producer keeps cp.async; #if-erase). TRANSPORT-ONLY: the wgmma ascending-k fp32 order is untouched → fp64 parity + A/A/A preserved. This closes bottleneck LEVER ① (the GEMM at 6.5% of roofline / 72% of step, measured). gate_commands: ['CUDA_VISIBLE_DEVICES=0 bash scripts/compile_to_object.sh csrc/fused/sm_90/mega_decoder_real_adamw_tc.cu -DWITH_CUTLASS -DSG_TUNED_GEMM_IMPL=1 -DSG_TUNED_GEMM_ENGINE=1 -DSG_TUNED_GEMM_TMA=1','CUDA_VISIBLE_DEVICES=0 GATE_SEED=42 python -m pytest tests/hw/test_decoder_tc.py -q']. Spec -> /workspace/impl_diffs/tma_wire.md.` },

  { name: 'vit_flagship', label: 'ViT flagship (layout + dW-generalization)', prompt: `${COMMON}
AREA: grokking_optimizers/megakernel_codegen.py (ViT emitters _vit_*) + csrc/fused/sm_90/model_stage_vit_tc.cuh + vit_layout.cuh. GOAL: mirror the DECODER flagship work for ViT. Flagship ViT dims = MODEL_SCALES_BY_MODEL['flagship']['vit'] (grokking_race_v2.py — d=1664, L=48, heads=16). (1) Parameterize the ViT layout emitter by (d,layers,...) like decoder, add decoder_flagship-style vit_flagship_layout_header() + --vit-layout-flagship, keep the existing layout byte-identical. (2) Generalize any 2/L-layer-pinned enumeration in the ViT TC backward (the ViT analogues of dectc_build_dw_specs / kLnVecTensorIdx / kDecMuon2D — model_stage_vit_tc.cuh has VitDwSpec spec[10], kLnVecTensorIdx, etc.) to vit::kLayers via formulas proven byte-identical at the current L. Study the applied decoder spec /workspace/impl_diffs/flagship_dw.md as the exact template. gate_commands: ['python -m grokking_optimizers.megakernel_codegen --vit-layout > /tmp/v.cuh && diff /tmp/v.cuh csrc/fused/sm_90/vit_layout.cuh','python -m grokking_optimizers.megakernel_codegen --vit-layout-flagship > csrc/fused/sm_90/vit_flagship_layout.cuh','bash scripts/compile_to_object.sh csrc/fused/sm_90/mega_vit_real_adamw_tc.cu -DWITH_CUTLASS -DSG_TUNED_GEMM_IMPL=1 -DSG_DEC_SCALAR_MEGAKERNEL=0 -DSG_FUSED_SM90_VIT_LAYOUT_CUH_=1 -include csrc/fused/sm_90/vit_flagship_layout.cuh']. Spec -> /workspace/impl_diffs/vit_flagship.md.` },

  { name: 'mamba_flagship', label: 'Mamba flagship (layout + dW-generalization)', prompt: `${COMMON}
AREA: grokking_optimizers/megakernel_codegen.py (Mamba emitters) + csrc/fused/sm_90/model_stage_mamba_tc.cuh + mamba3_layout.cuh + fused_mamba_megakernel.cuh. GOAL: mirror the DECODER flagship work for Mamba-3. Flagship Mamba dims = MODEL_SCALES_BY_MODEL['flagship']['mamba'] (grokking_race_v2.py — d=2048, L=24). (1) Parameterize the Mamba layout emitter + add mamba_flagship_layout_header() + --mamba-layout-flagship, existing layout byte-identical. (2) Generalize any 2/L-layer-pinned enumeration in the Mamba TC backward (fused_mamba_megakernel.cuh has MbDwSpec spec[8]; find its dW-spec builder + any LN/SSM per-layer tables) to mb::kLayers via formulas byte-identical at the current L. Use /workspace/impl_diffs/flagship_dw.md (decoder) as the template; Mamba's selective-SSM has extra per-layer state (A/B/C/D, conv) — enumerate those too. gate_commands: ['python -m grokking_optimizers.megakernel_codegen --mamba-layout > /tmp/m.cuh && diff /tmp/m.cuh csrc/fused/sm_90/mamba3_layout.cuh','python -m grokking_optimizers.megakernel_codegen --mamba-layout-flagship > csrc/fused/sm_90/mamba_flagship_layout.cuh','bash scripts/compile_to_object.sh csrc/fused/sm_90/mega_mamba_real_adamw_tc.cu -DWITH_CUTLASS -DSG_TUNED_GEMM_IMPL=1 -DSG_DEC_SCALAR_MEGAKERNEL=0 -DSG_FUSED_SM90_MAMBA_LAYOUT_CUH_=1 -include csrc/fused/sm_90/mamba_flagship_layout.cuh']. Spec -> /workspace/impl_diffs/mamba_flagship.md.` },

  { name: 'datasets', label: 'datasets Layer-A (FineWeb/ImageNet/GiftEval)', prompt: `${COMMON}
AREA: grokking_race_v2.py. Re-validate + refine the EXISTING spec /workspace/impl_diffs/datasets.md against the CURRENT live file (line numbers may have drifted) into APPLY-READY exact edits. GOAL: Layer-A data plumbing ONLY — make_data_for_task dispatch on a new DEFAULT-OFF c['data_source'] returning (streaming train iterator, FIXED eval probe) for FineWeb-Edu (decoder) / ImageNet-1k (ViT) / GiftEvalPretrain (mamba); a fixed-probe-capped evaluate (seconds not minutes); the loss-PLATEAU EarlyStopper for LM/forecasting (KEEP 0.95-accuracy for ViT). DEFAULT-OFF so the mod-97 path is BYTE-IDENTICAL (kernels are size-pinned; stub the dataset sources behind an importable interface, NO downloads). Also confirm the dead-code removals (MambaModel/SelectiveSSMLayer/_maybe_wrap_cuda_graph) are still valid. gate_commands: ['python grokking_race_v2.py --gpus 2 --optimizers adamw --num-seeds 1 --early-stop-max-steps 300 --no-status-server --output /tmp/smoke','python -c "import grokking_race_v2"']. Spec -> /workspace/impl_diffs/datasets_v2.md.` },
]

phase('Tracks')
const results = await parallel(agents.map(a => () =>
  agent(a.prompt, { label: a.label, phase: 'Tracks', schema: SCHEMA })
    .then(r => ({ name: a.name, ...(r || { area: a.name, spec_path: '', files_changed: [], gate_commands: [], confidence: 'AGENT NULL', risks: ['agent died'], summary: 'null' }) }))))
log(`Track specs: ${results.filter(r => r && r.spec_path).length}/${agents.length}`)
return results
