# csrc/fused/tpu_v5p/mega_vit_lion.py
# GENERATED by megakernel_codegen.py — cell (vit, lion,
# tpu_v5p), tier=L3_FWD_BWD_OPT (pallas: single fused program).
#
# The TPU L3 megakernel is one pl.pallas_call composing forward → backward →
# optimizer; XLA owns the allocation so the solver always reports L3. The body
# is emitted from the JAX kernel tree (grokking_optimizers/kernels/tpu_v5p).
import jax  # noqa: F401  (structural stub; production generator emits the body)
