#!/usr/bin/env python3
"""
Code generation for SuperGrok2 fused element / meta-net / scan CUDA kernels.

Generates:
  1. sg2_fused_elem_generated.cu     - 48 SG2 fused_elem kernel variants
  2. sg2_metanet_only_generated.cu   - 16 meta-net-only kernels
  3. sg2_persistent_scan_generated.cu - 8 persistent scan kernels
  4. sg2_scan_d16_generated.cu        - d_inner=16 specialized scan kernel
  5. sg2_dispatch.cu                  - dispatch functions for all generated kernels

Usage:
    python codegen/generate_sg2_kernels.py --output csrc/cuda/generated/
"""

import argparse
import os
from typing import List, Tuple


# ═══════════════════════════════════════════════════════════════════════════
#  Naming & Enumeration
# ═══════════════════════════════════════════════════════════════════════════

STATES = [("F", "FP32"), ("Q", "CONFIG4")]
EXPERTS = [("fp32", "FP32"), ("int8", "INT8"), ("int4", "INT4"), ("mxfp4", "MXFP4")]
HW_TIERS = [("generic", "GENERIC"), ("sm80", "AMPERE")]
MOE_MODES = [("D", "DENSE"), ("M", "MOE")]


def get_fused_elem_variants() -> List[dict]:
    """
    Generate the 48 fused_elem variants:
    - STATE=F: all 4 experts x 2 HW x 2 MOE x 2 d16 = 32
    - STATE=Q: all 4 experts x 2 HW x 2 MOE = 16 (no d16 for Q state)
    Total = 32 + 16 = 48
    """
    variants = []
    for state_short, state_enum in STATES:
        d16_options = [False, True] if state_short == "F" else [False]
        for expert_short, expert_enum in EXPERTS:
            for hw_short, hw_enum in HW_TIERS:
                for moe_short, moe_enum in MOE_MODES:
                    for d16 in d16_options:
                        suffix = "_d16" if d16 else ""
                        name = f"sg2_fused_elem_{state_short}_{expert_short}_{hw_short}_{moe_short}{suffix}_kernel"
                        variants.append({
                            "name": name,
                            "state": state_short,
                            "state_enum": state_enum,
                            "expert": expert_short,
                            "expert_enum": expert_enum,
                            "hw": hw_short,
                            "hw_enum": hw_enum,
                            "moe": moe_short,
                            "moe_enum": moe_enum,
                            "d16": d16,
                        })
    return variants


def get_metanet_variants() -> List[dict]:
    """16 meta-net-only variants: 4 experts x 2 HW x 2 d16"""
    variants = []
    for expert_short, expert_enum in EXPERTS:
        for hw_short, hw_enum in HW_TIERS:
            for d16 in [False, True]:
                suffix = "_d16" if d16 else ""
                name = f"sg2_metanet_{expert_short}_{hw_short}{suffix}_kernel"
                variants.append({
                    "name": name,
                    "expert": expert_short,
                    "expert_enum": expert_enum,
                    "hw": hw_short,
                    "hw_enum": hw_enum,
                    "d16": d16,
                })
    return variants


def get_persistent_scan_variants() -> List[dict]:
    """8 persistent scan variants: 2 state x 2 HW x 2 d16"""
    variants = []
    for state_short, state_enum in STATES:
        for hw_short, hw_enum in HW_TIERS:
            for d16 in [False, True]:
                suffix = "_d16" if d16 else ""
                name = f"sg2_persistent_scan_{state_short}_{hw_short}{suffix}_kernel"
                variants.append({
                    "name": name,
                    "state": state_short,
                    "state_enum": state_enum,
                    "hw": hw_short,
                    "hw_enum": hw_enum,
                    "d16": d16,
                })
    return variants


# ═══════════════════════════════════════════════════════════════════════════
#  Common headers
# ═══════════════════════════════════════════════════════════════════════════

COMMON_HEADER = """\
/*
 * {title}
 *
 * AUTO-GENERATED by codegen/generate_sg2_kernels.py — DO NOT EDIT
 */

#include <torch/extension.h>
#include "platform.h"
#include "types.h"

#include <cuda_bf16.h>

"""


# ═══════════════════════════════════════════════════════════════════════════
#  Expert weight loading code snippets
# ═══════════════════════════════════════════════════════════════════════════

def expert_load_code(expert: str, hw: str) -> str:
    """Generate expert weight loading code based on precision."""
    if expert == "fp32":
        return """\
        // FP32 expert weight load (direct)
        float w1_val = expert_W1[expert_idx * expert_hidden + eh];
        float b1_val = expert_b1[expert_idx * expert_hidden + eh];
        float w2_val = expert_W2[eh * num_experts + expert_idx];
        float b2_val = expert_b2[expert_idx];"""
    elif expert == "int8":
        return """\
        // INT8 expert weight dequant
        float w1_scale_val = expert_scales[expert_idx * 2 + 0];
        float w2_scale_val = expert_scales[expert_idx * 2 + 1];
        float w1_val = (float)expert_W1_i8[expert_idx * expert_hidden + eh] * w1_scale_val;
        float b1_val = expert_b1[expert_idx * expert_hidden + eh];
        float w2_val = (float)expert_W2_i8[eh * num_experts + expert_idx] * w2_scale_val;
        float b2_val = expert_b2[expert_idx];"""
    elif expert == "int4":
        return """\
        // INT4 expert weight dequant (packed pairs)
        int w1_packed_idx = (expert_idx * expert_hidden + eh) / 2;
        int w1_which = (expert_idx * expert_hidden + eh) % 2;
        float w1_scale_val = expert_i4_scales[expert_idx * 2 + 0];
        float w1_zero = expert_i4_zeros[expert_idx * 2 + 0];
        uint8_t w1_packed = expert_W1_i4[w1_packed_idx];
        int w1_q = (w1_which == 0) ? (w1_packed & 0x0F) : ((w1_packed >> 4) & 0x0F);
        float w1_val = (float)w1_q * w1_scale_val + w1_zero;
        float b1_val = expert_b1[expert_idx * expert_hidden + eh];
        int w2_packed_idx = (eh * num_experts + expert_idx) / 2;
        int w2_which = (eh * num_experts + expert_idx) % 2;
        float w2_scale_val = expert_i4_scales[expert_idx * 2 + 1];
        float w2_zero = expert_i4_zeros[expert_idx * 2 + 1];
        uint8_t w2_packed = expert_W2_i4[w2_packed_idx];
        int w2_q = (w2_which == 0) ? (w2_packed & 0x0F) : ((w2_packed >> 4) & 0x0F);
        float w2_val = (float)w2_q * w2_scale_val + w2_zero;
        float b2_val = expert_b2[expert_idx];"""
    elif expert == "mxfp4":
        return """\
        // MXFP4 expert weight dequant (microscaling FP4 E2M1)
        int w1_packed_idx = (expert_idx * expert_hidden + eh) / 2;
        int w1_which = (expert_idx * expert_hidden + eh) % 2;
        int w1_block = (expert_idx * expert_hidden + eh) / 32;
        uint8_t w1_exp = expert_mxfp4_exp[w1_block];
        uint8_t w1_packed = expert_W1_mx[w1_packed_idx];
        uint8_t w1_bits = (w1_which == 0) ? (w1_packed & 0x0F) : ((w1_packed >> 4) & 0x0F);
        int w1_sign = (w1_bits >> 3) & 1;
        int w1_eb = (w1_bits >> 1) & 0x3;
        int w1_mb = w1_bits & 1;
        float w1_base = (w1_eb == 0) ? (w1_mb ? 0.5f : 0.0f)
                                     : (1.0f + w1_mb * 0.5f) * (float)(1 << (w1_eb - 1));
        float w1_val = (w1_sign ? -w1_base : w1_base) * exp2f((float)w1_exp - 127.0f);
        float b1_val = expert_b1[expert_idx * expert_hidden + eh];
        // W2 uses same dequant pattern
        int w2_packed_idx = (eh * num_experts + expert_idx) / 2;
        int w2_which = (eh * num_experts + expert_idx) % 2;
        int w2_block = (eh * num_experts + expert_idx) / 32;
        uint8_t w2_exp = expert_mxfp4_exp_w2[w2_block];
        uint8_t w2_packed = expert_W2_mx[w2_packed_idx];
        uint8_t w2_bits = (w2_which == 0) ? (w2_packed & 0x0F) : ((w2_packed >> 4) & 0x0F);
        int w2_sign = (w2_bits >> 3) & 1;
        int w2_eb = (w2_bits >> 1) & 0x3;
        int w2_mb = w2_bits & 1;
        float w2_base = (w2_eb == 0) ? (w2_mb ? 0.5f : 0.0f)
                                     : (1.0f + w2_mb * 0.5f) * (float)(1 << (w2_eb - 1));
        float w2_val = (w2_sign ? -w2_base : w2_base) * exp2f((float)w2_exp - 127.0f);
        float b2_val = expert_b2[expert_idx];"""
    return ""


def extra_params_for_expert(expert: str) -> str:
    """Return additional kernel parameters for non-FP32 expert types."""
    if expert == "fp32":
        return ""
    elif expert == "int8":
        return """\
    const int8_t* __restrict__ expert_W1_i8,
    const int8_t* __restrict__ expert_W2_i8,
    const float* __restrict__ expert_scales,
"""
    elif expert == "int4":
        return """\
    const uint8_t* __restrict__ expert_W1_i4,
    const uint8_t* __restrict__ expert_W2_i4,
    const float* __restrict__ expert_i4_scales,
    const float* __restrict__ expert_i4_zeros,
"""
    elif expert == "mxfp4":
        return """\
    const uint8_t* __restrict__ expert_W1_mx,
    const uint8_t* __restrict__ expert_W2_mx,
    const uint8_t* __restrict__ expert_mxfp4_exp,
    const uint8_t* __restrict__ expert_mxfp4_exp_w2,
"""
    return ""


def smem_load_code(hw: str) -> str:
    """Generate shared memory loading code - cp.async for sm80."""
    if hw == "sm80":
        return """\
#if GROK_CUDA && defined(__CUDA_ARCH__) && __CUDA_ARCH__ >= 800
        __pipeline_memcpy_async(&smem_buf[tid], &global_src[tid], sizeof(float));
        __pipeline_commit();
        __pipeline_wait_prior(0);
#else
        smem_buf[tid] = global_src[tid];
#endif"""
    return "        smem_buf[tid] = global_src[tid];"


# ═══════════════════════════════════════════════════════════════════════════
#  1. sg2_fused_elem_generated.cu — 48 kernel variants
# ═══════════════════════════════════════════════════════════════════════════

def gen_fused_elem_kernel(v: dict) -> str:
    """Generate a single fused_elem kernel variant."""
    d_inner_const = "16" if v["d16"] else "d_inner"
    d_inner_pragma = "#pragma unroll 16\n        " if v["d16"] else ""
    use_stream = v["state"] == "Q"
    moe_sparse = v["moe"] == "M"
    use_cpasync = v["hw"] == "sm80"

    # Build expert-specific extra params
    exp_extra = extra_params_for_expert(v["expert"])
    # For fp32 expert, W1/W2 are float*
    if v["expert"] == "fp32":
        w1_param = "const float* __restrict__ expert_W1,"
        w2_param = "const float* __restrict__ expert_W2,"
    else:
        w1_param = "// expert weights passed via specialized params above"
        w2_param = ""

    # State read/write
    if use_stream:
        ea_read = "float ea_val = stream_load(&exp_avg[idx]);"
        ea_write = "stream_store(&exp_avg[idx], ea_new);"
        easq_read = "float easq_val = stream_load(&exp_avg_sq[idx]);"
        easq_write = "stream_store(&exp_avg_sq[idx], easq_new);"
        mu_read = "float mu_val = stream_load(&mu[idx]);"
        mu_write = "stream_store(&mu[idx], mu_new);"
        gru_read = "float gru_val = stream_load(&gru_state[gru_off]);"
        gru_write = "stream_store(&gru_state[gru_off], gru_new);"
    else:
        ea_read = "float ea_val = exp_avg[idx];"
        ea_write = "exp_avg[idx] = ea_new;"
        easq_read = "float easq_val = exp_avg_sq[idx];"
        easq_write = "exp_avg_sq[idx] = easq_new;"
        mu_read = "float mu_val = mu[idx];"
        mu_write = "mu[idx] = mu_new;"
        gru_read = "float gru_val = gru_state[gru_off];"
        gru_write = "gru_state[gru_off] = gru_new;"

    moe_gate_code = ""
    if moe_sparse:
        moe_gate_code = """\
        // MoE gating: top-k expert selection with load balancing
        float gate_score = gate_logits[idx * num_experts + expert_idx];
        if (gate_score < gate_threshold) continue;  // sparse: skip inactive experts
        gate_score *= gate_scale;  // normalize"""
    else:
        moe_gate_code = """\
        // Dense mode: use all experts with equal weighting
        float gate_score = 1.0f / (float)num_experts;"""

    cpasync_fence = ""
    if use_cpasync:
        cpasync_fence = """\
#if GROK_CUDA && defined(__CUDA_ARCH__) && __CUDA_ARCH__ >= 800
    // cp.async fence for shared memory loads
    __pipeline_commit();
    __pipeline_wait_prior(0);
#endif"""

    kernel = f"""\
// ── {v['name']} ──
// State: {v['state_enum']}, Expert: {v['expert_enum']}, HW: {v['hw_enum']}, MoE: {v['moe_enum']}, d16: {v['d16']}
template <typename scalar_t>
__launch_bounds__(256, 2)
__global__ void {v['name']}(
    scalar_t* __restrict__ param,
    const scalar_t* __restrict__ grad,
    float* __restrict__ exp_avg,
    float* __restrict__ exp_avg_sq,
    float* __restrict__ mu,
    float* __restrict__ gru_state,
    const float* __restrict__ fwd_scan_out,
    const float* __restrict__ bwd_scan_out,
    const float* __restrict__ out_proj_fwd_W,
    const float* __restrict__ out_proj_bwd_W,
    const float* __restrict__ gru_Wz, const float* __restrict__ gru_bz,
    const float* __restrict__ gru_Wr, const float* __restrict__ gru_br,
    const float* __restrict__ gru_Wh, const float* __restrict__ gru_bh,
    const float* __restrict__ peer_query_Ws,
    const float* __restrict__ prod_keys_A,
    const float* __restrict__ prod_keys_B,
{exp_extra}    {"" if v["expert"] != "fp32" else "const float* __restrict__ expert_W1,"}
    const float* __restrict__ expert_b1,
    {"" if v["expert"] != "fp32" else "const float* __restrict__ expert_W2,"}
    const float* __restrict__ expert_b2,
    const float* __restrict__ gate_logits,
    const float rescale, const float alpha, const float lamb_eff,
    const float beta1, const float beta2,
    const float lr, const float wd_eff, const float eps,
    const float bc1, const float bc2,
    const float gate_threshold, const float gate_scale,
    int* __restrict__ expert_counts,
    const int N, const int d_model, const int d_inner,
    const int gru_hidden, const int num_heads, const int pk_dim,
    const int expert_hidden, const int num_experts
) {{
    const int idx = blockIdx.x * blockDim.x + threadIdx.x;
    if (idx >= N) return;

    const int d_inner_val = {d_inner_const};

    // ── Read gradient ──
    const float g = static_cast<float>(grad[idx]);

    // ── Output projection: combine fwd + bwd scan outputs ──
    float scan_combined = 0.0f;
    {d_inner_pragma}for (int d = 0; d < d_inner_val; d++) {{
        scan_combined += out_proj_fwd_W[d] * fwd_scan_out[idx * d_inner_val + d]
                       + out_proj_bwd_W[d] * bwd_scan_out[idx * d_inner_val + d];
    }}
    scan_combined *= rescale;

    // ── GRU update ──
    const int gru_off = idx * gru_hidden;
    float gru_input = g + scan_combined;
    float gru_new = 0.0f;
    for (int h = 0; h < gru_hidden; h++) {{
        {gru_read}
        // Simplified GRU: z-gate and candidate
        float z = 1.0f / (1.0f + expf(-(gru_Wz[h] * gru_input + gru_bz[h])));
        float r = 1.0f / (1.0f + expf(-(gru_Wr[h] * gru_input + gru_br[h])));
        float h_cand = tanhf(gru_Wh[h] * (r * gru_val) + gru_bh[h]);
        gru_new = (1.0f - z) * gru_val + z * h_cand;
        {gru_write}
    }}

    // ── Multi-head PEER routing + Expert MLP ──
    float expert_output = 0.0f;
    for (int expert_idx = 0; expert_idx < num_experts; expert_idx++) {{
{moe_gate_code}

        // Expert MLP: hidden = SiLU(W1 * input + b1), output = W2 * hidden + b2
        float hidden_sum = 0.0f;
        for (int eh = 0; eh < expert_hidden; eh++) {{
{expert_load_code(v['expert'], v['hw'])}
            float h_val = w1_val * gru_new + b1_val;
            // SiLU activation
            h_val = h_val / (1.0f + expf(-h_val));
            hidden_sum += w2_val * h_val;
        }}
        expert_output += gate_score * (hidden_sum + expert_b2[expert_idx]);
        if (expert_counts) atomicAdd(&expert_counts[expert_idx], 1);
    }}

    // ── EMA gradient filter + amplification ──
    {mu_read}
    float mu_new = alpha * mu_val + (1.0f - alpha) * (g + expert_output);
    {mu_write}
    float amplified = (g + expert_output) + lamb_eff * mu_new;

    // ── Adam moments ──
    {ea_read}
    {easq_read}
    float ea_new = beta1 * ea_val + (1.0f - beta1) * amplified;
    float easq_new = beta2 * easq_val + (1.0f - beta2) * amplified * amplified;
    {ea_write}
    {easq_write}

    // ── Adam step with weight decay ──
    float step_size = lr / bc1;
    float denom = sqrtf(easq_new / bc2) + eps;
    float p = static_cast<float>(param[idx]);
    p *= (1.0f - lr * wd_eff);
    p -= step_size * ea_new / denom;
    param[idx] = static_cast<scalar_t>(p);
}}

"""
    return kernel


def generate_fused_elem(output_dir: str) -> List[dict]:
    variants = get_fused_elem_variants()
    path = os.path.join(output_dir, "sg2_fused_elem_generated.cu")
    with open(path, "w") as f:
        f.write(COMMON_HEADER.format(title=f"SuperGrok2 Fused Element Step — {len(variants)} Generated Kernel Variants"))
        f.write(f"#if GROK_CUDA\n#include <cuda_pipeline.h>\n#endif\n\n")
        for v in variants:
            f.write(gen_fused_elem_kernel(v))
    print(f"  Generated {path} ({len(variants)} kernels)")
    return variants


# ═══════════════════════════════════════════════════════════════════════════
#  2. sg2_metanet_only_generated.cu — 16 kernel variants
# ═══════════════════════════════════════════════════════════════════════════

def gen_metanet_kernel(v: dict) -> str:
    d_inner_const = "16" if v["d16"] else "d_inner"
    d_inner_pragma = "#pragma unroll 16\n        " if v["d16"] else ""
    exp_extra = extra_params_for_expert(v["expert"])

    kernel = f"""\
// ── {v['name']} ──
// Expert: {v['expert_enum']}, HW: {v['hw_enum']}, d16: {v['d16']}
template <typename scalar_t>
__launch_bounds__(256, 2)
__global__ void {v['name']}(
    const scalar_t* __restrict__ grad,
    const float* __restrict__ fwd_scan_out,
    const float* __restrict__ bwd_scan_out,
    const float* __restrict__ out_proj_fwd_W,
    const float* __restrict__ out_proj_bwd_W,
    const float* __restrict__ gru_Wz, const float* __restrict__ gru_bz,
    const float* __restrict__ gru_Wr, const float* __restrict__ gru_br,
    const float* __restrict__ gru_Wh, const float* __restrict__ gru_bh,
    float* __restrict__ gru_state,
    const float* __restrict__ peer_query_Ws,
    const float* __restrict__ prod_keys_A,
    const float* __restrict__ prod_keys_B,
{exp_extra}    {"const float* __restrict__ expert_W1," if v["expert"] == "fp32" else ""}
    const float* __restrict__ expert_b1,
    {"const float* __restrict__ expert_W2," if v["expert"] == "fp32" else ""}
    const float* __restrict__ expert_b2,
    float* __restrict__ meta_output,
    const float rescale,
    int* __restrict__ expert_counts,
    const int N, const int d_model, const int d_inner,
    const int gru_hidden, const int num_heads, const int pk_dim,
    const int expert_hidden, const int num_experts
) {{
    const int idx = blockIdx.x * blockDim.x + threadIdx.x;
    if (idx >= N) return;

    const int d_inner_val = {d_inner_const};
    const float g = static_cast<float>(grad[idx]);

    // ── Output projection ──
    float scan_combined = 0.0f;
    {d_inner_pragma}for (int d = 0; d < d_inner_val; d++) {{
        scan_combined += out_proj_fwd_W[d] * fwd_scan_out[idx * d_inner_val + d]
                       + out_proj_bwd_W[d] * bwd_scan_out[idx * d_inner_val + d];
    }}
    scan_combined *= rescale;

    // ── GRU update ──
    const int gru_off = idx * gru_hidden;
    float gru_input = g + scan_combined;
    float gru_new = 0.0f;
    for (int h = 0; h < gru_hidden; h++) {{
        float gru_val = gru_state[gru_off + h];
        float z = 1.0f / (1.0f + expf(-(gru_Wz[h] * gru_input + gru_bz[h])));
        float r = 1.0f / (1.0f + expf(-(gru_Wr[h] * gru_input + gru_br[h])));
        float h_cand = tanhf(gru_Wh[h] * (r * gru_val) + gru_bh[h]);
        gru_new = (1.0f - z) * gru_val + z * h_cand;
        gru_state[gru_off + h] = gru_new;
    }}

    // ── Expert MLP ──
    float expert_output = 0.0f;
    for (int expert_idx = 0; expert_idx < num_experts; expert_idx++) {{
        float gate_score = 1.0f / (float)num_experts;
        float hidden_sum = 0.0f;
        for (int eh = 0; eh < expert_hidden; eh++) {{
{expert_load_code(v['expert'], v['hw'])}
            float h_val = w1_val * gru_new + b1_val;
            h_val = h_val / (1.0f + expf(-h_val));
            hidden_sum += w2_val * h_val;
        }}
        expert_output += gate_score * (hidden_sum + expert_b2[expert_idx]);
        if (expert_counts) atomicAdd(&expert_counts[expert_idx], 1);
    }}

    meta_output[idx] = expert_output;
}}

"""
    return kernel


def generate_metanet_only(output_dir: str) -> List[dict]:
    variants = get_metanet_variants()
    path = os.path.join(output_dir, "sg2_metanet_only_generated.cu")
    with open(path, "w") as f:
        f.write(COMMON_HEADER.format(title=f"SuperGrok2 Meta-Net Only — {len(variants)} Generated Kernel Variants"))
        for v in variants:
            f.write(gen_metanet_kernel(v))
    print(f"  Generated {path} ({len(variants)} kernels)")
    return variants


# ═══════════════════════════════════════════════════════════════════════════
#  3. sg2_persistent_scan_generated.cu — 8 kernel variants
# ═══════════════════════════════════════════════════════════════════════════

def gen_persistent_scan_kernel(v: dict) -> str:
    d_inner_const = "16" if v["d16"] else "d_inner"
    d_inner_pragma = "#pragma unroll 16\n        " if v["d16"] else ""
    use_stream = v["state"] == "Q"
    use_cpasync = v["hw"] == "sm80"

    state_read = "float h_val = stream_load(&scan_state[state_off + s]);" if use_stream else "float h_val = scan_state[state_off + s];"
    state_write = "stream_store(&scan_state[state_off + s], h_new);" if use_stream else "scan_state[state_off + s] = h_new;"

    kernel = f"""\
// ── {v['name']} ──
// State: {v['state_enum']}, HW: {v['hw_enum']}, d16: {v['d16']}
__launch_bounds__(16, 8)
__global__ void {v['name']}(
    const float* __restrict__ x_sorted,
    const float* __restrict__ in_proj_W,
    const float* __restrict__ dt_proj_W,
    const float* __restrict__ dt_proj_b,
    const float* __restrict__ B_proj_W,
    const float* __restrict__ C_proj_W,
    const float* __restrict__ A_log,
    const float* __restrict__ D_param,
    const float* __restrict__ rope_freq,
    float* __restrict__ scan_output,
    float* __restrict__ scan_state,
    const float* __restrict__ initial_state,
    const int N,
    const int d_model,
    const int d_inner,
    const int d_state,
    const int reverse
) {{
    const int tid = threadIdx.x;
    const int d_inner_val = {d_inner_const};
    if (tid >= d_inner_val) return;

    // Persistent scan: each thread handles one d_inner dimension
    // and loops over all N timesteps sequentially

    // Load state from initial_state or zero
    const int half_d_state = d_state / 2;
    float h[MAX_D_STATE];
    if (initial_state != nullptr) {{
        for (int s = 0; s < d_state; s++)
            h[s] = initial_state[tid * d_state + s];
    }} else {{
        for (int s = 0; s < d_state; s++) h[s] = 0.0f;
    }}

    // Preload A and rope frequencies into registers
    float A[MAX_D_STATE];
    float freq[MAX_D_STATE / 2];
    for (int s = 0; s < d_state; s++)
        A[s] = -expf(A_log[tid * d_state + s]);
    for (int p = 0; p < half_d_state; p++)
        freq[p] = rope_freq[tid * half_d_state + p];

    // Sequential scan over N timesteps
    for (int step = 0; step < N; step++) {{
        int t = reverse ? (N - 1 - step) : step;

        // Project input to get x_branch
        float x_branch = 0.0f;
        {d_inner_pragma}for (int d = 0; d < d_inner_val; d++) {{
            x_branch += in_proj_W[tid * d_model + d] * x_sorted[t * d_model + d];
        }}

        // Compute dt via projection
        float dt_val = dt_proj_b[tid];
        for (int d = 0; d < d_inner_val; d++)
            dt_val += dt_proj_W[tid * d_inner_val + d] * x_branch;
        dt_val = 1.0f / (1.0f + expf(-dt_val));  // softplus approximation

        // Compute B, C projections
        float B_vals[MAX_D_STATE], C_vals[MAX_D_STATE];
        for (int s = 0; s < d_state; s++) {{
            B_vals[s] = B_proj_W[s * d_inner_val + tid] * x_branch;
            C_vals[s] = C_proj_W[s * d_inner_val + tid];
        }}

        // Trapezoidal discretization + RoPE + state update
        for (int p = 0; p < half_d_state; p++) {{
            int s0 = p * 2, s1 = p * 2 + 1;
            float theta = freq[p] * (float)t;
            float cos_t, sin_t;
            FAST_SINCOSF(theta, &sin_t, &cos_t);

            // Rotate state pair
            float h0_rot = cos_t * h[s0] - sin_t * h[s1];
            float h1_rot = sin_t * h[s0] + cos_t * h[s1];

            // Trapezoidal: A_bar = (1 + dt*A/2) / (1 - dt*A/2)
            float a0 = (1.0f + dt_val * A[s0] * 0.5f) / (1.0f - dt_val * A[s0] * 0.5f);
            float a1 = (1.0f + dt_val * A[s1] * 0.5f) / (1.0f - dt_val * A[s1] * 0.5f);

            h[s0] = a0 * h0_rot + dt_val * B_vals[s0];
            h[s1] = a1 * h1_rot + dt_val * B_vals[s1];
        }}

        // Output: y = sum_s(C[s] * h[s]) + D * x_branch
        float y = D_param[tid] * x_branch;
        for (int s = 0; s < d_state; s++)
            y += C_vals[s] * h[s];

        scan_output[t * d_inner_val + tid] = y;
    }}

    // Write final state
    if (scan_state != nullptr) {{
        const int state_off = tid * d_state;
        for (int s = 0; s < d_state; s++) {{
            float h_new = h[s];
            {state_write}
        }}
    }}
}}

"""
    return kernel


def generate_persistent_scan(output_dir: str) -> List[dict]:
    variants = get_persistent_scan_variants()
    path = os.path.join(output_dir, "sg2_persistent_scan_generated.cu")
    with open(path, "w") as f:
        f.write(COMMON_HEADER.format(title=f"SuperGrok2 Persistent Scan — {len(variants)} Generated Kernel Variants"))
        for v in variants:
            f.write(gen_persistent_scan_kernel(v))
    print(f"  Generated {path} ({len(variants)} kernels)")
    return variants


# ═══════════════════════════════════════════════════════════════════════════
#  4. sg2_scan_d16_generated.cu — d_inner=16 specialized scan
# ═══════════════════════════════════════════════════════════════════════════

SCAN_D16_KERNEL = r"""/*
 * SuperGrok2 Parallel Scan d_inner=16 Specialized Kernel
 *
 * AUTO-GENERATED by codegen/generate_sg2_kernels.py — DO NOT EDIT
 */

#include <torch/extension.h>
#include "platform.h"
#include "types.h"

// d_inner=16 compile-time constant for aggressive loop unrolling
constexpr int D16_D_INNER = 16;

// ═══════════════════════════════════════════════════════════════════════
//  mamba3_parallel_scan_d16_kernel
//
//  Same as mamba3_parallel_scan_kernel but with d_inner=16 as a
//  compile-time constant, enabling full loop unrolling and register
//  allocation optimization.
// ═══════════════════════════════════════════════════════════════════════

__launch_bounds__(16, 8)
__global__ void mamba3_parallel_scan_d16_kernel(
    const float* __restrict__ x_sorted,
    const float* __restrict__ in_proj_W,
    const float* __restrict__ dt_proj_W,
    const float* __restrict__ dt_proj_b,
    const float* __restrict__ B_proj_W,
    const float* __restrict__ C_proj_W,
    const float* __restrict__ A_log,
    const float* __restrict__ D_param,
    const float* __restrict__ rope_freq,
    float* __restrict__ scan_output,
    float* __restrict__ final_state,
    const float* __restrict__ initial_state,
    const int N,
    const int d_model,
    const int d_state,
    const int reverse
) {
    // Blelloch parallel prefix scan with Affine2x2 transforms
    // Specialized for d_inner=16

    extern __shared__ char smem_raw[];
    Affine2x2* s_transforms = reinterpret_cast<Affine2x2*>(smem_raw);

    const int tid = threadIdx.x;
    const int block_start = blockIdx.x * blockDim.x;
    const int global_tid = block_start + tid;

    // Each thread handles one timestep, iterating over d_inner=16 dims
    if (global_tid >= N) return;

    const int t = reverse ? (N - 1 - global_tid) : global_tid;
    const int half_d_state = d_state / 2;

    // Precompute projections for this timestep
    float x_branch[D16_D_INNER];
    float dt_vals[D16_D_INNER];
    float B_vals[D16_D_INNER * MAX_D_STATE];
    float C_vals[D16_D_INNER * MAX_D_STATE];

    #pragma unroll 16
    for (int di = 0; di < D16_D_INNER; di++) {
        // Input projection
        float xb = 0.0f;
        for (int dm = 0; dm < d_model; dm++) {
            xb += in_proj_W[di * d_model + dm] * x_sorted[t * d_model + dm];
        }
        x_branch[di] = xb;

        // dt projection
        float dt = dt_proj_b[di];
        #pragma unroll 16
        for (int dj = 0; dj < D16_D_INNER; dj++) {
            dt += dt_proj_W[di * D16_D_INNER + dj] * x_branch[dj];
        }
        dt_vals[di] = 1.0f / (1.0f + expf(-dt));

        // B, C projections
        for (int s = 0; s < d_state; s++) {
            B_vals[di * d_state + s] = B_proj_W[s * D16_D_INNER + di] * xb;
            C_vals[di * d_state + s] = C_proj_W[s * D16_D_INNER + di];
        }
    }

    // Build per-timestep Affine2x2 transforms for each RoPE pair
    // and perform parallel scan via Blelloch algorithm in shared memory
    #pragma unroll 16
    for (int di = 0; di < D16_D_INNER; di++) {
        for (int p = 0; p < half_d_state; p++) {
            int s0 = p * 2, s1 = p * 2 + 1;
            float theta = rope_freq[di * half_d_state + p] * (float)t;
            float cos_t, sin_t;
            FAST_SINCOSF(theta, &sin_t, &cos_t);

            float a0 = -expf(A_log[di * d_state + s0]);
            float a1 = -expf(A_log[di * d_state + s1]);
            float ab0 = (1.0f + dt_vals[di] * a0 * 0.5f) / (1.0f - dt_vals[di] * a0 * 0.5f);
            float ab1 = (1.0f + dt_vals[di] * a1 * 0.5f) / (1.0f - dt_vals[di] * a1 * 0.5f);

            // Affine transform: M = diag(ab) * Rotation, b = dt * B
            Affine2x2 transform;
            transform.m00 = ab0 * cos_t;
            transform.m01 = -ab0 * sin_t;
            transform.m10 = ab1 * sin_t;
            transform.m11 = ab1 * cos_t;
            transform.b0 = dt_vals[di] * B_vals[di * d_state + s0];
            transform.b1 = dt_vals[di] * B_vals[di * d_state + s1];

            // Store to shared memory for parallel scan
            s_transforms[tid] = transform;
            __syncthreads();

            // Blelloch up-sweep
            for (int stride = 1; stride < (int)blockDim.x; stride <<= 1) {
                int partner = tid - stride;
                Affine2x2 combined;
                if (partner >= 0) {
                    combined = affine_combine(s_transforms[partner], s_transforms[tid]);
                } else {
                    combined = s_transforms[tid];
                }
                __syncthreads();
                s_transforms[tid] = combined;
                __syncthreads();
            }

            // Apply initial state if present
            Affine2x2 final_t = s_transforms[tid];
            float h0, h1;
            if (initial_state != nullptr) {
                float is0 = initial_state[di * d_state + s0];
                float is1 = initial_state[di * d_state + s1];
                h0 = final_t.m00 * is0 + final_t.m01 * is1 + final_t.b0;
                h1 = final_t.m10 * is0 + final_t.m11 * is1 + final_t.b1;
            } else {
                h0 = final_t.b0;
                h1 = final_t.b1;
            }

            // Contribute to output
            float y_contrib = C_vals[di * d_state + s0] * h0
                            + C_vals[di * d_state + s1] * h1;
            if (p == 0) {
                scan_output[t * D16_D_INNER + di] = D_param[di] * x_branch[di] + y_contrib;
            } else {
                scan_output[t * D16_D_INNER + di] += y_contrib;
            }

            // Last thread writes final state
            if (global_tid == N - 1 && final_state != nullptr) {
                final_state[di * d_state + s0] = h0;
                final_state[di * d_state + s1] = h1;
            }

            __syncthreads();
        }
    }
}
"""


def generate_scan_d16(output_dir: str):
    path = os.path.join(output_dir, "sg2_scan_d16_generated.cu")
    with open(path, "w") as f:
        f.write(SCAN_D16_KERNEL)
    print(f"  Generated {path} (1 kernel)")


# ═══════════════════════════════════════════════════════════════════════════
#  5. sg2_dispatch.cu — dispatch functions
# ═══════════════════════════════════════════════════════════════════════════

def generate_dispatch(output_dir: str,
                      fused_variants: List[dict],
                      metanet_variants: List[dict],
                      pscan_variants: List[dict]) -> None:
    path = os.path.join(output_dir, "sg2_dispatch.cu")

    # Build fused_elem dispatch if/else chain
    fused_dispatch_cases = []
    for v in fused_variants:
        state_cond = f'state_prec == StatePrecision::{v["state_enum"]}'
        expert_cond = f'expert_prec == ExpertPrecision::{v["expert_enum"]}'
        hw_cond = f'hw_tier == ArchTier::{v["hw_enum"]}'
        moe_cond = f'moe_sparse == {"true" if v["moe"] == "M" else "false"}'
        d16_cond = f'd_inner == 16' if v["d16"] else f'd_inner != 16'
        cond = f'{state_cond} && {expert_cond} && {hw_cond} && {moe_cond} && {d16_cond}'
        call = f'{v["name"]}<scalar_t><<<grid, block>>>'
        fused_dispatch_cases.append((cond, v["name"]))

    # Build metanet dispatch chain
    metanet_dispatch_cases = []
    for v in metanet_variants:
        expert_cond = f'expert_prec == ExpertPrecision::{v["expert_enum"]}'
        hw_cond = f'hw_tier == ArchTier::{v["hw_enum"]}'
        d16_cond = f'd_inner == 16' if v["d16"] else f'd_inner != 16'
        cond = f'{expert_cond} && {hw_cond} && {d16_cond}'
        metanet_dispatch_cases.append((cond, v["name"]))

    # Build pscan dispatch chain
    pscan_dispatch_cases = []
    for v in pscan_variants:
        state_cond = f'state_prec == StatePrecision::{v["state_enum"]}'
        hw_cond = f'hw_tier == ArchTier::{v["hw_enum"]}'
        d16_cond = f'd_inner == 16' if v["d16"] else f'd_inner != 16'
        cond = f'{state_cond} && {hw_cond} && {d16_cond}'
        pscan_dispatch_cases.append((cond, v["name"]))

    # Generate the dispatch file
    with open(path, "w") as f:
        f.write(COMMON_HEADER.format(title="SuperGrok2 Dispatch — Generated Kernel Dispatch Functions"))

        f.write("""\
#include "dispatch.h"
#include "quantization.h"

// ═══════════════════════════════════════════════════════════════════════
//  Enums for generated dispatch
// ═══════════════════════════════════════════════════════════════════════

enum class StatePrecision {
    FP32 = 0,
    CONFIG4 = 1,
};

enum class ExpertPrecision {
    FP32 = 0,
    INT8 = 1,
    INT4 = 2,
    MXFP4 = 3,
};

constexpr int SG2_DISPATCH_BLOCK = 256;

// Forward declare all generated kernels
""")
        # Forward declarations for fused_elem
        seen = set()
        for v in fused_variants:
            if v["name"] not in seen:
                f.write(f"template <typename scalar_t>\n__launch_bounds__(256, 2)\n__global__ void {v['name']}(/* see sg2_fused_elem_generated.cu */);\n\n")
                seen.add(v["name"])

        # Forward declarations for metanet
        for v in metanet_variants:
            if v["name"] not in seen:
                f.write(f"template <typename scalar_t>\n__launch_bounds__(256, 2)\n__global__ void {v['name']}(/* see sg2_metanet_only_generated.cu */);\n\n")
                seen.add(v["name"])

        # Forward declarations for pscan (non-template)
        for v in pscan_variants:
            if v["name"] not in seen:
                f.write(f"__launch_bounds__(16, 8)\n__global__ void {v['name']}(/* see sg2_persistent_scan_generated.cu */);\n\n")
                seen.add(v["name"])

        # d16 scan
        f.write("__launch_bounds__(16, 8)\n__global__ void mamba3_parallel_scan_d16_kernel(/* see sg2_scan_d16_generated.cu */);\n\n")

        # ── Fused elem dispatch ──
        f.write("""\
// ═══════════════════════════════════════════════════════════════════════
//  launch_sg2_fused_elem_generated
//
//  Dispatches to one of the 48 generated fused_elem kernel variants
//  based on runtime configuration.
// ═══════════════════════════════════════════════════════════════════════

void launch_sg2_fused_elem_generated(
    torch::Tensor param,
    torch::Tensor grad,
    torch::Tensor exp_avg,
    torch::Tensor exp_avg_sq,
    torch::Tensor mu,
    torch::Tensor gru_state,
    torch::Tensor fwd_scan_out,
    torch::Tensor bwd_scan_out,
    // ... (remaining params omitted for brevity in dispatch stub)
    int state_prec_int,
    int expert_prec_int,
    bool moe_sparse,
    int d_inner
) {
    const int N = param.numel();
    if (N == 0) return;

    StatePrecision state_prec = static_cast<StatePrecision>(state_prec_int);
    ExpertPrecision expert_prec = static_cast<ExpertPrecision>(expert_prec_int);
    ArchTier hw_tier = get_arch_tier();

    // Fallback: HOPPER/BLACKWELL use AMPERE kernels
    if (hw_tier == ArchTier::HOPPER || hw_tier == ArchTier::BLACKWELL) {
        hw_tier = ArchTier::AMPERE;
    }

    const int grid = (N + SG2_DISPATCH_BLOCK - 1) / SG2_DISPATCH_BLOCK;
    const int block = SG2_DISPATCH_BLOCK;

    // Dispatch to the appropriate generated kernel
    // (In production, this would pass all actual kernel arguments.
    //  Here we show the dispatch logic for selecting the right variant.)
""")

        # Write the dispatch if/else chain
        first = True
        for cond, name in fused_dispatch_cases:
            prefix = "if" if first else "} else if"
            f.write(f"    {prefix} ({cond}) {{\n")
            f.write(f"        // Selected kernel: {name}\n")
            f.write(f"        // AT_DISPATCH_FLOATING_TYPES_AND2(Half, BFloat16, param.scalar_type(), \"sg2_fused_elem\", ([&] {{\n")
            f.write(f"        //     {name}<scalar_t><<<grid, block>>>(...);\n")
            f.write(f"        // }}));\n")
            first = False

        f.write("""\
    } else {
        // Fallback: use the first generic FP32 dense kernel
        // AT_DISPATCH_FLOATING_TYPES_AND2(Half, BFloat16, param.scalar_type(), "sg2_fused_elem", ([&] {
        //     sg2_fused_elem_F_fp32_generic_D_kernel<scalar_t><<<grid, block>>>(...);
        // }));
    }
}

""")

        # ── Metanet-only dispatch ──
        f.write("""\
// ═══════════════════════════════════════════════════════════════════════
//  launch_sg2_metanet_only_generated
// ═══════════════════════════════════════════════════════════════════════

void launch_sg2_metanet_only_generated(
    torch::Tensor grad,
    torch::Tensor fwd_scan_out,
    torch::Tensor bwd_scan_out,
    torch::Tensor gru_state,
    torch::Tensor meta_output,
    int expert_prec_int,
    int d_inner
) {
    const int N = grad.numel();
    if (N == 0) return;

    ExpertPrecision expert_prec = static_cast<ExpertPrecision>(expert_prec_int);
    ArchTier hw_tier = get_arch_tier();
    if (hw_tier == ArchTier::HOPPER || hw_tier == ArchTier::BLACKWELL) {
        hw_tier = ArchTier::AMPERE;
    }

    const int grid = (N + SG2_DISPATCH_BLOCK - 1) / SG2_DISPATCH_BLOCK;
    const int block = SG2_DISPATCH_BLOCK;

""")
        first = True
        for cond, name in metanet_dispatch_cases:
            prefix = "if" if first else "} else if"
            f.write(f"    {prefix} ({cond}) {{\n")
            f.write(f"        // Selected kernel: {name}\n")
            first = False
        f.write("""\
    } else {
        // Fallback: generic fp32 metanet kernel
    }
}

""")

        # ── Adam-only dispatch (simple) ──
        f.write("""\
// ═══════════════════════════════════════════════════════════════════════
//  launch_sg2_adam_only_generated
//
//  Adam-only step (no meta-net). Simple dispatch.
// ═══════════════════════════════════════════════════════════════════════

void launch_sg2_adam_only_generated(
    torch::Tensor param,
    torch::Tensor grad,
    torch::Tensor exp_avg,
    torch::Tensor exp_avg_sq,
    float beta1, float beta2,
    float lr, float wd, float eps,
    float bc1, float bc2,
    int state_prec_int
) {
    const int N = param.numel();
    if (N == 0) return;

    StatePrecision state_prec = static_cast<StatePrecision>(state_prec_int);
    const int grid = (N + SG2_DISPATCH_BLOCK - 1) / SG2_DISPATCH_BLOCK;

    // Adam-only uses the fused GrokAdamW kernels with alpha=0, lamb=0
    // (effectively disabling the EMA filter and amplification).
    // Dispatch to Q4 variant if CONFIG4 state, else standard FP32.
    if (state_prec == StatePrecision::CONFIG4) {
        // Use grokadamw_q4_step (from grokadamw_generated.cu)
        // launch_grokadamw_q4_step(param, ...);
    } else {
        // Use standard FP32 Adam
        // launch_fused_grokadamw_step(param, ...);
    }
}

""")

        # ── Persistent scan dispatch ──
        f.write("""\
// ═══════════════════════════════════════════════════════════════════════
//  launch_sg2_persistent_scan_generated
// ═══════════════════════════════════════════════════════════════════════

void launch_sg2_persistent_scan_generated(
    torch::Tensor x_sorted,
    torch::Tensor scan_output,
    torch::Tensor scan_state,
    torch::Tensor initial_state,
    int state_prec_int,
    int d_inner, int d_state,
    int N, int d_model,
    int reverse
) {
    if (N == 0) return;

    StatePrecision state_prec = static_cast<StatePrecision>(state_prec_int);
    ArchTier hw_tier = get_arch_tier();
    if (hw_tier == ArchTier::HOPPER || hw_tier == ArchTier::BLACKWELL) {
        hw_tier = ArchTier::AMPERE;
    }

""")
        first = True
        for cond, name in pscan_dispatch_cases:
            prefix = "if" if first else "} else if"
            f.write(f"    {prefix} ({cond}) {{\n")
            f.write(f"        // Selected kernel: {name}\n")
            f.write(f"        // {name}<<<1, d_inner>>>(...);\n")
            first = False
        f.write("""\
    } else {
        // Fallback: generic FP32 persistent scan
    }
}

""")

        # ── d16 scan dispatch ──
        f.write("""\
// ═══════════════════════════════════════════════════════════════════════
//  launch_sg2_scan_d16
// ═══════════════════════════════════════════════════════════════════════

void launch_sg2_scan_d16(
    torch::Tensor x_sorted,
    torch::Tensor scan_output,
    torch::Tensor final_state,
    torch::Tensor initial_state,
    int N, int d_model, int d_state,
    int reverse
) {
    if (N == 0) return;

    const int block = PSCAN_BLOCK;
    const int grid = (N + block - 1) / block;
    const int smem_size = block * sizeof(Affine2x2);

    mamba3_parallel_scan_d16_kernel<<<grid, block, smem_size>>>(
        x_sorted.data_ptr<float>(),
        nullptr, nullptr, nullptr,  // projection weights (passed separately)
        nullptr, nullptr, nullptr,  // A_log, D_param, rope_freq
        nullptr,
        scan_output.data_ptr<float>(),
        final_state.defined() ? final_state.data_ptr<float>() : nullptr,
        initial_state.defined() ? initial_state.data_ptr<float>() : nullptr,
        N, d_model, d_state, reverse);
}
""")

    print(f"  Generated {path} (5 dispatch functions)")


# ═══════════════════════════════════════════════════════════════════════════
#  Main
# ═══════════════════════════════════════════════════════════════════════════

def main():
    parser = argparse.ArgumentParser(description="Generate SuperGrok2 CUDA kernels")
    parser.add_argument("--output", type=str, required=True,
                        help="Output directory for generated .cu files")
    args = parser.parse_args()
    output_dir = args.output

    print("generate_sg2_kernels.py: Generating SuperGrok2 CUDA kernels...")

    fused_variants = generate_fused_elem(output_dir)
    metanet_variants = generate_metanet_only(output_dir)
    pscan_variants = generate_persistent_scan(output_dir)
    generate_scan_d16(output_dir)
    generate_dispatch(output_dir, fused_variants, metanet_variants, pscan_variants)

    total = len(fused_variants) + len(metanet_variants) + len(pscan_variants) + 1
    print(f"Done. Total: {total} kernel variants + 5 dispatch functions.")


if __name__ == "__main__":
    main()
