#!/usr/bin/env python3
"""
SuperGrok v2 — SG2 Fused Element Kernel Code Generator

Generates all SG2 fused_elem kernel variants across the axes:
  - State:     FP32, Q4 (Config 4 quantized optimizer state)
  - Expert:    FP32, INT8, INT4, MXFP4
  - Hardware:  Generic, Ampere (cp.async)
  - Model:     Dense, MoE (with active_mask early exit)
  - d_inner:   Generic (runtime), d_inner=16, d_inner=8

Total fused_elem = 2 * 4 * 2 * 2 * 3 = 96 kernels, of which 5 exist.

Also generates:
  - 16 meta-net-only kernels  (Expert x HW x d_inner_spec)
  - 7 persistent scan fusion variants (State x HW x d_inner_spec, minus one existing)

SG2 Adam-only kernels (8 variants) are already generated by Phase 1
(codegen/generate_kernels.py) and are skipped here.

Usage:
    python codegen/generate_sg2_kernels.py

Output goes to csrc/cuda/generated/
"""

import os
import sys
import itertools
from pathlib import Path

# ═══════════════════════════════════════════════════════════════════════
#  Configuration
# ═══════════════════════════════════════════════════════════════════════

STATES = ["fp32", "q4"]
EXPERTS = ["fp32", "int8", "int4", "mxfp4"]
HARDWARE = ["generic", "cpasync"]
MODELS = ["dense", "moe"]
# 0 = generic (runtime d_inner), 16/8 = compile-time template specializations
D_INNER_OPTS = [0, 16, 8]

# Existing kernels (already hand-written, skip generation)
EXISTING_KERNELS = {
    "fused_elem_step_kernel",           # fp32_fp32_generic
    "fused_elem_step_int8_kernel",      # fp32_int8_generic
    "fused_elem_step_int4_kernel",      # fp32_int4_generic
    "fused_elem_step_mxfp4_kernel",     # fp32_mxfp4_generic
    "fused_elem_step_cpasync_kernel",   # fp32_fp32_cpasync
}

OUTPUT_DIR = Path(__file__).resolve().parent.parent / "csrc" / "cuda" / "generated"

# ═══════════════════════════════════════════════════════════════════════
#  Naming helpers
# ═══════════════════════════════════════════════════════════════════════

def _d_inner_suffix(d_inner_spec):
    """Return naming suffix for d_inner specialization (0=none, 16='d16', 8='d8')."""
    if d_inner_spec == 16:
        return "d16"
    elif d_inner_spec == 8:
        return "d8"
    return None


def fused_elem_kernel_name(state, expert, hw, model, d_inner_spec):
    """
    Build kernel name:
      sg2_fused_elem_{state}_{expert}_{hw}[_moe][_d16|_d8]_kernel
    """
    parts = ["sg2_fused_elem", state, expert, hw]
    if model == "moe":
        parts.append("moe")
    ds = _d_inner_suffix(d_inner_spec)
    if ds:
        parts.append(ds)
    parts.append("kernel")
    return "_".join(parts)


def meta_only_kernel_name(expert, hw, d_inner_spec):
    parts = ["sg2_meta_only", expert, hw]
    ds = _d_inner_suffix(d_inner_spec)
    if ds:
        parts.append(ds)
    parts.append("kernel")
    return "_".join(parts)


def persistent_scan_kernel_name(state, hw, d_inner_spec):
    parts = ["persistent_scan_fused_elem", state, hw]
    ds = _d_inner_suffix(d_inner_spec)
    if ds:
        parts.append(ds)
    parts.append("kernel")
    return "_".join(parts)


def launcher_name(kernel_name):
    return "launch_" + kernel_name.replace("_kernel", "")


# ═══════════════════════════════════════════════════════════════════════
#  Header / includes / helper code
# ═══════════════════════════════════════════════════════════════════════

FILE_HEADER = """\
/* GENERATED by codegen/generate_sg2_kernels.py — DO NOT EDIT */
/* SG2 fused_elem kernel variants */

#include <torch/extension.h>
#include <ATen/cuda/CUDAContext.h>
#include "platform.h"
#include "types.h"
#include "utils.cuh"

#if GROK_CUDA
#include <cuda_bf16.h>
#include <cuda_pipeline.h>
#endif

// ═══════════════════════════════════════════════════════════════════════
//  INT4 unpack helper
// ═══════════════════════════════════════════════════════════════════════
__device__ __forceinline__ void unpack_int4_gen(
    uint8_t packed, float scale, float& lo_out, float& hi_out
) {
    int lo = (packed & 0x0F) - 8;
    int hi = ((packed >> 4) & 0x0F) - 8;
    lo_out = static_cast<float>(lo) * scale;
    hi_out = static_cast<float>(hi) * scale;
}

// ═══════════════════════════════════════════════════════════════════════
//  MXFP4 dequant helper
// ═══════════════════════════════════════════════════════════════════════
__device__ __forceinline__ float dequant_mxfp4_gen(
    uint8_t nibble, uint8_t shared_exp, float scale
) {
    return ldexpf(static_cast<float>(nibble), static_cast<int>(shared_exp) - 127) * scale;
}

// ═══════════════════════════════════════════════════════════════════════
//  Philox RNG for Q4 stochastic rounding
// ═══════════════════════════════════════════════════════════════════════
__device__ __forceinline__ unsigned sg2_philox_hash(unsigned key, unsigned salt) {
    unsigned v = key * 2654435761u + salt * 2246822519u;
    v ^= v >> 16; v *= 0x45d9f3bu; v ^= v >> 16;
    return v;
}

"""

# ═══════════════════════════════════════════════════════════════════════
#  Expert weight parameter generation
# ═══════════════════════════════════════════════════════════════════════

def expert_params_decl(expert):
    """Return the expert weight parameter declarations for the kernel signature."""
    if expert == "fp32":
        return [
            "const float* __restrict__ expert_W1",
            "const float* __restrict__ expert_b1",
            "const float* __restrict__ expert_W2",
            "const float* __restrict__ expert_b2",
        ]
    elif expert == "int8":
        return [
            "const int8_t* __restrict__ expert_W1_q",
            "const int8_t* __restrict__ expert_b1_q",
            "const int8_t* __restrict__ expert_W2_q",
            "const int8_t* __restrict__ expert_b2_q",
            "const float expert_W1_scale",
            "const float expert_b1_scale",
            "const float expert_W2_scale",
            "const float expert_b2_scale",
        ]
    elif expert == "int4":
        return [
            "const uint8_t* __restrict__ expert_W1_q",
            "const uint8_t* __restrict__ expert_b1_q",
            "const uint8_t* __restrict__ expert_W2_q",
            "const uint8_t* __restrict__ expert_b2_q",
            "const float expert_W1_scale",
            "const float expert_b1_scale",
            "const float expert_W2_scale",
            "const float expert_b2_scale",
        ]
    elif expert == "mxfp4":
        return [
            "const uint8_t* __restrict__ expert_W1_q",
            "const uint8_t* __restrict__ expert_W1_exp",
            "const uint8_t* __restrict__ expert_W2_q",
            "const uint8_t* __restrict__ expert_W2_exp",
            "const uint8_t* __restrict__ expert_b1_q",
            "const uint8_t* __restrict__ expert_b1_exp",
            "const uint8_t* __restrict__ expert_b2_q",
            "const uint8_t* __restrict__ expert_b2_exp",
            "const float mxfp4_scale",
        ]
    else:
        raise ValueError(f"Unknown expert type: {expert}")


def state_params_decl(state):
    """Return optimizer state parameter declarations."""
    if state == "fp32":
        return [
            "float* __restrict__ exp_avg",
            "float* __restrict__ exp_avg_sq",
            "float* __restrict__ mu",
            "float* __restrict__ gru_state",
        ]
    elif state == "q4":
        return [
            "int8_t* __restrict__ exp_avg_q",
            "float* __restrict__ exp_avg_scales",
            "int8_t* __restrict__ exp_avg_sq_q",
            "float* __restrict__ exp_avg_sq_scales",
            "__nv_bfloat16* __restrict__ mu",
            "__nv_bfloat16* __restrict__ gru_state",
        ]
    else:
        raise ValueError(f"Unknown state type: {state}")


# ═══════════════════════════════════════════════════════════════════════
#  Shared memory loading code generation
# ═══════════════════════════════════════════════════════════════════════

def gen_smem_layout(indent="    "):
    """Generate shared memory layout (same for all variants — always FP32 in smem)."""
    return f"""{indent}const int gru_input_dim = 2 + 2 * d_model;
{indent}const int gru_row_len = gru_input_dim + gru_hidden;
{indent}const int op_size = d_model * d_inner;
{indent}const int gru_mat_size = gru_hidden * gru_row_len;

{indent}extern __shared__ float smem[];

{indent}// Shared memory layout: out_proj -> GRU weights -> expert weights (all FP32)
{indent}float* s_out_fwd = smem;
{indent}float* s_out_bwd = smem + op_size;
{indent}float* s_gru_Wz = s_out_bwd + op_size;
{indent}float* s_gru_Wr = s_gru_Wz + gru_mat_size;
{indent}float* s_gru_Wh = s_gru_Wr + gru_mat_size;
{indent}float* s_gru_bz = s_gru_Wh + gru_mat_size;
{indent}float* s_gru_br = s_gru_bz + gru_hidden;
{indent}float* s_gru_bh = s_gru_br + gru_hidden;
{indent}float* s_expert_W1 = s_gru_bh + gru_hidden;
{indent}float* s_expert_b1 = s_expert_W1 + num_experts * expert_hidden;
{indent}float* s_expert_W2 = s_expert_b1 + num_experts * expert_hidden;
{indent}float* s_expert_b2 = s_expert_W2 + num_experts * expert_hidden;

{indent}const int tid = threadIdx.x;
{indent}const int block_size = blockDim.x;"""


def gen_outproj_gru_load(hw, indent="    "):
    """Generate out_proj + GRU weight loading (generic or cp.async)."""
    if hw == "cpasync":
        return f"""{indent}// Phase 1: cp.async prefetch out_proj + GRU weights
{indent}for (int i = tid; i < 2 * op_size; i += block_size) {{
{indent}    const float* src = (i < op_size) ? &out_proj_fwd_W[i] : &out_proj_bwd_W[i - op_size];
{indent}#if GROK_CUDA && defined(__CUDA_ARCH__) && __CUDA_ARCH__ >= 800
{indent}    __pipeline_memcpy_async(&smem[i], src, sizeof(float));
{indent}#else
{indent}    smem[i] = *src;
{indent}#endif
{indent}}}

{indent}const float* gru_gmem[] = {{gru_Wz, gru_Wr, gru_Wh, gru_bz, gru_br, gru_bh}};
{indent}int gru_sizes[] = {{gru_mat_size, gru_mat_size, gru_mat_size, gru_hidden, gru_hidden, gru_hidden}};
{indent}float* gru_dst = s_gru_Wz;
{indent}int gru_offset = 0;
{indent}for (int seg = 0; seg < 6; seg++) {{
{indent}    for (int i = tid; i < gru_sizes[seg]; i += block_size) {{
{indent}#if GROK_CUDA && defined(__CUDA_ARCH__) && __CUDA_ARCH__ >= 800
{indent}        __pipeline_memcpy_async(&gru_dst[gru_offset + i], &gru_gmem[seg][i], sizeof(float));
{indent}#else
{indent}        gru_dst[gru_offset + i] = gru_gmem[seg][i];
{indent}#endif
{indent}    }}
{indent}    gru_offset += gru_sizes[seg];
{indent}}}
{indent}#if GROK_CUDA && defined(__CUDA_ARCH__) && __CUDA_ARCH__ >= 800
{indent}__pipeline_commit();
{indent}#endif"""
    else:
        return f"""{indent}// Load out_proj weights
{indent}for (int i = tid; i < 2 * op_size; i += block_size) {{
{indent}    if (i < op_size) smem[i] = out_proj_fwd_W[i];
{indent}    else smem[i] = out_proj_bwd_W[i - op_size];
{indent}}}
{indent}// Load GRU weights
{indent}const float* gru_gmem[] = {{gru_Wz, gru_Wr, gru_Wh, gru_bz, gru_br, gru_bh}};
{indent}int gru_sizes[] = {{gru_mat_size, gru_mat_size, gru_mat_size, gru_hidden, gru_hidden, gru_hidden}};
{indent}float* gru_dst = s_gru_Wz;
{indent}int gru_offset = 0;
{indent}for (int seg = 0; seg < 6; seg++) {{
{indent}    for (int i = tid; i < gru_sizes[seg]; i += block_size)
{indent}        gru_dst[gru_offset + i] = gru_gmem[seg][i];
{indent}    gru_offset += gru_sizes[seg];
{indent}}}"""


def gen_expert_load(expert, hw, indent="    "):
    """Generate expert weight loading into shared memory."""
    cpasync = (hw == "cpasync")

    if expert == "fp32":
        if cpasync:
            return f"""{indent}// Phase 2: cp.async prefetch expert weights
{indent}for (int i = tid; i < num_experts * expert_hidden; i += block_size) {{
{indent}#if GROK_CUDA && defined(__CUDA_ARCH__) && __CUDA_ARCH__ >= 800
{indent}    __pipeline_memcpy_async(&s_expert_W1[i], &expert_W1[i], sizeof(float));
{indent}    __pipeline_memcpy_async(&s_expert_b1[i], &expert_b1[i], sizeof(float));
{indent}    __pipeline_memcpy_async(&s_expert_W2[i], &expert_W2[i], sizeof(float));
{indent}#else
{indent}    s_expert_W1[i] = expert_W1[i];
{indent}    s_expert_b1[i] = expert_b1[i];
{indent}    s_expert_W2[i] = expert_W2[i];
{indent}#endif
{indent}}}
{indent}for (int i = tid; i < num_experts; i += block_size) {{
{indent}#if GROK_CUDA && defined(__CUDA_ARCH__) && __CUDA_ARCH__ >= 800
{indent}    __pipeline_memcpy_async(&s_expert_b2[i], &expert_b2[i], sizeof(float));
{indent}#else
{indent}    s_expert_b2[i] = expert_b2[i];
{indent}#endif
{indent}}}
{indent}#if GROK_CUDA && defined(__CUDA_ARCH__) && __CUDA_ARCH__ >= 800
{indent}__pipeline_commit();
{indent}__pipeline_wait_prior(1);
{indent}#endif
{indent}__syncthreads();"""
        else:
            return f"""{indent}// Load FP32 expert weights
{indent}for (int i = tid; i < num_experts * expert_hidden; i += block_size) {{
{indent}    s_expert_W1[i] = expert_W1[i];
{indent}    s_expert_b1[i] = expert_b1[i];
{indent}    s_expert_W2[i] = expert_W2[i];
{indent}}}
{indent}for (int i = tid; i < num_experts; i += block_size) {{
{indent}    s_expert_b2[i] = expert_b2[i];
{indent}}}
{indent}__syncthreads();"""

    elif expert == "int8":
        sync_code = _cpasync_sync_code(cpasync, indent)
        return f"""{indent}// INT8 dequantize expert weights on load into shared memory
{indent}for (int i = tid; i < num_experts * expert_hidden; i += block_size) {{
{indent}    s_expert_W1[i] = static_cast<float>(expert_W1_q[i]) * expert_W1_scale;
{indent}    s_expert_b1[i] = static_cast<float>(expert_b1_q[i]) * expert_b1_scale;
{indent}    s_expert_W2[i] = static_cast<float>(expert_W2_q[i]) * expert_W2_scale;
{indent}}}
{indent}for (int i = tid; i < num_experts; i += block_size) {{
{indent}    s_expert_b2[i] = static_cast<float>(expert_b2_q[i]) * expert_b2_scale;
{indent}}}
{sync_code}"""

    elif expert == "int4":
        sync_code = _cpasync_sync_code(cpasync, indent)
        return f"""{indent}// INT4 dequantize: unpack 2 values per byte into shared memory
{indent}const int exp_total = num_experts * expert_hidden;
{indent}for (int i = tid; i < (exp_total + 1) / 2; i += block_size) {{
{indent}    float lo, hi;
{indent}    unpack_int4_gen(expert_W1_q[i], expert_W1_scale, lo, hi);
{indent}    s_expert_W1[2*i] = lo;
{indent}    if (2*i + 1 < exp_total) s_expert_W1[2*i + 1] = hi;
{indent}    unpack_int4_gen(expert_b1_q[i], expert_b1_scale, lo, hi);
{indent}    s_expert_b1[2*i] = lo;
{indent}    if (2*i + 1 < exp_total) s_expert_b1[2*i + 1] = hi;
{indent}    unpack_int4_gen(expert_W2_q[i], expert_W2_scale, lo, hi);
{indent}    s_expert_W2[2*i] = lo;
{indent}    if (2*i + 1 < exp_total) s_expert_W2[2*i + 1] = hi;
{indent}}}
{indent}for (int i = tid; i < (num_experts + 1) / 2; i += block_size) {{
{indent}    float lo, hi;
{indent}    unpack_int4_gen(expert_b2_q[i], expert_b2_scale, lo, hi);
{indent}    s_expert_b2[2*i] = lo;
{indent}    if (2*i + 1 < num_experts) s_expert_b2[2*i + 1] = hi;
{indent}}}
{sync_code}"""

    elif expert == "mxfp4":
        sync_code = _cpasync_sync_code(cpasync, indent)
        return f"""{indent}// MXFP4 dequantize into shared memory
{indent}const int exp_total = num_experts * expert_hidden;
{indent}for (int i = tid; i < (exp_total + 1) / 2; i += block_size) {{
{indent}    uint8_t packed_w1 = expert_W1_q[i];
{indent}    uint8_t packed_b1 = expert_b1_q[i];
{indent}    uint8_t packed_w2 = expert_W2_q[i];
{indent}    uint8_t exp_w1 = expert_W1_exp[2*i / 32];
{indent}    uint8_t exp_b1 = expert_b1_exp[2*i / 32];
{indent}    uint8_t exp_w2 = expert_W2_exp[2*i / 32];
{indent}    s_expert_W1[2*i] = dequant_mxfp4_gen(packed_w1 & 0x0F, exp_w1, mxfp4_scale);
{indent}    if (2*i+1 < exp_total) s_expert_W1[2*i+1] = dequant_mxfp4_gen((packed_w1>>4)&0x0F, exp_w1, mxfp4_scale);
{indent}    s_expert_b1[2*i] = dequant_mxfp4_gen(packed_b1 & 0x0F, exp_b1, mxfp4_scale);
{indent}    if (2*i+1 < exp_total) s_expert_b1[2*i+1] = dequant_mxfp4_gen((packed_b1>>4)&0x0F, exp_b1, mxfp4_scale);
{indent}    s_expert_W2[2*i] = dequant_mxfp4_gen(packed_w2 & 0x0F, exp_w2, mxfp4_scale);
{indent}    if (2*i+1 < exp_total) s_expert_W2[2*i+1] = dequant_mxfp4_gen((packed_w2>>4)&0x0F, exp_w2, mxfp4_scale);
{indent}}}
{indent}for (int i = tid; i < (num_experts + 1) / 2; i += block_size) {{
{indent}    uint8_t packed = expert_b2_q[i];
{indent}    uint8_t exp_val = expert_b2_exp[2*i / 32];
{indent}    s_expert_b2[2*i] = dequant_mxfp4_gen(packed & 0x0F, exp_val, mxfp4_scale);
{indent}    if (2*i+1 < num_experts) s_expert_b2[2*i+1] = dequant_mxfp4_gen((packed>>4)&0x0F, exp_val, mxfp4_scale);
{indent}}}
{sync_code}"""


def _cpasync_sync_code(cpasync, indent):
    if cpasync:
        return f"""{indent}#if GROK_CUDA && defined(__CUDA_ARCH__) && __CUDA_ARCH__ >= 800
{indent}__pipeline_commit();
{indent}__pipeline_wait_prior(0);
{indent}#endif
{indent}__syncthreads();"""
    else:
        return f"{indent}__syncthreads();"


# ═══════════════════════════════════════════════════════════════════════
#  Compute body stub
# ═══════════════════════════════════════════════════════════════════════

def gen_compute_body(state, model, d_inner_spec, has_adam=True,
                     is_meta_only=False, indent="    "):
    """Generate the full per-element compute body (6-step pipeline)."""
    I = indent
    lines = []

    # MoE early exit
    if model == "moe":
        lines.append(f"{I}// MoE early-exit: skip inactive expert parameters")
        lines.append(f"{I}if (!active_mask[idx]) return;")
        lines.append("")

    lines.append(f"{I}float g = static_cast<float>(grad[idx]);")
    lines.append(f"{I}float s = static_cast<float>(sharpness[idx]);")
    lines.append(f"{I}if (!isfinite(g)) g = 0.0f;")
    lines.append(f"{I}if (!isfinite(s)) s = 0.0f;")
    lines.append(f"{I}const int half_d = d_model / 2;")
    lines.append(f"{I}const int peer_input_dim = gru_hidden + 2 * d_model + 2;")
    lines.append("")

    # d_inner may be compile-time or runtime
    din = str(d_inner_spec) if d_inner_spec > 0 else "d_inner"
    unroll = "#pragma unroll" if d_inner_spec > 0 else ""

    # ═══ Step 1: Out_proj — project scan outputs ═══
    lines.append(f"{I}// Step 1: out_proj — project scan outputs to fwd_ctx/bwd_ctx")
    lines.append(f"{I}float fwd_ctx[MAX_D_MODEL], bwd_ctx[MAX_D_MODEL];")
    lines.append(f"{I}for (int dm = 0; dm < d_model; dm++) {{")
    lines.append(f"{I}    float fwd_acc = 0.0f, bwd_acc = 0.0f;")
    if unroll:
        lines.append(f"{I}    {unroll}")
    lines.append(f"{I}    for (int di = 0; di < {din}; di++) {{")
    lines.append(f"{I}        float fwd_so = fwd_scan_out[idx * {din} + di];")
    lines.append(f"{I}        float bwd_so = bwd_scan_out[idx * {din} + di];")
    lines.append(f"{I}        fwd_acc += s_out_fwd[dm * {din} + di] * fwd_so;")
    lines.append(f"{I}        bwd_acc += s_out_bwd[dm * {din} + di] * bwd_so;")
    lines.append(f"{I}    }}")
    lines.append(f"{I}    fwd_ctx[dm] = fwd_acc;")
    lines.append(f"{I}    bwd_ctx[dm] = bwd_acc;")
    lines.append(f"{I}}}")
    lines.append("")

    # ═══ Step 2: GRU update ═══
    lines.append(f"{I}// Step 2: GRU state update")
    # Load old GRU state with non-temporal access for FP32, or dequantize for Q4
    if state == "fp32":
        lines.append(f"{I}float h_old[MAX_GRU_HIDDEN];")
        lines.append(f"{I}for (int gh = 0; gh < gru_hidden; gh++)")
        lines.append(f"{I}    h_old[gh] = stream_load(&gru_state[idx * gru_hidden + gh]);")
    else:  # q4: BF16+SR
        lines.append(f"{I}float h_old[MAX_GRU_HIDDEN];")
        lines.append(f"{I}for (int gh = 0; gh < gru_hidden; gh++)")
        lines.append(f"{I}    h_old[gh] = __bfloat162float(gru_state[idx * gru_hidden + gh]);")
    lines.append("")

    lines.append(f"{I}// Build GRU input vector: [g, s, fwd_ctx, bwd_ctx, h_old]")
    lines.append(f"{I}float gru_in[2 + 2 * MAX_D_MODEL + MAX_GRU_HIDDEN];")
    lines.append(f"{I}gru_in[0] = g; gru_in[1] = s;")
    lines.append(f"{I}for (int dm = 0; dm < d_model; dm++) gru_in[2 + dm] = fwd_ctx[dm];")
    lines.append(f"{I}for (int dm = 0; dm < d_model; dm++) gru_in[2 + d_model + dm] = bwd_ctx[dm];")
    lines.append(f"{I}for (int gh = 0; gh < gru_hidden; gh++) gru_in[2 + 2 * d_model + gh] = h_old[gh];")
    lines.append(f"{I}const int gru_in_len = 2 + 2 * d_model + gru_hidden;")
    lines.append("")

    # GRU gates
    lines.append(f"{I}float h_new[MAX_GRU_HIDDEN];")
    lines.append(f"{I}for (int gh = 0; gh < gru_hidden; gh++) {{")
    lines.append(f"{I}    float z_raw = s_gru_bz[gh], r_raw = s_gru_br[gh];")
    lines.append(f"{I}    for (int k = 0; k < gru_in_len; k++) {{")
    lines.append(f"{I}        z_raw += s_gru_Wz[gh * gru_row_len + k] * gru_in[k];")
    lines.append(f"{I}        r_raw += s_gru_Wr[gh * gru_row_len + k] * gru_in[k];")
    lines.append(f"{I}    }}")
    lines.append(f"{I}    float z_gate = ptx_sigmoidf(z_raw);")
    lines.append(f"{I}    float r_gate = ptx_sigmoidf(r_raw);")
    lines.append(f"{I}    // Candidate with reset applied to h_old portion")
    lines.append(f"{I}    float h_raw = s_gru_bh[gh];")
    lines.append(f"{I}    for (int k = 0; k < gru_in_len; k++) {{")
    lines.append(f"{I}        float inp_k = gru_in[k];")
    lines.append(f"{I}        if (k >= 2 + 2 * d_model) inp_k = r_gate * inp_k;  // reset h_old")
    lines.append(f"{I}        h_raw += s_gru_Wh[gh * gru_row_len + k] * inp_k;")
    lines.append(f"{I}    }}")
    lines.append(f"{I}    float h_tilde = ptx_tanhf(h_raw);")
    lines.append(f"{I}    h_new[gh] = (1.0f - z_gate) * h_old[gh] + z_gate * h_tilde;")
    lines.append(f"{I}}}")
    lines.append("")

    # Store new GRU state
    if state == "fp32":
        lines.append(f"{I}for (int gh = 0; gh < gru_hidden; gh++)")
        lines.append(f"{I}    stream_store(&gru_state[idx * gru_hidden + gh], h_new[gh]);")
    else:  # q4: BF16+SR
        lines.append(f"{I}for (int gh = 0; gh < gru_hidden; gh++) {{")
        lines.append(f"{I}    unsigned _rng = hash_prng(global_step * 7u + (unsigned)gh, (unsigned)idx);")
        lines.append(f"{I}    gru_state[idx * gru_hidden + gh] = float_to_bf16_stochastic(h_new[gh], _rng);")
        lines.append(f"{I}}}")
    lines.append("")

    # ═══ Step 3: Multi-head PEER routing + Expert MLP ═══
    lines.append(f"{I}// Step 3: Multi-head PEER routing + Expert MLP")
    lines.append(f"{I}// Build query input: [h_new, fwd_ctx, bwd_ctx, g, s]")
    lines.append(f"{I}float q_in[MAX_GRU_HIDDEN + 2 * MAX_D_MODEL + 2];")
    lines.append(f"{I}for (int gh = 0; gh < gru_hidden; gh++) q_in[gh] = h_new[gh];")
    lines.append(f"{I}for (int dm = 0; dm < d_model; dm++) q_in[gru_hidden + dm] = fwd_ctx[dm];")
    lines.append(f"{I}for (int dm = 0; dm < d_model; dm++) q_in[gru_hidden + d_model + dm] = bwd_ctx[dm];")
    lines.append(f"{I}q_in[gru_hidden + 2 * d_model] = g;")
    lines.append(f"{I}q_in[gru_hidden + 2 * d_model + 1] = s;")
    lines.append("")

    lines.append(f"{I}float total_out = 0.0f;")
    lines.append(f"{I}for (int head = 0; head < num_heads; head++) {{")
    lines.append(f"{I}    // Query projection")
    lines.append(f"{I}    float query[MAX_D_MODEL];")
    lines.append(f"{I}    for (int dm = 0; dm < d_model; dm++) {{")
    lines.append(f"{I}        float acc = 0.0f;")
    lines.append(f"{I}        for (int k = 0; k < peer_input_dim; k++)")
    lines.append(f"{I}            acc += peer_query_Ws[head * d_model * peer_input_dim + dm * peer_input_dim + k] * q_in[k];")
    lines.append(f"{I}        query[dm] = acc;")
    lines.append(f"{I}    }}")
    lines.append("")

    lines.append(f"{I}    // Product-key routing: argmax over each half")
    lines.append(f"{I}    float best_A = -1e30f, best_B = -1e30f;")
    lines.append(f"{I}    int idx_A = 0, idx_B = 0;")
    lines.append(f"{I}    for (int pk = 0; pk < pk_dim; pk++) {{")
    lines.append(f"{I}        float score_A = 0.0f, score_B = 0.0f;")
    lines.append(f"{I}        for (int dm = 0; dm < half_d; dm++) {{")
    lines.append(f"{I}            score_A += prod_keys_A[head * pk_dim * half_d + pk * half_d + dm] * query[dm];")
    lines.append(f"{I}            score_B += prod_keys_B[head * pk_dim * half_d + pk * half_d + dm] * query[half_d + dm];")
    lines.append(f"{I}        }}")
    lines.append(f"{I}        if (score_A > best_A) {{ best_A = score_A; idx_A = pk; }}")
    lines.append(f"{I}        if (score_B > best_B) {{ best_B = score_B; idx_B = pk; }}")
    lines.append(f"{I}    }}")
    lines.append(f"{I}    int expert_id = idx_A * pk_dim + idx_B;")
    lines.append(f"{I}    if (expert_id >= num_experts) expert_id = num_experts - 1;")
    lines.append(f"{I}    atomicAdd(&expert_counts[expert_id], 1);")
    lines.append("")

    lines.append(f"{I}    // Expert MLP: ReLU(W1 * g + b1) → W2 @ hidden + b2")
    lines.append(f"{I}    float head_out = s_expert_b2[expert_id];")
    lines.append(f"{I}    for (int eh = 0; eh < expert_hidden; eh++) {{")
    lines.append(f"{I}        float hidden = s_expert_W1[expert_id * expert_hidden + eh] * g + s_expert_b1[expert_id * expert_hidden + eh];")
    lines.append(f"{I}        hidden = fmaxf(hidden, 0.0f);  // ReLU")
    lines.append(f"{I}        head_out += s_expert_W2[expert_id * expert_hidden + eh] * hidden;")
    lines.append(f"{I}    }}")
    lines.append(f"{I}    total_out += head_out;")
    lines.append(f"{I}}}")
    lines.append("")

    # ═══ Step 4: Smart gradient ═══
    lines.append(f"{I}// Step 4: smart gradient")
    lines.append(f"{I}float smart_grad = g + rescale * (total_out / (float)num_heads);")
    lines.append("")

    if is_meta_only:
        lines.append(f"{I}// Meta-only: write smart_grad to output buffer, no Adam")
        lines.append(f"{I}smart_grad_out[idx] = smart_grad;")
        return "\n".join(lines)

    # ═══ Step 5: Mu EMA update ═══
    lines.append(f"{I}// Step 5: mu EMA update")
    if state == "fp32":
        lines.append(f"{I}float mu_old = stream_load(&mu[idx]);")
        lines.append(f"{I}float mu_new = alpha * mu_old + (1.0f - alpha) * g;")
        lines.append(f"{I}stream_store(&mu[idx], mu_new);")
    else:  # q4: BF16+SR for mu
        lines.append(f"{I}// Q4 BF16 mu load/store with stochastic rounding")
        lines.append(f"{I}float mu_old = __bfloat162float(mu[idx]);")
        lines.append(f"{I}float mu_new = alpha * mu_old + (1.0f - alpha) * g;")
        lines.append(f"{I}unsigned _mu_rng = hash_prng(global_step * 5u, (unsigned)idx);")
        lines.append(f"{I}mu[idx] = float_to_bf16_stochastic(mu_new, _mu_rng);")
    lines.append("")

    # ═══ Step 6: Adam optimizer step ═══
    lines.append(f"{I}// Step 6: Adam optimizer step")
    lines.append(f"{I}float effective_grad = smart_grad + lamb_eff * mu_new;")
    if state == "fp32":
        lines.append(f"{I}float ea_old = stream_load(&exp_avg[idx]);")
        lines.append(f"{I}float easq_old = stream_load(&exp_avg_sq[idx]);")
        lines.append(f"{I}float ea = beta1 * ea_old + (1.0f - beta1) * effective_grad;")
        lines.append(f"{I}float easq = beta2 * easq_old + (1.0f - beta2) * effective_grad * effective_grad;")
        lines.append(f"{I}stream_store(&exp_avg[idx], ea);")
        lines.append(f"{I}stream_store(&exp_avg_sq[idx], easq);")
    else:  # q4: INT8-block8
        lines.append(f"{I}// Q4 INT8 exp_avg load")
        lines.append(f"{I}int _ea_blk = idx / 8;")
        lines.append(f"{I}float ea_old = (float)exp_avg_q[idx] * exp_avg_scales[_ea_blk];")
        lines.append(f"{I}float ea = beta1 * ea_old + (1.0f - beta1) * effective_grad;")
        lines.append(f"{I}// Q4 INT8 exp_avg_sq load")
        lines.append(f"{I}float easq_old = (float)exp_avg_sq_q[idx] * exp_avg_sq_scales[_ea_blk];")
        lines.append(f"{I}float easq = beta2 * easq_old + (1.0f - beta2) * effective_grad * effective_grad;")
        lines.append(f"{I}// Stochastic requantize")
        lines.append(f"{I}unsigned _ea_rng = sg2_philox_hash(global_step * 3u, (unsigned)idx);")
        lines.append(f"{I}float _ea_scale = fmaxf(fabsf(ea), 1e-12f) / 127.0f;")
        lines.append(f"{I}exp_avg_q[idx] = float_to_int8_stochastic(ea, _ea_scale, _ea_rng);")
        lines.append(f"{I}if (idx % 8 == 0) exp_avg_scales[_ea_blk] = _ea_scale;")
        lines.append(f"{I}unsigned _easq_rng = sg2_philox_hash(global_step * 4u, (unsigned)idx);")
        lines.append(f"{I}float _easq_scale = fmaxf(fabsf(easq), 1e-12f) / 127.0f;")
        lines.append(f"{I}exp_avg_sq_q[idx] = float_to_int8_stochastic(easq, _easq_scale, _easq_rng);")
        lines.append(f"{I}if (idx % 8 == 0) exp_avg_sq_scales[_ea_blk] = _easq_scale;")
    lines.append("")

    lines.append(f"{I}// Param update with weight decay")
    lines.append(f"{I}float step_size = lr / bc1;")
    lines.append(f"{I}float denom = sqrtf(easq / bc2) + eps;")
    lines.append(f"{I}float p = static_cast<float>(param[idx]);")
    lines.append(f"{I}p *= (1.0f - lr * wd_eff);")
    lines.append(f"{I}p -= step_size * ea / denom;")
    lines.append(f"{I}param[idx] = static_cast<scalar_t>(p);")

    return "\n".join(lines)


# ═══════════════════════════════════════════════════════════════════════
#  Full kernel generation
# ═══════════════════════════════════════════════════════════════════════

def gen_fused_elem_kernel(state, expert, hw, model, d_inner_spec):
    """Generate a single fused_elem kernel stub."""
    kname = fused_elem_kernel_name(state, expert, hw, model, d_inner_spec)
    lines = []

    # Template declaration
    if d_inner_spec > 0:
        lines.append(f"template <typename scalar_t, int D_INNER={d_inner_spec}>")
    else:
        lines.append(f"template <typename scalar_t>")

    lines.append(f"__launch_bounds__(256, 2)")
    lines.append(f"__global__ void {kname}(")

    # Parameter list
    params = []
    params.append("    scalar_t* __restrict__ param")
    params.append("    const scalar_t* __restrict__ grad")
    params.append("    const scalar_t* __restrict__ sharpness")

    # State params
    for p in state_params_decl(state):
        params.append(f"    {p}")

    # Scan outputs
    params.append("    const float* __restrict__ fwd_scan_out")
    params.append("    const float* __restrict__ bwd_scan_out")

    # Mamba out_proj
    params.append("    const float* __restrict__ out_proj_fwd_W")
    params.append("    const float* __restrict__ out_proj_bwd_W")

    # GRU weights
    params.append("    const float* __restrict__ gru_Wz, const float* __restrict__ gru_bz")
    params.append("    const float* __restrict__ gru_Wr, const float* __restrict__ gru_br")
    params.append("    const float* __restrict__ gru_Wh, const float* __restrict__ gru_bh")

    # PEER weights
    params.append("    const float* __restrict__ peer_query_Ws")
    params.append("    const float* __restrict__ prod_keys_A")
    params.append("    const float* __restrict__ prod_keys_B")

    # Expert weights
    for p in expert_params_decl(expert):
        params.append(f"    {p}")

    # Scalars
    params.append("    const float rescale, const float alpha, const float lamb_eff")
    params.append("    const float beta1, const float beta2, const float lr")
    params.append("    const float wd_eff, const float eps, const float bc1, const float bc2")

    # Q4 global step
    if state == "q4":
        params.append("    const unsigned global_step")

    # MoE active_mask
    if model == "moe":
        params.append("    const bool* __restrict__ active_mask")

    # Expert counts + dims
    params.append("    int* __restrict__ expert_counts")
    params.append("    const int N, const int d_model, const int d_inner")
    params.append("    const int gru_hidden, const int num_heads, const int pk_dim")
    params.append("    const int expert_hidden, const int num_experts")

    # Format params with commas
    param_str = ",\n".join(params)
    lines.append(param_str)
    lines.append(") {")

    # Body
    lines.append(gen_smem_layout())
    lines.append("")
    lines.append(gen_outproj_gru_load(hw))
    lines.append("")
    lines.append(gen_expert_load(expert, hw))
    lines.append("")

    lines.append("    // Per-element processing")
    lines.append("    const int idx = blockIdx.x * blockDim.x + threadIdx.x;")
    lines.append("    if (idx >= N) return;")
    lines.append("")
    lines.append(gen_compute_body(state, model, d_inner_spec))
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def gen_meta_only_kernel(expert, hw, d_inner_spec):
    """Generate a meta-net-only kernel (no Adam)."""
    kname = meta_only_kernel_name(expert, hw, d_inner_spec)
    lines = []

    if d_inner_spec > 0:
        lines.append(f"template <typename scalar_t, int D_INNER={d_inner_spec}>")
    else:
        lines.append(f"template <typename scalar_t>")

    lines.append(f"__launch_bounds__(256, 2)")
    lines.append(f"__global__ void {kname}(")

    params = []
    params.append("    const scalar_t* __restrict__ grad")
    params.append("    const scalar_t* __restrict__ sharpness")
    params.append("    float* __restrict__ gru_state")
    params.append("    float* __restrict__ smart_grad_out")    # output buffer
    params.append("    const float* __restrict__ fwd_scan_out")
    params.append("    const float* __restrict__ bwd_scan_out")
    params.append("    const float* __restrict__ out_proj_fwd_W")
    params.append("    const float* __restrict__ out_proj_bwd_W")
    params.append("    const float* __restrict__ gru_Wz, const float* __restrict__ gru_bz")
    params.append("    const float* __restrict__ gru_Wr, const float* __restrict__ gru_br")
    params.append("    const float* __restrict__ gru_Wh, const float* __restrict__ gru_bh")
    params.append("    const float* __restrict__ peer_query_Ws")
    params.append("    const float* __restrict__ prod_keys_A")
    params.append("    const float* __restrict__ prod_keys_B")

    for p in expert_params_decl(expert):
        params.append(f"    {p}")

    params.append("    const float rescale")
    params.append("    int* __restrict__ expert_counts")
    params.append("    const int N, const int d_model, const int d_inner")
    params.append("    const int gru_hidden, const int num_heads, const int pk_dim")
    params.append("    const int expert_hidden, const int num_experts")

    param_str = ",\n".join(params)
    lines.append(param_str)
    lines.append(") {")

    lines.append(gen_smem_layout())
    lines.append("")
    lines.append(gen_outproj_gru_load(hw))
    lines.append("")
    lines.append(gen_expert_load(expert, hw))
    lines.append("")

    lines.append("    // Per-element processing")
    lines.append("    const int idx = blockIdx.x * blockDim.x + threadIdx.x;")
    lines.append("    if (idx >= N) return;")
    lines.append("")
    lines.append(gen_compute_body("fp32", "dense", d_inner_spec, has_adam=False, is_meta_only=True))
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def gen_persistent_scan_kernel(state, hw, d_inner_spec):
    """Generate a persistent scan fusion kernel stub."""
    kname = persistent_scan_kernel_name(state, hw, d_inner_spec)
    lines = []

    if d_inner_spec > 0:
        lines.append(f"template <typename scalar_t, int D_INNER={d_inner_spec}>")
    else:
        lines.append(f"template <typename scalar_t>")

    lines.append(f"__launch_bounds__(256, 2)")
    lines.append(f"__global__ void {kname}(")

    params = []
    params.append("    scalar_t* __restrict__ param")
    params.append("    const scalar_t* __restrict__ grad")
    params.append("    const scalar_t* __restrict__ sharpness")

    for p in state_params_decl(state):
        params.append(f"    {p}")

    # Scan inputs (persistent scan fuses the scan computation)
    params.append("    const float* __restrict__ scan_A")        # [N, d_inner] decay
    params.append("    const float* __restrict__ scan_B")        # [N, d_inner] input
    params.append("    float* __restrict__ scan_state")          # [d_inner] running state
    params.append("    const float* __restrict__ out_proj_fwd_W")
    params.append("    const float* __restrict__ out_proj_bwd_W")
    params.append("    const float* __restrict__ gru_Wz, const float* __restrict__ gru_bz")
    params.append("    const float* __restrict__ gru_Wr, const float* __restrict__ gru_br")
    params.append("    const float* __restrict__ gru_Wh, const float* __restrict__ gru_bh")
    params.append("    const float* __restrict__ peer_query_Ws")
    params.append("    const float* __restrict__ prod_keys_A")
    params.append("    const float* __restrict__ prod_keys_B")
    params.append("    const float* __restrict__ expert_W1")
    params.append("    const float* __restrict__ expert_b1")
    params.append("    const float* __restrict__ expert_W2")
    params.append("    const float* __restrict__ expert_b2")
    params.append("    const float rescale, const float alpha, const float lamb_eff")
    params.append("    const float beta1, const float beta2, const float lr")
    params.append("    const float wd_eff, const float eps, const float bc1, const float bc2")

    if state == "q4":
        params.append("    const unsigned global_step")

    params.append("    int* __restrict__ expert_counts")
    params.append("    const int N, const int d_model, const int d_inner")
    params.append("    const int gru_hidden, const int num_heads, const int pk_dim")
    params.append("    const int expert_hidden, const int num_experts")

    param_str = ",\n".join(params)
    lines.append(param_str)
    lines.append(") {")

    lines.append(gen_smem_layout())
    lines.append("")
    lines.append(gen_outproj_gru_load(hw))
    lines.append("")
    lines.append(gen_expert_load("fp32", hw))
    lines.append("")

    # Persistent scan: each thread processes one scan dimension,
    # sequentially over N timesteps, then fuses the elem update.
    din = str(d_inner_spec) if d_inner_spec > 0 else "d_inner"
    lines.append("    // Persistent scan: sequential over N, fused with elem step")
    lines.append(f"    const int tid_dim = threadIdx.x;")
    lines.append(f"    if (tid_dim >= {din}) return;")
    lines.append("")
    lines.append(f"    // Running scan state in registers")
    lines.append(f"    float scan_h = (scan_state != nullptr) ? scan_state[tid_dim] : 0.0f;")
    lines.append("")
    lines.append(f"    for (int step = 0; step < N; step++) {{")
    lines.append(f"        // Scan recurrence: h = A * h + B")
    lines.append(f"        float a_val = scan_A[step * {din} + tid_dim];")
    lines.append(f"        float b_val = scan_B[step * {din} + tid_dim];")
    lines.append(f"        scan_h = a_val * scan_h + b_val;")
    lines.append(f"    }}")
    lines.append("")
    lines.append(f"    // Write final scan state")
    lines.append(f"    if (scan_state != nullptr) scan_state[tid_dim] = scan_h;")
    lines.append("")
    lines.append(f"    // Now apply fused_elem for each element using the scan output")
    lines.append(f"    // Grid-stride over N with fused elem pipeline")
    lines.append(f"    for (int idx = blockIdx.x * blockDim.x + threadIdx.x; idx < N; idx += gridDim.x * blockDim.x) {{")
    lines.append(gen_compute_body(state, "dense", d_inner_spec))
    lines.append(f"    }}")
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


# ═══════════════════════════════════════════════════════════════════════
#  Launcher generation
# ═══════════════════════════════════════════════════════════════════════

def gen_launcher(kname, state, expert, model, is_meta=False, is_pscan=False):
    """Generate a C++ launcher function for the given kernel."""
    lname = launcher_name(kname)
    lines = []
    lines.append(f"void {lname}(")

    # Torch tensor params
    tensor_params = []
    if not is_meta:
        tensor_params.append("    torch::Tensor param")
    tensor_params.append("    torch::Tensor grad")
    tensor_params.append("    torch::Tensor sharpness")

    if is_meta:
        tensor_params.append("    torch::Tensor gru_state")
        tensor_params.append("    torch::Tensor smart_grad_out")
    elif state == "fp32":
        tensor_params.append("    torch::Tensor exp_avg")
        tensor_params.append("    torch::Tensor exp_avg_sq")
        tensor_params.append("    torch::Tensor mu")
        tensor_params.append("    torch::Tensor gru_state")
    else:
        tensor_params.append("    torch::Tensor exp_avg_q")
        tensor_params.append("    torch::Tensor exp_avg_scales")
        tensor_params.append("    torch::Tensor exp_avg_sq_q")
        tensor_params.append("    torch::Tensor exp_avg_sq_scales")
        tensor_params.append("    torch::Tensor mu")
        tensor_params.append("    torch::Tensor gru_state")

    if is_pscan:
        tensor_params.append("    torch::Tensor scan_A")
        tensor_params.append("    torch::Tensor scan_B")
        tensor_params.append("    torch::Tensor scan_state")
    else:
        tensor_params.append("    torch::Tensor fwd_scan_out")
        tensor_params.append("    torch::Tensor bwd_scan_out")

    # Scalar params
    scalar_params = []
    if not is_meta:
        scalar_params.extend([
            "    float rescale, float alpha, float lamb_eff",
            "    float beta1, float beta2, float lr",
            "    float wd_eff, float eps, float bc1, float bc2",
        ])
    else:
        scalar_params.append("    float rescale")

    if state == "q4" and not is_meta:
        scalar_params.append("    int global_step")

    scalar_params.extend([
        "    int d_model, int d_inner",
        "    int gru_hidden, int num_heads, int pk_dim",
        "    int expert_hidden, int num_experts",
    ])

    all_params = tensor_params + scalar_params
    lines.append(",\n".join(all_params))
    lines.append(") {")
    lines.append(f"    const int N = grad.numel();")
    lines.append(f"    if (N == 0) return;")
    lines.append(f"    const int grid = (N + 256 - 1) / 256;")
    lines.append(f"    // TODO: compute shared memory size and launch {kname}")
    lines.append(f"    // Shared memory = 2*op_size + 3*gru_mat_size + 3*gru_hidden")
    lines.append(f"    //               + 3*num_experts*expert_hidden + num_experts (all float)")
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


# ═══════════════════════════════════════════════════════════════════════
#  Main generation
# ═══════════════════════════════════════════════════════════════════════

def is_existing_kernel(state, expert, hw, model, d_inner_spec):
    """Check if this variant already exists as a hand-written kernel."""
    # Existing kernels: fp32 state, dense model, generic d_inner
    if state == "fp32" and model == "dense" and d_inner_spec == 0:
        if expert == "fp32" and hw == "generic":
            return True  # fused_elem_step_kernel
        if expert == "int8" and hw == "generic":
            return True  # fused_elem_step_int8_kernel
        if expert == "int4" and hw == "generic":
            return True  # fused_elem_step_int4_kernel
        if expert == "mxfp4" and hw == "generic":
            return True  # fused_elem_step_mxfp4_kernel
        if expert == "fp32" and hw == "cpasync":
            return True  # fused_elem_step_cpasync_kernel
    return False


def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # ── Collect all kernels ──────────────────────────────────────────
    fused_elem_kernels = []
    meta_only_kernels = []
    persistent_scan_kernels = []

    # Fused elem: State(2) x Expert(4) x HW(2) x Model(2) x d_inner(3)
    # = 96 total, minus 5 existing = 91 new
    for state, expert, hw, model, d_inner_spec in itertools.product(
        STATES, EXPERTS, HARDWARE, MODELS, D_INNER_OPTS
    ):
        if is_existing_kernel(state, expert, hw, model, d_inner_spec):
            continue
        fused_elem_kernels.append((state, expert, hw, model, d_inner_spec))

    # Meta-only: Expert(4) x HW(2) x d_inner(2: generic + d16 only) = 16
    for expert, hw, d_inner_spec in itertools.product(EXPERTS, HARDWARE, [0, 16]):
        meta_only_kernels.append((expert, hw, d_inner_spec))

    # Persistent scan: State(2) x HW(2) x d_inner(2: generic + d16) = 8
    # minus 1 existing (fp32_generic_0) = 7
    for state, hw, d_inner_spec in itertools.product(STATES, HARDWARE, [0, 16]):
        persistent_scan_kernels.append((state, hw, d_inner_spec))

    # Remove existing persistent scan variant
    persistent_scan_kernels = [
        (s, h, d) for s, h, d in persistent_scan_kernels
        if not (s == "fp32" and h == "generic" and d == 0)
    ]

    total_fused = len(fused_elem_kernels)
    total_meta = len(meta_only_kernels)
    total_pscan = len(persistent_scan_kernels)

    print(f"SG2 fused_elem kernel variants to generate: {total_fused}")
    print(f"  (5 existing hand-written kernels skipped, 96 total)")
    print(f"Meta-only kernel variants: {total_meta}")
    print(f"Persistent scan fusion variants: {total_pscan}")
    print(f"SG2 Adam-only variants: 8 (already generated by Phase 1, skipped)")
    print(f"Total new kernels: {total_fused + total_meta + total_pscan}")

    # ── Generate: split across multiple files to manage compile times ──

    # File 1: fused_elem kernels (FP32 state)
    fp32_kernels = [(s, e, h, m, d) for s, e, h, m, d in fused_elem_kernels if s == "fp32"]
    _write_fused_file("sg2_fused_elem_fp32_generated.cu", fp32_kernels, "FP32 state")

    # File 2: fused_elem kernels (Q4 state)
    q4_kernels = [(s, e, h, m, d) for s, e, h, m, d in fused_elem_kernels if s == "q4"]
    _write_fused_file("sg2_fused_elem_q4_generated.cu", q4_kernels, "Q4 state")

    # File 3: meta-only kernels
    _write_meta_file("sg2_meta_only_generated.cu", meta_only_kernels)

    # File 4: persistent scan fusion kernels
    _write_pscan_file("sg2_persistent_scan_generated.cu", persistent_scan_kernels)

    print(f"\nGenerated files in {OUTPUT_DIR}/:")
    print(f"  sg2_fused_elem_fp32_generated.cu  ({len(fp32_kernels)} kernels)")
    print(f"  sg2_fused_elem_q4_generated.cu    ({len(q4_kernels)} kernels)")
    print(f"  sg2_meta_only_generated.cu        ({total_meta} kernels)")
    print(f"  sg2_persistent_scan_generated.cu  ({total_pscan} kernels)")


def _write_fused_file(filename, kernels, desc):
    """Write a fused_elem kernel file."""
    path = OUTPUT_DIR / filename
    with open(path, "w") as f:
        f.write(FILE_HEADER)
        f.write(f"// {len(kernels)} SG2 fused_elem kernel variants ({desc})\n\n")

        for state, expert, hw, model, d_inner_spec in kernels:
            kname = fused_elem_kernel_name(state, expert, hw, model, d_inner_spec)
            tag = f"{state}/{expert}/{hw}"
            if model == "moe":
                tag += "/moe"
            ds = _d_inner_suffix(d_inner_spec)
            if ds:
                tag += f"/{ds}"
            f.write(f"// ═══════════════════════════════════════════════════════════\n")
            f.write(f"//  {kname}  [{tag}]\n")
            f.write(f"// ═══════════════════════════════════════════════════════════\n\n")
            f.write(gen_fused_elem_kernel(state, expert, hw, model, d_inner_spec))
            f.write("\n")
            f.write(gen_launcher(kname, state, expert, model))
            f.write("\n")


def _write_meta_file(filename, kernels):
    """Write meta-only kernel file."""
    path = OUTPUT_DIR / filename
    with open(path, "w") as f:
        f.write(FILE_HEADER)
        f.write(f"// {len(kernels)} SG2 meta-net-only kernel variants\n")
        f.write(f"// These kernels compute GRU + PEER + Expert to produce smart_grad\n")
        f.write(f"// and write to an output buffer. No Adam step is performed.\n\n")

        for expert, hw, d_inner_spec in kernels:
            kname = meta_only_kernel_name(expert, hw, d_inner_spec)
            tag = f"{expert}/{hw}"
            ds = _d_inner_suffix(d_inner_spec)
            if ds:
                tag += f"/{ds}"
            f.write(f"// ═══════════════════════════════════════════════════════════\n")
            f.write(f"//  {kname}  [{tag}]\n")
            f.write(f"// ═══════════════════════════════════════════════════════════\n\n")
            f.write(gen_meta_only_kernel(expert, hw, d_inner_spec))
            f.write("\n")
            f.write(gen_launcher(kname, "fp32", expert, "dense", is_meta=True))
            f.write("\n")


def _write_pscan_file(filename, kernels):
    """Write persistent scan fusion kernel file."""
    path = OUTPUT_DIR / filename
    with open(path, "w") as f:
        f.write(FILE_HEADER)
        f.write(f"// {len(kernels)} persistent scan + fused_elem kernel variants\n")
        f.write(f"// These kernels fuse the parallel prefix scan with the per-element\n")
        f.write(f"// GRU + PEER + Expert + Adam step, eliminating intermediate buffers.\n\n")

        for state, hw, d_inner_spec in kernels:
            kname = persistent_scan_kernel_name(state, hw, d_inner_spec)
            tag = f"{state}/{hw}"
            ds = _d_inner_suffix(d_inner_spec)
            if ds:
                tag += f"/{ds}"
            f.write(f"// ═══════════════════════════════════════════════════════════\n")
            f.write(f"//  {kname}  [{tag}]\n")
            f.write(f"// ═══════════════════════════════════════════════════════════\n\n")
            f.write(gen_persistent_scan_kernel(state, hw, d_inner_spec))
            f.write("\n")
            f.write(gen_launcher(kname, state, "fp32", "dense", is_pscan=True))
            f.write("\n")


if __name__ == "__main__":
    main()
