#!/usr/bin/env python3
"""
Code generation for SuperGrok1.5 optimizer CUDA kernels.

Generates:
  1. grokadamw_generated.cu   - GrokAdamW Q4 variants (scalar + vec4)
  2. compute_absmax_scale_kernel.cu - GPU-side absmax scale computation
  3. muon_update_generated.cu  - Muon update with stream_load/stream_store

Usage:
    python codegen/generate_kernels.py --output csrc/cuda/generated/
"""

import argparse
import os
import textwrap


# ═══════════════════════════════════════════════════════════════════════════
#  1. GrokAdamW Q4 Generated Kernels
# ═══════════════════════════════════════════════════════════════════════════

GROKADAMW_Q4_HEADER = r"""/*
 * GrokAdamW Q4 — Generated CUDA Kernels (Config 4)
 *
 * INT8 per-block quantized exp_avg with block-size 8.
 * BF16 stochastic rounding for exp_avg_sq and ema.
 * Includes scalar and float4-vectorized variants.
 *
 * AUTO-GENERATED by codegen/generate_kernels.py — DO NOT EDIT
 */

#include <torch/extension.h>
#include "platform.h"
#include "types.h"

#include <cuda_bf16.h>

// Block size for per-block INT8 quantization of exp_avg
constexpr int Q4_QUANT_BLOCK = 8;
constexpr int Q4_KERNEL_BLOCK = 256;

// ═══════════════════════════════════════════════════════════════════════
//  Utility: hash-based PRNG for stochastic rounding
// ═══════════════════════════════════════════════════════════════════════

__device__ __forceinline__ unsigned q4_hash_prng(unsigned step, int idx) {
    unsigned h = step * 2654435761u ^ (unsigned)idx * 2246822519u;
    h ^= h >> 16;
    h *= 0x85ebca6b;
    h ^= h >> 13;
    h *= 0xc2b2ae35;
    h ^= h >> 16;
    return h;
}

__device__ __forceinline__ int8_t q4_float_to_int8_sr(float val, float scale, unsigned rng) {
    float q = val / fmaxf(scale, 1e-12f);
    float q_floor = floorf(q);
    float frac = q - q_floor;
    float threshold = (float)(rng & 0xFFFFFF) / 16777216.0f;
    int q_int = (int)q_floor + (frac > threshold ? 1 : 0);
    return (int8_t)max(-127, min(127, q_int));
}

__device__ __forceinline__ __nv_bfloat16 q4_float_to_bf16_sr(float val, unsigned rng) {
    // Stochastic rounding: add random noise within the BF16 ULP
    __nv_bfloat16 bf = __float2bfloat16(val);
    float rounded = __bfloat162float(bf);
    float diff = val - rounded;
    if (diff != 0.0f) {
        float ulp = fabsf(__bfloat162float(__float2bfloat16(fabsf(val) + 1.0f)) -
                          __bfloat162float(__float2bfloat16(fabsf(val))));
        if (ulp > 0.0f) {
            float prob = fabsf(diff) / ulp;
            float threshold = (float)(rng & 0xFFFFFF) / 16777216.0f;
            if (prob > threshold) {
                bf = __float2bfloat16(rounded + copysignf(ulp, diff));
            }
        }
    }
    return bf;
}
"""

GROKADAMW_Q4_SCALAR = r"""
// ═══════════════════════════════════════════════════════════════════════
//  Q4 Scalar Kernel
//
//  Per-block INT8 quantization for exp_avg (block-size 8).
//  BF16 with stochastic rounding for exp_avg_sq and ema.
// ═══════════════════════════════════════════════════════════════════════

template <typename scalar_t>
__launch_bounds__(256, 8)
__global__ void grokadamw_q4_scalar_kernel(
    scalar_t* __restrict__ param,
    int8_t* __restrict__ exp_avg_q,
    __nv_bfloat16* __restrict__ exp_avg_sq_bf16,
    __nv_bfloat16* __restrict__ ema_bf16,
    float* __restrict__ exp_avg_scales,
    const scalar_t* __restrict__ grad,
    const float alpha,
    const float lamb,
    const float beta1,
    const float beta2,
    const float lr,
    const float wd,
    const float eps,
    const float bc1,
    const float bc2,
    const int N
) {
    const int idx = blockIdx.x * blockDim.x + threadIdx.x;
    if (idx >= N) return;

    // Hash-based RNG for stochastic rounding
    unsigned rng = q4_hash_prng(0u, idx);

    // Read gradient
    const float g = static_cast<float>(grad[idx]);

    // Block index for per-block INT8 scales (block-size 8)
    const int _blk = (idx) / 8;

    // Dequantize exp_avg from INT8
    float ea_scale = exp_avg_scales[_blk];
    float exp_avg_val = (float)exp_avg_q[idx] * ea_scale;

    // Dequantize exp_avg_sq from BF16
    float easq_val = __bfloat162float(exp_avg_sq_bf16[idx]);

    // BUG FIX: Define ema_val BEFORE using it
    float ema_val = __bfloat162float(ema_bf16[idx]);

    // 1. EMA gradient filter
    const float e_old = ema_val;
    const float filtered = alpha * e_old + (1.0f - alpha) * g;
    ema_val = filtered;

    // 2. Gradient amplification
    const float amplified = g + lamb * filtered;

    // 3. Adam moment updates
    const float ea = beta1 * exp_avg_val + (1.0f - beta1) * amplified;
    const float easq = beta2 * easq_val + (1.0f - beta2) * amplified * amplified;

    // 4. Requantize exp_avg -> INT8
    float new_scale = fmaxf(fabsf(ea), 1e-12f) / 127.0f;
    rng = q4_hash_prng(1u, idx);
    exp_avg_q[idx] = q4_float_to_int8_sr(ea, new_scale, rng);
    // First thread in quantization block writes the scale
    if (idx % 8 == 0) {
        exp_avg_scales[_blk] = new_scale;
    }

    // 5. Requantize exp_avg_sq -> BF16 with stochastic rounding
    rng = q4_hash_prng(2u, idx);
    exp_avg_sq_bf16[idx] = q4_float_to_bf16_sr(easq, rng);

    // 6. Requantize ema -> BF16 with stochastic rounding
    rng = q4_hash_prng(3u, idx);
    ema_bf16[idx] = q4_float_to_bf16_sr(ema_val, rng);

    // 7. Adam step with decoupled weight decay
    const float step_size = lr / bc1;
    const float denom = sqrtf(easq / bc2) + eps;
    float p = static_cast<float>(param[idx]);
    p *= (1.0f - lr * wd);
    p -= step_size * ea / denom;
    param[idx] = static_cast<scalar_t>(p);
}
"""

GROKADAMW_Q4_VEC4 = r"""
// ═══════════════════════════════════════════════════════════════════════
//  Q4 Vec4 Kernel (FP32 tensors only)
//
//  Float4-vectorized variant with per-component variable names to
//  avoid redeclaration bugs. Per-block INT8 for exp_avg (block-size 8).
// ═══════════════════════════════════════════════════════════════════════

__launch_bounds__(256, 8)
__global__ void grokadamw_q4_vec4_kernel(
    float4* __restrict__ param4,
    int8_t* __restrict__ exp_avg_q,
    __nv_bfloat16* __restrict__ exp_avg_sq_bf16,
    __nv_bfloat16* __restrict__ ema_bf16,
    float* __restrict__ exp_avg_scales,
    const float4* __restrict__ grad4,
    const float alpha,
    const float lamb,
    const float beta1,
    const float beta2,
    const float lr,
    const float wd,
    const float eps,
    const float bc1,
    const float bc2,
    const int N4
) {
    const int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i >= N4) return;

    // Read float4 gradient and params
    float4 g = grad4[i];
    float4 p = param4[i];

    // BUG FIX: Block index must use parentheses for operator precedence
    const int _blk_x = (i*4+0) / 8;
    const int _blk_y = (i*4+1) / 8;
    const int _blk_z = (i*4+2) / 8;
    const int _blk_w = (i*4+3) / 8;

    // Dequantize exp_avg from INT8 (per-component)
    float exp_avg_val_x = (float)exp_avg_q[i*4+0] * exp_avg_scales[_blk_x];
    float exp_avg_val_y = (float)exp_avg_q[i*4+1] * exp_avg_scales[_blk_y];
    float exp_avg_val_z = (float)exp_avg_q[i*4+2] * exp_avg_scales[_blk_z];
    float exp_avg_val_w = (float)exp_avg_q[i*4+3] * exp_avg_scales[_blk_w];

    // Dequantize exp_avg_sq from BF16
    float easq_x = __bfloat162float(exp_avg_sq_bf16[i*4+0]);
    float easq_y = __bfloat162float(exp_avg_sq_bf16[i*4+1]);
    float easq_z = __bfloat162float(exp_avg_sq_bf16[i*4+2]);
    float easq_w = __bfloat162float(exp_avg_sq_bf16[i*4+3]);

    // BUG FIX: Define ema_val BEFORE using it
    float ema_val_x = __bfloat162float(ema_bf16[i*4+0]);
    float ema_val_y = __bfloat162float(ema_bf16[i*4+1]);
    float ema_val_z = __bfloat162float(ema_bf16[i*4+2]);
    float ema_val_w = __bfloat162float(ema_bf16[i*4+3]);

    // ── 1. EMA gradient filter (per-component variable names) ──

    // Component x
    const float e_old_x = ema_val_x;
    const float filtered_x = alpha * e_old_x + (1.0f - alpha) * g.x;
    ema_val_x = filtered_x;
    const float amplified_x = g.x + lamb * filtered_x;

    // Component y
    const float e_old_y = ema_val_y;
    const float filtered_y = alpha * e_old_y + (1.0f - alpha) * g.y;
    ema_val_y = filtered_y;
    const float amplified_y = g.y + lamb * filtered_y;

    // Component z
    const float e_old_z = ema_val_z;
    const float filtered_z = alpha * e_old_z + (1.0f - alpha) * g.z;
    ema_val_z = filtered_z;
    const float amplified_z = g.z + lamb * filtered_z;

    // Component w
    const float e_old_w = ema_val_w;
    const float filtered_w = alpha * e_old_w + (1.0f - alpha) * g.w;
    ema_val_w = filtered_w;
    const float amplified_w = g.w + lamb * filtered_w;

    // ── 2. Adam moments (CORRECT per-component amplified values) ──

    const float ea_x = beta1 * exp_avg_val_x + (1.0f - beta1) * amplified_x;
    const float ea_y = beta1 * exp_avg_val_y + (1.0f - beta1) * amplified_y;
    const float ea_z = beta1 * exp_avg_val_z + (1.0f - beta1) * amplified_z;
    const float ea_w = beta1 * exp_avg_val_w + (1.0f - beta1) * amplified_w;

    const float esq_x = beta2 * easq_x + (1.0f - beta2) * amplified_x * amplified_x;
    const float esq_y = beta2 * easq_y + (1.0f - beta2) * amplified_y * amplified_y;
    const float esq_z = beta2 * easq_z + (1.0f - beta2) * amplified_z * amplified_z;
    const float esq_w = beta2 * easq_w + (1.0f - beta2) * amplified_w * amplified_w;

    // ── 3. Requantize exp_avg -> INT8 ──
    unsigned rng;

    float new_scale_x = fmaxf(fabsf(ea_x), 1e-12f) / 127.0f;
    float new_scale_y = fmaxf(fabsf(ea_y), 1e-12f) / 127.0f;
    float new_scale_z = fmaxf(fabsf(ea_z), 1e-12f) / 127.0f;
    float new_scale_w = fmaxf(fabsf(ea_w), 1e-12f) / 127.0f;

    rng = q4_hash_prng(1u, i*4+0);
    exp_avg_q[i*4+0] = q4_float_to_int8_sr(ea_x, new_scale_x, rng);
    rng = q4_hash_prng(1u, i*4+1);
    exp_avg_q[i*4+1] = q4_float_to_int8_sr(ea_y, new_scale_y, rng);
    rng = q4_hash_prng(1u, i*4+2);
    exp_avg_q[i*4+2] = q4_float_to_int8_sr(ea_z, new_scale_z, rng);
    rng = q4_hash_prng(1u, i*4+3);
    exp_avg_q[i*4+3] = q4_float_to_int8_sr(ea_w, new_scale_w, rng);

    // Write per-block scales (first element in each block)
    if ((i*4+0) % 8 == 0) exp_avg_scales[_blk_x] = new_scale_x;
    if ((i*4+1) % 8 == 0) exp_avg_scales[_blk_y] = new_scale_y;
    if ((i*4+2) % 8 == 0) exp_avg_scales[_blk_z] = new_scale_z;
    if ((i*4+3) % 8 == 0) exp_avg_scales[_blk_w] = new_scale_w;

    // ── 4. Requantize exp_avg_sq -> BF16 ──
    rng = q4_hash_prng(2u, i*4+0);
    exp_avg_sq_bf16[i*4+0] = q4_float_to_bf16_sr(esq_x, rng);
    rng = q4_hash_prng(2u, i*4+1);
    exp_avg_sq_bf16[i*4+1] = q4_float_to_bf16_sr(esq_y, rng);
    rng = q4_hash_prng(2u, i*4+2);
    exp_avg_sq_bf16[i*4+2] = q4_float_to_bf16_sr(esq_z, rng);
    rng = q4_hash_prng(2u, i*4+3);
    exp_avg_sq_bf16[i*4+3] = q4_float_to_bf16_sr(esq_w, rng);

    // ── 5. Requantize ema -> BF16 ──
    rng = q4_hash_prng(3u, i*4+0);
    ema_bf16[i*4+0] = q4_float_to_bf16_sr(ema_val_x, rng);
    rng = q4_hash_prng(3u, i*4+1);
    ema_bf16[i*4+1] = q4_float_to_bf16_sr(ema_val_y, rng);
    rng = q4_hash_prng(3u, i*4+2);
    ema_bf16[i*4+2] = q4_float_to_bf16_sr(ema_val_z, rng);
    rng = q4_hash_prng(3u, i*4+3);
    ema_bf16[i*4+3] = q4_float_to_bf16_sr(ema_val_w, rng);

    // ── 6. Adam step with decoupled weight decay ──
    const float step_size = lr / bc1;
    const float decay = 1.0f - lr * wd;

    p.x = decay * p.x - step_size * ea_x / (sqrtf(esq_x / bc2) + eps);
    p.y = decay * p.y - step_size * ea_y / (sqrtf(esq_y / bc2) + eps);
    p.z = decay * p.z - step_size * ea_z / (sqrtf(esq_z / bc2) + eps);
    p.w = decay * p.w - step_size * ea_w / (sqrtf(esq_w / bc2) + eps);
    param4[i] = p;
}
"""

GROKADAMW_Q4_DISPATCH = r"""
// ═══════════════════════════════════════════════════════════════════════
//  C++ Dispatch: GrokAdamW Q4 Step
// ═══════════════════════════════════════════════════════════════════════

void launch_grokadamw_q4_step(
    torch::Tensor param,
    torch::Tensor exp_avg_q,
    torch::Tensor exp_avg_sq_bf16,
    torch::Tensor ema_bf16,
    torch::Tensor exp_avg_scales,
    torch::Tensor grad,
    float alpha,
    float lamb,
    float beta1,
    float beta2,
    float lr,
    float wd,
    float eps,
    float bc1,
    float bc2
) {
    const int N = param.numel();
    if (N == 0) return;

    // float4 fast path: FP32 params, N divisible by 4, 16-byte aligned
    if (param.scalar_type() == at::ScalarType::Float &&
        N % 4 == 0 &&
        reinterpret_cast<uintptr_t>(param.data_ptr()) % 16 == 0 &&
        reinterpret_cast<uintptr_t>(grad.data_ptr()) % 16 == 0) {
        const int N4 = N / 4;
        const int grid4 = (N4 + Q4_KERNEL_BLOCK - 1) / Q4_KERNEL_BLOCK;
        grokadamw_q4_vec4_kernel<<<grid4, Q4_KERNEL_BLOCK>>>(
            reinterpret_cast<float4*>(param.data_ptr<float>()),
            exp_avg_q.data_ptr<int8_t>(),
            reinterpret_cast<__nv_bfloat16*>(exp_avg_sq_bf16.data_ptr()),
            reinterpret_cast<__nv_bfloat16*>(ema_bf16.data_ptr()),
            exp_avg_scales.data_ptr<float>(),
            reinterpret_cast<const float4*>(grad.data_ptr<float>()),
            alpha, lamb, beta1, beta2, lr, wd, eps, bc1, bc2, N4);
        return;
    }

    const int grid = (N + Q4_KERNEL_BLOCK - 1) / Q4_KERNEL_BLOCK;

    AT_DISPATCH_FLOATING_TYPES_AND2(
        at::ScalarType::Half, at::ScalarType::BFloat16,
        param.scalar_type(), "grokadamw_q4_step", ([&] {
        grokadamw_q4_scalar_kernel<scalar_t><<<grid, Q4_KERNEL_BLOCK>>>(
            param.data_ptr<scalar_t>(),
            exp_avg_q.data_ptr<int8_t>(),
            reinterpret_cast<__nv_bfloat16*>(exp_avg_sq_bf16.data_ptr()),
            reinterpret_cast<__nv_bfloat16*>(ema_bf16.data_ptr()),
            exp_avg_scales.data_ptr<float>(),
            grad.data_ptr<scalar_t>(),
            alpha, lamb, beta1, beta2, lr, wd, eps, bc1, bc2, N);
    }));
}
"""


# ═══════════════════════════════════════════════════════════════════════════
#  2. compute_absmax_scale_kernel.cu
# ═══════════════════════════════════════════════════════════════════════════

COMPUTE_ABSMAX_SCALE = r"""/*
 * Compute Absmax Scale Kernel — Generated
 *
 * Computes max(|input|) over a float array on the GPU and writes
 * scale = max_val / max_representable to a device-side float.
 *
 * AUTO-GENERATED by codegen/generate_kernels.py — DO NOT EDIT
 */

#include <torch/extension.h>
#include "platform.h"
#include "types.h"

constexpr int ABSMAX_BLOCK = 256;

// ═══════════════════════════════════════════════════════════════════════
//  Atomics helper: atomicMax for float using CAS loop
// ═══════════════════════════════════════════════════════════════════════

__device__ __forceinline__ void atomicMaxFloat(float* addr, float value) {
    // Reinterpret as int for CAS. Works because IEEE 754 positive floats
    // have the same ordering as their integer bit representations.
    int* addr_as_int = reinterpret_cast<int*>(addr);
    int old = *addr_as_int;
    int assumed;
    do {
        assumed = old;
        float old_f = __int_as_float(assumed);
        if (old_f >= value) break;
        old = atomicCAS(addr_as_int, assumed, __float_as_int(value));
    } while (assumed != old);
}

// ═══════════════════════════════════════════════════════════════════════
//  Kernel: compute_absmax_kernel
//
//  Uses warp-level reduction with __shfl_down_sync, then shared memory
//  reduction across warps, then atomicMax across blocks.
// ═══════════════════════════════════════════════════════════════════════

__launch_bounds__(256, 8)
__global__ void compute_absmax_kernel(
    const float* __restrict__ input,
    float* __restrict__ scale_out,
    const int N,
    const float max_representable  // e.g., 448.0 for FP8 E4M3
) {
    __shared__ float smem[32];  // one float per warp (max 32 warps per block)

    const int tid = threadIdx.x;
    const int global_idx = blockIdx.x * blockDim.x + tid;
    const int stride = gridDim.x * blockDim.x;

    // Grid-stride loop to find thread-local max
    float local_max = 0.0f;
    for (int i = global_idx; i < N; i += stride) {
        local_max = fmaxf(local_max, fabsf(input[i]));
    }

    // Warp-level reduction via shuffle
    for (int offset = WARP_SIZE / 2; offset > 0; offset >>= 1) {
        local_max = fmaxf(local_max, SHFL_DOWN(local_max, offset));
    }

    // Write warp results to shared memory
    const int lane = tid % WARP_SIZE;
    const int warp_id = tid / WARP_SIZE;
    if (lane == 0) {
        smem[warp_id] = local_max;
    }
    __syncthreads();

    // First warp reduces across all warps
    const int num_warps = (blockDim.x + WARP_SIZE - 1) / WARP_SIZE;
    if (warp_id == 0) {
        local_max = (lane < num_warps) ? smem[lane] : 0.0f;
        for (int offset = WARP_SIZE / 2; offset > 0; offset >>= 1) {
            local_max = fmaxf(local_max, SHFL_DOWN(local_max, offset));
        }
    }

    // Lane 0 of warp 0 writes to global result via atomicMax
    if (tid == 0) {
        atomicMaxFloat(scale_out, local_max / fmaxf(max_representable, 1e-12f));
    }
}

// ═══════════════════════════════════════════════════════════════════════
//  C++ Launch Function
// ═══════════════════════════════════════════════════════════════════════

void launch_compute_absmax_scale(
    torch::Tensor input,
    torch::Tensor scale_out,
    float max_representable
) {
    TORCH_CHECK(input.is_contiguous(), "input must be contiguous");
    TORCH_CHECK(input.scalar_type() == at::ScalarType::Float,
                "input must be FP32");
    TORCH_CHECK(scale_out.numel() == 1, "scale_out must be a single float");

    const int N = input.numel();
    if (N == 0) return;

    // Zero the output first (atomicMax starts from 0)
    scale_out.zero_();

    const int grid = min((N + ABSMAX_BLOCK - 1) / ABSMAX_BLOCK, 1024);
    compute_absmax_kernel<<<grid, ABSMAX_BLOCK>>>(
        input.data_ptr<float>(),
        scale_out.data_ptr<float>(),
        N,
        max_representable);
}
"""


# ═══════════════════════════════════════════════════════════════════════════
#  3. muon_update_generated.cu
# ═══════════════════════════════════════════════════════════════════════════

MUON_UPDATE_GENERATED = r"""/*
 * Muon Update — Generated Stream Variants
 *
 * Muon optimizer update kernels with stream_load/stream_store for
 * momentum state to avoid L2 cache pollution.
 *
 * AUTO-GENERATED by codegen/generate_kernels.py — DO NOT EDIT
 */

#include <torch/extension.h>
#include "platform.h"
#include "types.h"

constexpr int MUON_STREAM_BLOCK = 256;

// ═══════════════════════════════════════════════════════════════════════
//  Scalar Stream Kernel
//
//  Uses stream_load for momentum_buffer reads and stream_store for
//  momentum_buffer writes to bypass L2 cache.
// ═══════════════════════════════════════════════════════════════════════

template <typename scalar_t>
__launch_bounds__(256, 8)
__global__ void muon_update_stream_kernel(
    scalar_t* __restrict__ param,
    float* __restrict__ momentum_buffer,
    const scalar_t* __restrict__ orth,
    const float neg_lr_scale,
    const float decay_factor,
    const float momentum,
    const int numel
) {
    const int idx = blockIdx.x * blockDim.x + threadIdx.x;
    if (idx >= numel) return;

    // Stream load momentum buffer (bypass L2)
    float mom_val = stream_load(&momentum_buffer[idx]);

    // Read orthogonalized gradient
    float o = static_cast<float>(orth[idx]);

    // Update momentum: buf = momentum * buf + orth
    float new_mom = momentum * mom_val + o;

    // Stream store updated momentum (bypass L2)
    stream_store(&momentum_buffer[idx], new_mom);

    // Update parameter: p = (p + neg_lr * orth) * decay
    float p = static_cast<float>(param[idx]);
    p += neg_lr_scale * o;
    p *= decay_factor;
    param[idx] = static_cast<scalar_t>(p);
}

// ═══════════════════════════════════════════════════════════════════════
//  Vec4 Stream Kernel (FP32 only)
//
//  float4-vectorized with stream_load4/stream_store4 for momentum.
// ═══════════════════════════════════════════════════════════════════════

__launch_bounds__(256, 8)
__global__ void muon_update_stream_vec4_kernel(
    float4* __restrict__ param4,
    float4* __restrict__ momentum_buffer4,
    const float4* __restrict__ orth4,
    const float neg_lr_scale,
    const float decay_factor,
    const float momentum,
    const int N4
) {
    const int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i >= N4) return;

    // Stream load momentum buffer
    float4 mom = stream_load4(&momentum_buffer4[i]);
    float4 o = orth4[i];
    float4 p = param4[i];

    // Update momentum: buf = momentum * buf + orth
    mom.x = momentum * mom.x + o.x;
    mom.y = momentum * mom.y + o.y;
    mom.z = momentum * mom.z + o.z;
    mom.w = momentum * mom.w + o.w;

    // Stream store updated momentum
    stream_store4(&momentum_buffer4[i], mom);

    // Update parameter: p = (p + neg_lr * orth) * decay
    p.x = (p.x + neg_lr_scale * o.x) * decay_factor;
    p.y = (p.y + neg_lr_scale * o.y) * decay_factor;
    p.z = (p.z + neg_lr_scale * o.z) * decay_factor;
    p.w = (p.w + neg_lr_scale * o.w) * decay_factor;

    param4[i] = p;
}

// ═══════════════════════════════════════════════════════════════════════
//  C++ Dispatch: Muon Update Stream
// ═══════════════════════════════════════════════════════════════════════

void launch_muon_update_stream(
    torch::Tensor param,
    torch::Tensor momentum_buffer,
    torch::Tensor orth,
    float neg_lr_scale,
    float decay_factor,
    float momentum
) {
    const int N = param.numel();
    if (N == 0) return;

    // float4 fast path: FP32, N divisible by 4, 16-byte aligned
    if (param.scalar_type() == at::ScalarType::Float &&
        N % 4 == 0 &&
        reinterpret_cast<uintptr_t>(param.data_ptr()) % 16 == 0 &&
        reinterpret_cast<uintptr_t>(orth.data_ptr()) % 16 == 0 &&
        reinterpret_cast<uintptr_t>(momentum_buffer.data_ptr()) % 16 == 0) {
        const int N4 = N / 4;
        const int grid4 = (N4 + MUON_STREAM_BLOCK - 1) / MUON_STREAM_BLOCK;
        muon_update_stream_vec4_kernel<<<grid4, MUON_STREAM_BLOCK>>>(
            reinterpret_cast<float4*>(param.data_ptr<float>()),
            reinterpret_cast<float4*>(momentum_buffer.data_ptr<float>()),
            reinterpret_cast<const float4*>(orth.data_ptr<float>()),
            neg_lr_scale, decay_factor, momentum, N4);
        return;
    }

    const int grid = (N + MUON_STREAM_BLOCK - 1) / MUON_STREAM_BLOCK;

    AT_DISPATCH_FLOATING_TYPES_AND2(
        at::ScalarType::Half, at::ScalarType::BFloat16,
        param.scalar_type(), "muon_update_stream", ([&] {
        muon_update_stream_kernel<scalar_t><<<grid, MUON_STREAM_BLOCK>>>(
            param.data_ptr<scalar_t>(),
            momentum_buffer.data_ptr<float>(),
            orth.data_ptr<scalar_t>(),
            neg_lr_scale, decay_factor, momentum, N);
    }));
}
"""


def generate_kernels(output_dir: str) -> None:
    os.makedirs(output_dir, exist_ok=True)

    # 1. GrokAdamW Q4
    path = os.path.join(output_dir, "grokadamw_generated.cu")
    with open(path, "w") as f:
        f.write(GROKADAMW_Q4_HEADER)
        f.write(GROKADAMW_Q4_SCALAR)
        f.write(GROKADAMW_Q4_VEC4)
        f.write(GROKADAMW_Q4_DISPATCH)
    print(f"  Generated {path}")

    # 2. Compute absmax scale
    path = os.path.join(output_dir, "compute_absmax_scale_kernel.cu")
    with open(path, "w") as f:
        f.write(COMPUTE_ABSMAX_SCALE)
    print(f"  Generated {path}")

    # 3. Muon update stream variants
    path = os.path.join(output_dir, "muon_update_generated.cu")
    with open(path, "w") as f:
        f.write(MUON_UPDATE_GENERATED)
    print(f"  Generated {path}")


def main():
    parser = argparse.ArgumentParser(description="Generate SuperGrok1.5 optimizer CUDA kernels")
    parser.add_argument("--output", type=str, required=True,
                        help="Output directory for generated .cu files")
    args = parser.parse_args()

    print("generate_kernels.py: Generating optimizer CUDA kernels...")
    generate_kernels(args.output)
    print("Done.")


if __name__ == "__main__":
    main()
