#!/usr/bin/env python3
"""
SuperGrok v2 — SG2 Fused Element Kernel Code Generator

Generates all SG2 fused_elem kernel variants across the axes:
  - State:    F (FP32 optimizer states), Q (Config4: INT8-block8 / INT4-block32 / BF16+SR)
  - Expert:   FP32 (base), INT8 (per-tensor scale), MXFP4 (packed nibbles + shared exponents)
  - HW:       generic, sm80 (cp.async for weight loading)
  - MoE:      D (dense), M (MoE with active_mask early-exit)
  - d16:      generic d_inner, d16 (d_inner=16 compile-time constant for full unrolling)

Naming: sg2_fused_elem_{state}_{expert}_{hw}_{moe}[_d16]_kernel

Also generates:
  - 16 meta-net-only async kernels   (Expert x HW x d16, adjusted for MXFP4)
  - 7 persistent scan fusion variants (State x HW x d16, minus base)

Output:
  csrc/cuda/generated/sg2_fused_elem_generated.cu
  csrc/cuda/generated/sg2_metanet_only_generated.cu
  csrc/cuda/generated/sg2_persistent_scan_generated.cu

Usage:
    python codegen/generate_sg2_kernels.py --output csrc/cuda/generated/
"""

import argparse
import itertools
import os
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
#  Configuration — variant axes
# ---------------------------------------------------------------------------

STATES = ["F", "Q"]
EXPERTS = ["fp32", "int8", "mxfp4"]
HW_OPTS = ["generic", "sm80"]
MOE_OPTS = ["D", "M"]
D16_OPTS = [False, True]

DEFAULT_OUTPUT = Path(__file__).resolve().parent.parent / "csrc" / "cuda" / "generated"

# ---------------------------------------------------------------------------
#  Naming helpers
# ---------------------------------------------------------------------------

def fused_elem_kernel_name(state, expert, hw, moe, d16):
    parts = ["sg2_fused_elem", state, expert, hw, moe]
    if d16:
        parts.append("d16")
    parts.append("kernel")
    return "_".join(parts)


def meta_kernel_name(expert, hw, moe, d16):
    parts = ["sg2_metanet", expert, hw, moe]
    if d16:
        parts.append("d16")
    parts.append("kernel")
    return "_".join(parts)


def pscan_kernel_name(state, hw, d16):
    parts = ["sg2_persistent_scan", state, hw]
    if d16:
        parts.append("d16")
    parts.append("kernel")
    return "_".join(parts)


def launcher_name(kname):
    return "launch_" + kname.replace("_kernel", "")


# ---------------------------------------------------------------------------
#  File header (common to all generated .cu files)
# ---------------------------------------------------------------------------

FILE_HEADER = """\
/* GENERATED by codegen/generate_sg2_kernels.py — DO NOT EDIT */

#include <torch/extension.h>
#include <ATen/cuda/CUDAContext.h>
#include "platform.h"
#include "types.h"
#include "utils.cuh"

#if GROK_CUDA
#include <cuda_bf16.h>
#include <cuda_pipeline.h>
#endif

#ifndef MAX_D_INNER
#define MAX_D_INNER 64
#endif
#ifndef MAX_D_MODEL
#define MAX_D_MODEL 64
#endif
#ifndef MAX_GRU_HIDDEN
#define MAX_GRU_HIDDEN 32
#endif
#ifndef MAX_EXPERT_HIDDEN
#define MAX_EXPERT_HIDDEN 64
#endif

// ═══════════════════════════════════════════════════════════════════════
//  MXFP4 dequant helper
// ═══════════════════════════════════════════════════════════════════════
__device__ __forceinline__ float dequant_mxfp4_gen(
    uint8_t nibble, uint8_t shared_exp, float scale
) {
    return ldexpf(static_cast<float>(nibble), static_cast<int>(shared_exp) - 127) * scale;
}

"""


# ---------------------------------------------------------------------------
#  Parameter declaration helpers
# ---------------------------------------------------------------------------

def state_params(state):
    """Kernel parameter declarations for optimizer state."""
    if state == "F":
        return [
            "float* __restrict__ exp_avg",
            "float* __restrict__ exp_avg_sq",
            "float* __restrict__ mu",
            "float* __restrict__ gru_state",
        ]
    else:  # Q
        return [
            "int8_t* __restrict__ exp_avg_q",
            "float* __restrict__ exp_avg_scales",
            "int8_t* __restrict__ exp_avg_sq_q",
            "float* __restrict__ exp_avg_sq_scales",
            "int8_t* __restrict__ mu_q",       # INT4 packed nibbles
            "float* __restrict__ mu_scales",    # block_size=32
            "__nv_bfloat16* __restrict__ gru_state",
        ]


def expert_params(expert):
    """Kernel parameter declarations for expert weights."""
    if expert == "fp32":
        return [
            "const float* __restrict__ expert_W1",
            "const float* __restrict__ expert_b1",
            "const float* __restrict__ expert_W2",
            "const float* __restrict__ expert_b2",
        ]
    elif expert == "int8":
        return [
            "const int8_t* __restrict__ expert_W1_q",
            "const int8_t* __restrict__ expert_b1_q",
            "const int8_t* __restrict__ expert_W2_q",
            "const int8_t* __restrict__ expert_b2_q",
            "const float expert_W1_scale",
            "const float expert_b1_scale",
            "const float expert_W2_scale",
            "const float expert_b2_scale",
        ]
    elif expert == "mxfp4":
        return [
            "const uint8_t* __restrict__ expert_W1_q",
            "const uint8_t* __restrict__ expert_W1_exp",
            "const uint8_t* __restrict__ expert_W2_q",
            "const uint8_t* __restrict__ expert_W2_exp",
            "const uint8_t* __restrict__ expert_b1_q",
            "const uint8_t* __restrict__ expert_b1_exp",
            "const uint8_t* __restrict__ expert_b2_q",
            "const uint8_t* __restrict__ expert_b2_exp",
            "const float mxfp4_scale",
        ]
    raise ValueError(f"Unknown expert: {expert}")


# ---------------------------------------------------------------------------
#  Shared memory layout (same for all — always FP32 in smem after dequant)
# ---------------------------------------------------------------------------

def gen_smem_layout(d16, I="    "):
    d_inner_ref = "D_INNER" if d16 else "d_inner"
    return f"""{I}const int gru_input_dim = 2 + 2 * d_model;
{I}const int gru_row_len = gru_input_dim + gru_hidden;
{I}const int op_size = d_model * {d_inner_ref};
{I}const int gru_mat_size = gru_hidden * gru_row_len;

{I}extern __shared__ float smem[];

{I}float* s_out_fwd = smem;
{I}float* s_out_bwd = smem + op_size;
{I}float* s_gru_Wz  = s_out_bwd + op_size;
{I}float* s_gru_Wr  = s_gru_Wz + gru_mat_size;
{I}float* s_gru_Wh  = s_gru_Wr + gru_mat_size;
{I}float* s_gru_bz  = s_gru_Wh + gru_mat_size;
{I}float* s_gru_br  = s_gru_bz + gru_hidden;
{I}float* s_gru_bh  = s_gru_br + gru_hidden;
{I}float* s_expert_W1 = s_gru_bh + gru_hidden;
{I}float* s_expert_b1 = s_expert_W1 + num_experts * expert_hidden;
{I}float* s_expert_W2 = s_expert_b1 + num_experts * expert_hidden;
{I}float* s_expert_b2 = s_expert_W2 + num_experts * expert_hidden;

{I}const int tid = threadIdx.x;
{I}const int block_size = blockDim.x;"""


# ---------------------------------------------------------------------------
#  Weight loading code generation
# ---------------------------------------------------------------------------

def gen_outproj_gru_load(hw, I="    "):
    """Generate out_proj + GRU weight loading."""
    if hw == "sm80":
        return f"""{I}// cp.async prefetch out_proj weights
{I}for (int i = tid; i < 2 * op_size; i += block_size) {{
{I}    const float* src = (i < op_size) ? &out_proj_fwd_W[i] : &out_proj_bwd_W[i - op_size];
{I}#if GROK_CUDA && defined(__CUDA_ARCH__) && __CUDA_ARCH__ >= 800
{I}    __pipeline_memcpy_async(&smem[i], src, sizeof(float));
{I}#else
{I}    smem[i] = *src;
{I}#endif
{I}}}
{I}// cp.async prefetch GRU weights
{I}const float* gru_gmem[] = {{gru_Wz, gru_Wr, gru_Wh, gru_bz, gru_br, gru_bh}};
{I}int gru_sizes[] = {{gru_mat_size, gru_mat_size, gru_mat_size, gru_hidden, gru_hidden, gru_hidden}};
{I}float* gru_dst = s_gru_Wz;
{I}int gru_offset = 0;
{I}for (int seg = 0; seg < 6; seg++) {{
{I}    for (int i = tid; i < gru_sizes[seg]; i += block_size) {{
{I}#if GROK_CUDA && defined(__CUDA_ARCH__) && __CUDA_ARCH__ >= 800
{I}        __pipeline_memcpy_async(&gru_dst[gru_offset + i], &gru_gmem[seg][i], sizeof(float));
{I}#else
{I}        gru_dst[gru_offset + i] = gru_gmem[seg][i];
{I}#endif
{I}    }}
{I}    gru_offset += gru_sizes[seg];
{I}}}
{I}#if GROK_CUDA && defined(__CUDA_ARCH__) && __CUDA_ARCH__ >= 800
{I}__pipeline_commit();
{I}#endif"""
    else:
        return f"""{I}// Load out_proj weights
{I}for (int i = tid; i < 2 * op_size; i += block_size) {{
{I}    if (i < op_size) smem[i] = out_proj_fwd_W[i];
{I}    else smem[i] = out_proj_bwd_W[i - op_size];
{I}}}
{I}// Load GRU weights
{I}const float* gru_gmem[] = {{gru_Wz, gru_Wr, gru_Wh, gru_bz, gru_br, gru_bh}};
{I}int gru_sizes[] = {{gru_mat_size, gru_mat_size, gru_mat_size, gru_hidden, gru_hidden, gru_hidden}};
{I}float* gru_dst = s_gru_Wz;
{I}int gru_offset = 0;
{I}for (int seg = 0; seg < 6; seg++) {{
{I}    for (int i = tid; i < gru_sizes[seg]; i += block_size)
{I}        gru_dst[gru_offset + i] = gru_gmem[seg][i];
{I}    gru_offset += gru_sizes[seg];
{I}}}"""


def gen_expert_load(expert, hw, I="    "):
    """Generate expert weight loading (with dequant for int8/mxfp4)."""
    cpasync = (hw == "sm80")

    if expert == "fp32":
        if cpasync:
            loads = f"""{I}for (int i = tid; i < num_experts * expert_hidden; i += block_size) {{
{I}#if GROK_CUDA && defined(__CUDA_ARCH__) && __CUDA_ARCH__ >= 800
{I}    __pipeline_memcpy_async(&s_expert_W1[i], &expert_W1[i], sizeof(float));
{I}    __pipeline_memcpy_async(&s_expert_b1[i], &expert_b1[i], sizeof(float));
{I}    __pipeline_memcpy_async(&s_expert_W2[i], &expert_W2[i], sizeof(float));
{I}#else
{I}    s_expert_W1[i] = expert_W1[i];
{I}    s_expert_b1[i] = expert_b1[i];
{I}    s_expert_W2[i] = expert_W2[i];
{I}#endif
{I}}}
{I}for (int i = tid; i < num_experts; i += block_size) {{
{I}#if GROK_CUDA && defined(__CUDA_ARCH__) && __CUDA_ARCH__ >= 800
{I}    __pipeline_memcpy_async(&s_expert_b2[i], &expert_b2[i], sizeof(float));
{I}#else
{I}    s_expert_b2[i] = expert_b2[i];
{I}#endif
{I}}}"""
        else:
            loads = f"""{I}for (int i = tid; i < num_experts * expert_hidden; i += block_size) {{
{I}    s_expert_W1[i] = expert_W1[i];
{I}    s_expert_b1[i] = expert_b1[i];
{I}    s_expert_W2[i] = expert_W2[i];
{I}}}
{I}for (int i = tid; i < num_experts; i += block_size) {{
{I}    s_expert_b2[i] = expert_b2[i];
{I}}}"""

    elif expert == "int8":
        loads = f"""{I}// INT8 dequantize expert weights on load: (float)q_val * scale
{I}for (int i = tid; i < num_experts * expert_hidden; i += block_size) {{
{I}    s_expert_W1[i] = static_cast<float>(expert_W1_q[i]) * expert_W1_scale;
{I}    s_expert_b1[i] = static_cast<float>(expert_b1_q[i]) * expert_b1_scale;
{I}    s_expert_W2[i] = static_cast<float>(expert_W2_q[i]) * expert_W2_scale;
{I}}}
{I}for (int i = tid; i < num_experts; i += block_size) {{
{I}    s_expert_b2[i] = static_cast<float>(expert_b2_q[i]) * expert_b2_scale;
{I}}}"""

    elif expert == "mxfp4":
        loads = f"""{I}// MXFP4 dequantize: extract nibble, lookup exponent, multiply scale
{I}const int exp_total = num_experts * expert_hidden;
{I}for (int i = tid; i < (exp_total + 1) / 2; i += block_size) {{
{I}    uint8_t pw1 = expert_W1_q[i];
{I}    uint8_t pb1 = expert_b1_q[i];
{I}    uint8_t pw2 = expert_W2_q[i];
{I}    uint8_t ew1 = expert_W1_exp[2*i / 32];
{I}    uint8_t eb1 = expert_b1_exp[2*i / 32];
{I}    uint8_t ew2 = expert_W2_exp[2*i / 32];
{I}    s_expert_W1[2*i]   = dequant_mxfp4_gen(pw1 & 0x0F, ew1, mxfp4_scale);
{I}    if (2*i+1 < exp_total) s_expert_W1[2*i+1] = dequant_mxfp4_gen((pw1>>4)&0x0F, ew1, mxfp4_scale);
{I}    s_expert_b1[2*i]   = dequant_mxfp4_gen(pb1 & 0x0F, eb1, mxfp4_scale);
{I}    if (2*i+1 < exp_total) s_expert_b1[2*i+1] = dequant_mxfp4_gen((pb1>>4)&0x0F, eb1, mxfp4_scale);
{I}    s_expert_W2[2*i]   = dequant_mxfp4_gen(pw2 & 0x0F, ew2, mxfp4_scale);
{I}    if (2*i+1 < exp_total) s_expert_W2[2*i+1] = dequant_mxfp4_gen((pw2>>4)&0x0F, ew2, mxfp4_scale);
{I}}}
{I}for (int i = tid; i < (num_experts + 1) / 2; i += block_size) {{
{I}    uint8_t p = expert_b2_q[i];
{I}    uint8_t e = expert_b2_exp[2*i / 32];
{I}    s_expert_b2[2*i]   = dequant_mxfp4_gen(p & 0x0F, e, mxfp4_scale);
{I}    if (2*i+1 < num_experts) s_expert_b2[2*i+1] = dequant_mxfp4_gen((p>>4)&0x0F, e, mxfp4_scale);
{I}}}"""
    else:
        raise ValueError(f"Unknown expert: {expert}")

    # Sync barrier
    if cpasync:
        sync = f"""{I}#if GROK_CUDA && defined(__CUDA_ARCH__) && __CUDA_ARCH__ >= 800
{I}__pipeline_commit();
{I}__pipeline_wait_prior(0);
{I}#endif
{I}__syncthreads();"""
    else:
        sync = f"{I}__syncthreads();"

    return loads + "\n" + sync


# ---------------------------------------------------------------------------
#  Real compute body generation — Steps 1-6
# ---------------------------------------------------------------------------

def gen_compute_steps_1_to_4(state, moe, d16, I="    "):
    """Generate steps 1-4: out_proj, GRU, PEER routing, smart_grad."""
    d_inner_loop = "D_INNER" if d16 else "d_inner"

    lines = []

    # MoE early exit
    if moe == "M":
        lines.append(f"{I}// MoE early-exit")
        lines.append(f"{I}if (!active_mask[idx]) return;")
        lines.append("")

    lines.append(f"{I}float g = static_cast<float>(grad[idx]);")
    lines.append(f"{I}float s = static_cast<float>(sharpness[idx]);")
    lines.append(f"{I}if (!isfinite(g)) g = 0.0f;")
    lines.append(f"{I}if (!isfinite(s)) s = 0.0f;")
    lines.append(f"{I}const int half_d = d_model / 2;")
    lines.append(f"{I}const int peer_input_dim = gru_hidden + 2 * d_model + 2;")
    lines.append("")

    # Step 1: Out_proj — project scan outputs
    lines.append(f"{I}// ── Step 1: Mamba out_proj ──")
    lines.append(f"{I}float fwd_scan[MAX_D_INNER], bwd_scan[MAX_D_INNER];")
    if d16:
        lines.append(f"{I}#pragma unroll")
    lines.append(f"{I}for (int j = 0; j < {d_inner_loop}; j += 4) {{")
    lines.append(f"{I}    float4 fwd4 = *reinterpret_cast<const float4*>(&fwd_scan_out[idx * {d_inner_loop} + j]);")
    lines.append(f"{I}    float4 bwd4 = *reinterpret_cast<const float4*>(&bwd_scan_out[idx * {d_inner_loop} + j]);")
    lines.append(f"{I}    fwd_scan[j]   = fwd4.x; fwd_scan[j+1] = fwd4.y;")
    lines.append(f"{I}    fwd_scan[j+2] = fwd4.z; fwd_scan[j+3] = fwd4.w;")
    lines.append(f"{I}    bwd_scan[j]   = bwd4.x; bwd_scan[j+1] = bwd4.y;")
    lines.append(f"{I}    bwd_scan[j+2] = bwd4.z; bwd_scan[j+3] = bwd4.w;")
    lines.append(f"{I}}}")
    lines.append("")
    lines.append(f"{I}float fwd_ctx[MAX_D_MODEL], bwd_ctx[MAX_D_MODEL];")
    lines.append(f"{I}for (int d = 0; d < d_model; d++) {{")
    lines.append(f"{I}    float fwd_val = 0.0f, bwd_val = 0.0f;")
    if d16:
        lines.append(f"{I}    #pragma unroll")
    lines.append(f"{I}    for (int j = 0; j < {d_inner_loop}; j++) {{")
    lines.append(f"{I}        fwd_val += s_out_fwd[d * {d_inner_loop} + j] * fwd_scan[j];")
    lines.append(f"{I}        bwd_val += s_out_bwd[d * {d_inner_loop} + j] * bwd_scan[j];")
    lines.append(f"{I}    }}")
    lines.append(f"{I}    fwd_ctx[d] = fwd_val;")
    lines.append(f"{I}    bwd_ctx[d] = bwd_val;")
    lines.append(f"{I}}}")
    lines.append("")

    # Step 2: GRU update
    lines.append(f"{I}// ── Step 2: GRU update ──")
    # Load h_old
    if state == "F":
        lines.append(f"{I}float h_old[MAX_GRU_HIDDEN];")
        lines.append(f"{I}for (int j = 0; j < gru_hidden; j++)")
        lines.append(f"{I}    h_old[j] = stream_load(&gru_state[idx * gru_hidden + j]);")
    else:  # Q — gru_state is __nv_bfloat16
        lines.append(f"{I}float h_old[MAX_GRU_HIDDEN];")
        lines.append(f"{I}for (int j = 0; j < gru_hidden; j++)")
        lines.append(f"{I}    h_old[j] = static_cast<float>(gru_state[idx * gru_hidden + j]);")
    lines.append("")

    # z_gate, r_gate
    lines.append(f"{I}float z_gate[MAX_GRU_HIDDEN], r_gate[MAX_GRU_HIDDEN];")
    lines.append(f"{I}for (int j = 0; j < gru_hidden; j++) {{")
    lines.append(f"{I}    float val_z = s_gru_bz[j];")
    lines.append(f"{I}    float val_r = s_gru_br[j];")
    lines.append(f"{I}    val_z += s_gru_Wz[j * gru_row_len + 0] * g;")
    lines.append(f"{I}    val_z += s_gru_Wz[j * gru_row_len + 1] * s;")
    lines.append(f"{I}    val_r += s_gru_Wr[j * gru_row_len + 0] * g;")
    lines.append(f"{I}    val_r += s_gru_Wr[j * gru_row_len + 1] * s;")
    lines.append(f"{I}    int off = 2;")
    lines.append(f"{I}    for (int d = 0; d < d_model; d++) {{")
    lines.append(f"{I}        val_z += s_gru_Wz[j * gru_row_len + off + d] * fwd_ctx[d];")
    lines.append(f"{I}        val_r += s_gru_Wr[j * gru_row_len + off + d] * fwd_ctx[d];")
    lines.append(f"{I}    }}")
    lines.append(f"{I}    off += d_model;")
    lines.append(f"{I}    for (int d = 0; d < d_model; d++) {{")
    lines.append(f"{I}        val_z += s_gru_Wz[j * gru_row_len + off + d] * bwd_ctx[d];")
    lines.append(f"{I}        val_r += s_gru_Wr[j * gru_row_len + off + d] * bwd_ctx[d];")
    lines.append(f"{I}    }}")
    lines.append(f"{I}    off += d_model;")
    lines.append(f"{I}    for (int k = 0; k < gru_hidden; k++) {{")
    lines.append(f"{I}        val_z += s_gru_Wz[j * gru_row_len + off + k] * h_old[k];")
    lines.append(f"{I}        val_r += s_gru_Wr[j * gru_row_len + off + k] * h_old[k];")
    lines.append(f"{I}    }}")
    lines.append(f"{I}    z_gate[j] = 1.0f / (1.0f + expf(-val_z));")
    lines.append(f"{I}    r_gate[j] = 1.0f / (1.0f + expf(-val_r));")
    lines.append(f"{I}}}")
    lines.append("")

    # h_tilde, h_new
    lines.append(f"{I}float h_new[MAX_GRU_HIDDEN];")
    lines.append(f"{I}for (int j = 0; j < gru_hidden; j++) {{")
    lines.append(f"{I}    float val = s_gru_bh[j];")
    lines.append(f"{I}    val += s_gru_Wh[j * gru_row_len + 0] * g;")
    lines.append(f"{I}    val += s_gru_Wh[j * gru_row_len + 1] * s;")
    lines.append(f"{I}    int off = 2;")
    lines.append(f"{I}    for (int d = 0; d < d_model; d++)")
    lines.append(f"{I}        val += s_gru_Wh[j * gru_row_len + off + d] * fwd_ctx[d];")
    lines.append(f"{I}    off += d_model;")
    lines.append(f"{I}    for (int d = 0; d < d_model; d++)")
    lines.append(f"{I}        val += s_gru_Wh[j * gru_row_len + off + d] * bwd_ctx[d];")
    lines.append(f"{I}    off += d_model;")
    lines.append(f"{I}    for (int k = 0; k < gru_hidden; k++)")
    lines.append(f"{I}        val += s_gru_Wh[j * gru_row_len + off + k] * (r_gate[k] * h_old[k]);")
    lines.append(f"{I}    float h_tilde = tanhf(val);")
    lines.append(f"{I}    h_new[j] = (1.0f - z_gate[j]) * h_old[j] + z_gate[j] * h_tilde;")
    lines.append(f"{I}}}")
    lines.append("")

    # Write GRU state
    if state == "F":
        lines.append(f"{I}for (int j = 0; j < gru_hidden; j++)")
        lines.append(f"{I}    stream_store(&gru_state[idx * gru_hidden + j], h_new[j]);")
    else:  # Q — BF16 with stochastic rounding
        lines.append(f"{I}unsigned gru_rng = hash_prng(idx * gru_hidden + global_step * 7919u);")
        lines.append(f"{I}for (int j = 0; j < gru_hidden; j++) {{")
        lines.append(f"{I}    gru_state[idx * gru_hidden + j] = float_to_bf16_stochastic(h_new[j], gru_rng);")
        lines.append(f"{I}    gru_rng = hash_prng(gru_rng + j);")
        lines.append(f"{I}}}")
    lines.append("")

    # Step 3: PEER routing + expert MLP
    lines.append(f"{I}// ── Step 3: Multi-head PEER routing + expert MLP ──")
    lines.append(f"{I}float total_out = 0.0f;")
    lines.append(f"{I}for (int head = 0; head < num_heads; head++) {{")
    lines.append(f"{I}    const float* pq_W = peer_query_Ws + head * d_model * peer_input_dim;")
    lines.append(f"{I}    float query[MAX_D_MODEL];")
    lines.append(f"{I}    for (int d = 0; d < d_model; d++) {{")
    lines.append(f"{I}        float val = 0.0f;")
    lines.append(f"{I}        int poff = 0;")
    lines.append(f"{I}        for (int k = 0; k < gru_hidden; k++)")
    lines.append(f"{I}            val += pq_W[d * peer_input_dim + poff + k] * h_new[k];")
    lines.append(f"{I}        poff += gru_hidden;")
    lines.append(f"{I}        for (int k = 0; k < d_model; k++)")
    lines.append(f"{I}            val += pq_W[d * peer_input_dim + poff + k] * fwd_ctx[k];")
    lines.append(f"{I}        poff += d_model;")
    lines.append(f"{I}        for (int k = 0; k < d_model; k++)")
    lines.append(f"{I}            val += pq_W[d * peer_input_dim + poff + k] * bwd_ctx[k];")
    lines.append(f"{I}        poff += d_model;")
    lines.append(f"{I}        val += pq_W[d * peer_input_dim + poff] * g;")
    lines.append(f"{I}        val += pq_W[d * peer_input_dim + poff + 1] * s;")
    lines.append(f"{I}        query[d] = val;")
    lines.append(f"{I}    }}")
    lines.append("")
    lines.append(f"{I}    // Product-key argmax")
    lines.append(f"{I}    const float* keys_A = prod_keys_A + head * pk_dim * half_d;")
    lines.append(f"{I}    const float* keys_B = prod_keys_B + head * pk_dim * half_d;")
    lines.append(f"{I}    int best_a = 0; float best_sa = -1e30f;")
    lines.append(f"{I}    for (int k = 0; k < pk_dim; k++) {{")
    lines.append(f"{I}        float dot = 0.0f;")
    lines.append(f"{I}        for (int d = 0; d < half_d; d++)")
    lines.append(f"{I}            dot += query[d] * LDG(&keys_A[k * half_d + d]);")
    lines.append(f"{I}        if (dot > best_sa) {{ best_sa = dot; best_a = k; }}")
    lines.append(f"{I}    }}")
    lines.append(f"{I}    int best_b = 0; float best_sb = -1e30f;")
    lines.append(f"{I}    for (int k = 0; k < pk_dim; k++) {{")
    lines.append(f"{I}        float dot = 0.0f;")
    lines.append(f"{I}        for (int d = 0; d < half_d; d++)")
    lines.append(f"{I}            dot += query[half_d + d] * LDG(&keys_B[k * half_d + d]);")
    lines.append(f"{I}        if (dot > best_sb) {{ best_sb = dot; best_b = k; }}")
    lines.append(f"{I}    }}")
    lines.append(f"{I}    int expert_idx = best_a * pk_dim + best_b;")
    lines.append(f"{I}    if (expert_idx >= num_experts) expert_idx = num_experts - 1;")
    lines.append(f"{I}    if (expert_counts != nullptr)")
    lines.append(f"{I}        atomicAdd(&expert_counts[expert_idx], 1);")
    lines.append("")
    lines.append(f"{I}    // Expert MLP: ReLU hidden layer")
    lines.append(f"{I}    float head_out = s_expert_b2[expert_idx];")
    lines.append(f"{I}    for (int h = 0; h < expert_hidden; h++) {{")
    lines.append(f"{I}        float z_val = s_expert_W1[expert_idx * expert_hidden + h] * g")
    lines.append(f"{I}                    + s_expert_b1[expert_idx * expert_hidden + h];")
    lines.append(f"{I}        z_val = fmaxf(z_val, 0.0f);")
    lines.append(f"{I}        head_out += s_expert_W2[expert_idx * expert_hidden + h] * z_val;")
    lines.append(f"{I}    }}")
    lines.append(f"{I}    total_out += head_out;")
    lines.append(f"{I}}}")
    lines.append("")

    # Step 4: smart gradient
    lines.append(f"{I}// ── Step 4: Smart gradient ──")
    lines.append(f"{I}float smart_grad = g + rescale * total_out / static_cast<float>(num_heads);")
    lines.append("")

    return "\n".join(lines)


def gen_steps_5_6_adam(state, I="    "):
    """Generate steps 5-6: mu EMA + Adam update."""
    lines = []

    # Step 5: mu EMA
    lines.append(f"{I}// ── Step 5: Mu EMA update ──")
    if state == "F":
        lines.append(f"{I}float mu_val = stream_load(&mu[idx]);")
        lines.append(f"{I}mu_val = alpha * mu_val + (1.0f - alpha) * g;")
        lines.append(f"{I}stream_store(&mu[idx], mu_val);")
    else:  # Q — INT4 packed nibbles, block_size=32
        lines.append(f"{I}// Q state: mu is int8_t packed nibbles with block_size=32 scales")
        lines.append(f"{I}const int mu_block = idx / 32;")
        lines.append(f"{I}const int mu_byte  = idx / 2;")
        lines.append(f"{I}const int mu_nib   = idx % 2;")
        lines.append(f"{I}float mu_scale = mu_scales[mu_block];")
        lines.append(f"{I}uint8_t mu_packed = static_cast<uint8_t>(mu_q[mu_byte]);")
        lines.append(f"{I}int mu_raw = mu_nib ? ((mu_packed >> 4) & 0x0F) : (mu_packed & 0x0F);")
        lines.append(f"{I}float mu_val = static_cast<float>(mu_raw - 8) * mu_scale;")
        lines.append(f"{I}mu_val = alpha * mu_val + (1.0f - alpha) * g;")
        lines.append(f"{I}// Stochastic round mu back to INT4")
        lines.append(f"{I}unsigned mu_rng = hash_prng(idx + global_step * 6271u);")
        lines.append(f"{I}int mu_q_new = float_to_int8_stochastic(mu_val / fmaxf(mu_scale, 1e-12f), mu_rng);")
        lines.append(f"{I}mu_q_new = max(-8, min(7, mu_q_new));")
        lines.append(f"{I}uint8_t mu_byte_old = static_cast<uint8_t>(mu_q[mu_byte]);")
        lines.append(f"{I}if (mu_nib)")
        lines.append(f"{I}    mu_q[mu_byte] = static_cast<int8_t>((mu_byte_old & 0x0F) | (((mu_q_new + 8) & 0x0F) << 4));")
        lines.append(f"{I}else")
        lines.append(f"{I}    mu_q[mu_byte] = static_cast<int8_t>((mu_byte_old & 0xF0) | ((mu_q_new + 8) & 0x0F));")
    lines.append("")

    # Step 6: effective grad + Adam
    lines.append(f"{I}// ── Step 6: Adam update ──")
    lines.append(f"{I}float fg = smart_grad + lamb_eff * mu_val;")

    if state == "F":
        lines.append(f"{I}float ea = stream_load(&exp_avg[idx]);")
        lines.append(f"{I}float easq = stream_load(&exp_avg_sq[idx]);")
        lines.append(f"{I}ea = beta1 * ea + (1.0f - beta1) * fg;")
        lines.append(f"{I}easq = beta2 * easq + (1.0f - beta2) * fg * fg;")
        lines.append(f"{I}stream_store(&exp_avg[idx], ea);")
        lines.append(f"{I}stream_store(&exp_avg_sq[idx], easq);")
    else:  # Q — INT8 block8
        lines.append(f"{I}// Q state: exp_avg/exp_avg_sq are int8 block_size=8")
        lines.append(f"{I}const int ea_block = idx / 8;")
        lines.append(f"{I}float ea_scale = exp_avg_scales[ea_block];")
        lines.append(f"{I}float easq_scale = exp_avg_sq_scales[ea_block];")
        lines.append(f"{I}float ea = static_cast<float>(exp_avg_q[idx]) * ea_scale;")
        lines.append(f"{I}float easq = static_cast<float>(exp_avg_sq_q[idx]) * easq_scale;")
        lines.append(f"{I}ea = beta1 * ea + (1.0f - beta1) * fg;")
        lines.append(f"{I}easq = beta2 * easq + (1.0f - beta2) * fg * fg;")
        lines.append(f"{I}unsigned ea_rng = hash_prng(idx * 2u + global_step * 3571u);")
        lines.append(f"{I}unsigned easq_rng = hash_prng(idx * 2u + 1u + global_step * 3571u);")
        lines.append(f"{I}exp_avg_q[idx] = static_cast<int8_t>(float_to_int8_stochastic(ea / fmaxf(ea_scale, 1e-12f), ea_rng));")
        lines.append(f"{I}exp_avg_sq_q[idx] = static_cast<int8_t>(float_to_int8_stochastic(easq / fmaxf(easq_scale, 1e-12f), easq_rng));")

    lines.append("")
    lines.append(f"{I}float step_size = lr / bc1;")
    lines.append(f"{I}float denom = sqrtf(easq / bc2) + eps;")
    lines.append(f"{I}float p_val = static_cast<float>(param[idx]);")
    lines.append(f"{I}p_val = p_val * (1.0f - lr * wd_eff) - step_size * ea / denom;")
    lines.append(f"{I}param[idx] = static_cast<scalar_t>(p_val);")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
#  Full kernel generators
# ---------------------------------------------------------------------------

def gen_fused_elem_kernel(state, expert, hw, moe, d16):
    """Generate a complete fused_elem kernel with real compute."""
    kname = fused_elem_kernel_name(state, expert, hw, moe, d16)
    L = []

    # Template line
    if d16:
        L.append(f"template <typename scalar_t, int D_INNER = 16>")
    else:
        L.append(f"template <typename scalar_t>")

    L.append(f"__launch_bounds__(256, 2)")
    L.append(f"__global__ void {kname}(")

    # Parameters
    params = []
    params.append("    scalar_t* __restrict__ param")
    params.append("    const scalar_t* __restrict__ grad")
    params.append("    const scalar_t* __restrict__ sharpness")
    for p in state_params(state):
        params.append(f"    {p}")
    params.append("    const float* __restrict__ fwd_scan_out")
    params.append("    const float* __restrict__ bwd_scan_out")
    params.append("    const float* __restrict__ out_proj_fwd_W")
    params.append("    const float* __restrict__ out_proj_bwd_W")
    params.append("    const float* __restrict__ gru_Wz, const float* __restrict__ gru_bz")
    params.append("    const float* __restrict__ gru_Wr, const float* __restrict__ gru_br")
    params.append("    const float* __restrict__ gru_Wh, const float* __restrict__ gru_bh")
    params.append("    const float* __restrict__ peer_query_Ws")
    params.append("    const float* __restrict__ prod_keys_A")
    params.append("    const float* __restrict__ prod_keys_B")
    for p in expert_params(expert):
        params.append(f"    {p}")
    params.append("    const float rescale, const float alpha, const float lamb_eff")
    params.append("    const float beta1, const float beta2, const float lr")
    params.append("    const float wd_eff, const float eps, const float bc1, const float bc2")
    if state == "Q":
        params.append("    const unsigned global_step")
    if moe == "M":
        params.append("    const bool* __restrict__ active_mask")
    params.append("    int* __restrict__ expert_counts")
    if d16:
        params.append("    const int N, const int d_model")
    else:
        params.append("    const int N, const int d_model, const int d_inner")
    params.append("    const int gru_hidden, const int num_heads, const int pk_dim")
    params.append("    const int expert_hidden, const int num_experts")

    L.append(",\n".join(params))
    L.append(") {")

    # Body
    L.append(gen_smem_layout(d16))
    L.append("")
    L.append(gen_outproj_gru_load(hw))
    L.append("")
    L.append(gen_expert_load(expert, hw))
    L.append("")
    L.append("    // Per-element processing")
    L.append("    const int idx = blockIdx.x * blockDim.x + threadIdx.x;")
    L.append("    if (idx >= N) return;")
    L.append("")
    L.append(gen_compute_steps_1_to_4(state, moe, d16))
    L.append(gen_steps_5_6_adam(state))
    L.append("}")
    L.append("")

    return "\n".join(L)


def gen_launcher_fused(state, expert, hw, moe, d16):
    """Generate launcher wrapper for a fused_elem kernel."""
    kname = fused_elem_kernel_name(state, expert, hw, moe, d16)
    lname = launcher_name(kname)
    L = []
    L.append(f"void {lname}(")

    tparams = []
    tparams.append("    torch::Tensor param")
    tparams.append("    torch::Tensor grad")
    tparams.append("    torch::Tensor sharpness")
    if state == "F":
        tparams.extend(["    torch::Tensor exp_avg", "    torch::Tensor exp_avg_sq",
                         "    torch::Tensor mu", "    torch::Tensor gru_state"])
    else:
        tparams.extend(["    torch::Tensor exp_avg_q", "    torch::Tensor exp_avg_scales",
                         "    torch::Tensor exp_avg_sq_q", "    torch::Tensor exp_avg_sq_scales",
                         "    torch::Tensor mu_q", "    torch::Tensor mu_scales",
                         "    torch::Tensor gru_state"])
    tparams.extend(["    torch::Tensor fwd_scan_out", "    torch::Tensor bwd_scan_out"])
    tparams.append("    float rescale, float alpha, float lamb_eff")
    tparams.append("    float beta1, float beta2, float lr")
    tparams.append("    float wd_eff, float eps, float bc1, float bc2")
    if state == "Q":
        tparams.append("    unsigned global_step")
    if moe == "M":
        tparams.append("    torch::Tensor active_mask")
    tparams.append("    int d_model, int d_inner")
    tparams.append("    int gru_hidden, int num_heads, int pk_dim")
    tparams.append("    int expert_hidden, int num_experts")

    L.append(",\n".join(tparams))
    L.append(") {")
    L.append("    const int N = grad.numel();")
    L.append("    if (N == 0) return;")
    L.append("    const int grid = (N + 256 - 1) / 256;")

    d_inner_ref = "16" if d16 else "d_inner"
    L.append(f"    const int op_size = d_model * {d_inner_ref};")
    L.append(f"    const int gru_input_dim = 2 + 2 * d_model;")
    L.append(f"    const int gru_row_len = gru_input_dim + gru_hidden;")
    L.append(f"    const int gru_mat_size = gru_hidden * gru_row_len;")
    L.append(f"    const size_t smem_bytes = (2*op_size + 3*gru_mat_size + 3*gru_hidden")
    L.append(f"        + 3*num_experts*expert_hidden + num_experts) * sizeof(float);")
    L.append(f"    // Launch kernel (dispatch omitted — caller instantiates template)")
    L.append(f"    (void)grid; (void)smem_bytes;")
    L.append("}")
    L.append("")

    return "\n".join(L)


def gen_meta_kernel(expert, hw, moe, d16):
    """Generate a meta-net-only kernel (steps 1-4, no Adam)."""
    kname = meta_kernel_name(expert, hw, moe, d16)
    L = []

    if d16:
        L.append(f"template <typename scalar_t, int D_INNER = 16>")
    else:
        L.append(f"template <typename scalar_t>")

    L.append(f"__launch_bounds__(256, 2)")
    L.append(f"__global__ void {kname}(")

    params = []
    params.append("    const scalar_t* __restrict__ grad")
    params.append("    const scalar_t* __restrict__ sharpness")
    params.append("    float* __restrict__ gru_state")
    params.append("    float* __restrict__ smart_grad_out")
    params.append("    const float* __restrict__ fwd_scan_out")
    params.append("    const float* __restrict__ bwd_scan_out")
    params.append("    const float* __restrict__ out_proj_fwd_W")
    params.append("    const float* __restrict__ out_proj_bwd_W")
    params.append("    const float* __restrict__ gru_Wz, const float* __restrict__ gru_bz")
    params.append("    const float* __restrict__ gru_Wr, const float* __restrict__ gru_br")
    params.append("    const float* __restrict__ gru_Wh, const float* __restrict__ gru_bh")
    params.append("    const float* __restrict__ peer_query_Ws")
    params.append("    const float* __restrict__ prod_keys_A")
    params.append("    const float* __restrict__ prod_keys_B")
    for p in expert_params(expert):
        params.append(f"    {p}")
    params.append("    const float rescale")
    if moe == "M":
        params.append("    const bool* __restrict__ active_mask")
    params.append("    int* __restrict__ expert_counts")
    if d16:
        params.append("    const int N, const int d_model")
    else:
        params.append("    const int N, const int d_model, const int d_inner")
    params.append("    const int gru_hidden, const int num_heads, const int pk_dim")
    params.append("    const int expert_hidden, const int num_experts")

    L.append(",\n".join(params))
    L.append(") {")

    L.append(gen_smem_layout(d16))
    L.append("")
    L.append(gen_outproj_gru_load(hw))
    L.append("")
    L.append(gen_expert_load(expert, hw))
    L.append("")
    L.append("    // Per-element processing")
    L.append("    const int idx = blockIdx.x * blockDim.x + threadIdx.x;")
    L.append("    if (idx >= N) return;")
    L.append("")
    # Meta uses F state (gru_state is float*) for steps 1-4
    L.append(gen_compute_steps_1_to_4("F", moe, d16))
    L.append("    // Meta-net output: write smart gradient, no Adam")
    L.append("    smart_grad_out[idx] = smart_grad;")
    L.append("}")
    L.append("")

    return "\n".join(L)


def gen_launcher_meta(expert, hw, moe, d16):
    kname = meta_kernel_name(expert, hw, moe, d16)
    lname = launcher_name(kname)
    L = []
    L.append(f"void {lname}(")
    tparams = []
    tparams.append("    torch::Tensor grad")
    tparams.append("    torch::Tensor sharpness")
    tparams.append("    torch::Tensor gru_state")
    tparams.append("    torch::Tensor smart_grad_out")
    tparams.append("    torch::Tensor fwd_scan_out")
    tparams.append("    torch::Tensor bwd_scan_out")
    tparams.append("    float rescale")
    if moe == "M":
        tparams.append("    torch::Tensor active_mask")
    tparams.append("    int d_model, int d_inner")
    tparams.append("    int gru_hidden, int num_heads, int pk_dim")
    tparams.append("    int expert_hidden, int num_experts")
    L.append(",\n".join(tparams))
    L.append(") {")
    L.append("    const int N = grad.numel();")
    L.append("    if (N == 0) return;")
    L.append("    const int grid = (N + 256 - 1) / 256;")
    d_inner_ref = "16" if d16 else "d_inner"
    L.append(f"    const int op_size = d_model * {d_inner_ref};")
    L.append(f"    const int gru_input_dim = 2 + 2 * d_model;")
    L.append(f"    const int gru_row_len = gru_input_dim + gru_hidden;")
    L.append(f"    const int gru_mat_size = gru_hidden * gru_row_len;")
    L.append(f"    const size_t smem_bytes = (2*op_size + 3*gru_mat_size + 3*gru_hidden")
    L.append(f"        + 3*num_experts*expert_hidden + num_experts) * sizeof(float);")
    L.append(f"    (void)grid; (void)smem_bytes;")
    L.append("}")
    L.append("")
    return "\n".join(L)


def gen_pscan_kernel(state, hw, d16):
    """Generate a persistent scan fusion kernel."""
    kname = pscan_kernel_name(state, hw, d16)
    L = []

    if d16:
        L.append(f"template <typename scalar_t, int D_INNER = 16>")
    else:
        L.append(f"template <typename scalar_t>")

    L.append(f"__launch_bounds__(256, 2)")
    L.append(f"__global__ void {kname}(")

    params = []
    params.append("    scalar_t* __restrict__ param")
    params.append("    const scalar_t* __restrict__ grad")
    params.append("    const scalar_t* __restrict__ sharpness")
    for p in state_params(state):
        params.append(f"    {p}")
    # Scan-specific inputs
    params.append("    const float* __restrict__ scan_A")
    params.append("    const float* __restrict__ scan_B")
    params.append("    float* __restrict__ scan_state")
    params.append("    const float* __restrict__ out_proj_fwd_W")
    params.append("    const float* __restrict__ out_proj_bwd_W")
    params.append("    const float* __restrict__ gru_Wz, const float* __restrict__ gru_bz")
    params.append("    const float* __restrict__ gru_Wr, const float* __restrict__ gru_br")
    params.append("    const float* __restrict__ gru_Wh, const float* __restrict__ gru_bh")
    params.append("    const float* __restrict__ peer_query_Ws")
    params.append("    const float* __restrict__ prod_keys_A")
    params.append("    const float* __restrict__ prod_keys_B")
    params.append("    const float* __restrict__ expert_W1")
    params.append("    const float* __restrict__ expert_b1")
    params.append("    const float* __restrict__ expert_W2")
    params.append("    const float* __restrict__ expert_b2")
    params.append("    const float rescale, const float alpha, const float lamb_eff")
    params.append("    const float beta1, const float beta2, const float lr")
    params.append("    const float wd_eff, const float eps, const float bc1, const float bc2")
    if state == "Q":
        params.append("    const unsigned global_step")
    params.append("    int* __restrict__ expert_counts")
    if d16:
        params.append("    const int N, const int d_model")
    else:
        params.append("    const int N, const int d_model, const int d_inner")
    params.append("    const int gru_hidden, const int num_heads, const int pk_dim")
    params.append("    const int expert_hidden, const int num_experts")

    L.append(",\n".join(params))
    L.append(") {")

    d_inner_ref = "D_INNER" if d16 else "d_inner"
    L.append(gen_smem_layout(d16))
    L.append("")
    L.append(gen_outproj_gru_load(hw))
    L.append("")
    L.append(gen_expert_load("fp32", hw))
    L.append("")

    I = "    "
    # Persistent scan: sequential over timesteps within the block
    L.append(f"{I}// ── Persistent scan: fuse scan + unsort + fused_elem ──")
    L.append(f"{I}const int tid_elem = blockIdx.x * blockDim.x + threadIdx.x;")
    L.append(f"{I}if (tid_elem >= N) return;")
    L.append(f"{I}const int idx = tid_elem;")
    L.append(f"")
    L.append(f"{I}// Inline scan: h_t = A_t * h_{{t-1}} + B_t")
    L.append(f"{I}float scan_h = stream_load(&scan_state[idx % {d_inner_ref}]);")
    L.append(f"{I}float a_val = scan_A[idx];")
    L.append(f"{I}float b_val = scan_B[idx];")
    L.append(f"{I}scan_h = a_val * scan_h + b_val;")
    L.append(f"{I}stream_store(&scan_state[idx % {d_inner_ref}], scan_h);")
    L.append(f"")
    L.append(f"{I}// Use scan_h as both fwd and bwd scan output (single-direction variant)")
    L.append(f"{I}// For the full bidirectional case the caller runs two persistent scan kernels")
    L.append(f"{I}const float* fwd_scan_out = &scan_h;  // register-resident")
    L.append(f"{I}const float* bwd_scan_out = &scan_h;")
    L.append(f"")

    # Emit the full compute body
    L.append(gen_compute_steps_1_to_4(state, "D", d16))
    L.append(gen_steps_5_6_adam(state))
    L.append("}")
    L.append("")

    return "\n".join(L)


def gen_launcher_pscan(state, hw, d16):
    kname = pscan_kernel_name(state, hw, d16)
    lname = launcher_name(kname)
    L = []
    L.append(f"void {lname}(")
    tparams = []
    tparams.append("    torch::Tensor param")
    tparams.append("    torch::Tensor grad")
    tparams.append("    torch::Tensor sharpness")
    if state == "F":
        tparams.extend(["    torch::Tensor exp_avg", "    torch::Tensor exp_avg_sq",
                         "    torch::Tensor mu", "    torch::Tensor gru_state"])
    else:
        tparams.extend(["    torch::Tensor exp_avg_q", "    torch::Tensor exp_avg_scales",
                         "    torch::Tensor exp_avg_sq_q", "    torch::Tensor exp_avg_sq_scales",
                         "    torch::Tensor mu_q", "    torch::Tensor mu_scales",
                         "    torch::Tensor gru_state"])
    tparams.extend(["    torch::Tensor scan_A", "    torch::Tensor scan_B", "    torch::Tensor scan_state"])
    tparams.append("    float rescale, float alpha, float lamb_eff")
    tparams.append("    float beta1, float beta2, float lr")
    tparams.append("    float wd_eff, float eps, float bc1, float bc2")
    if state == "Q":
        tparams.append("    unsigned global_step")
    tparams.append("    int d_model, int d_inner")
    tparams.append("    int gru_hidden, int num_heads, int pk_dim")
    tparams.append("    int expert_hidden, int num_experts")
    L.append(",\n".join(tparams))
    L.append(") {")
    L.append("    const int N = grad.numel();")
    L.append("    if (N == 0) return;")
    L.append("    const int grid = (N + 256 - 1) / 256;")
    d_inner_ref = "16" if d16 else "d_inner"
    L.append(f"    const int op_size = d_model * {d_inner_ref};")
    L.append(f"    const int gru_input_dim = 2 + 2 * d_model;")
    L.append(f"    const int gru_row_len = gru_input_dim + gru_hidden;")
    L.append(f"    const int gru_mat_size = gru_hidden * gru_row_len;")
    L.append(f"    const size_t smem_bytes = (2*op_size + 3*gru_mat_size + 3*gru_hidden")
    L.append(f"        + 3*num_experts*expert_hidden + num_experts) * sizeof(float);")
    L.append(f"    (void)grid; (void)smem_bytes;")
    L.append("}")
    L.append("")
    return "\n".join(L)


# ---------------------------------------------------------------------------
#  Variant enumeration
# ---------------------------------------------------------------------------

def enumerate_fused_elem_variants():
    """All fused_elem variants across 5 axes."""
    variants = []
    for state, expert, hw, moe, d16 in itertools.product(
        STATES, EXPERTS, HW_OPTS, MOE_OPTS, D16_OPTS
    ):
        variants.append((state, expert, hw, moe, d16))
    return variants


def enumerate_meta_variants():
    """16 meta-net-only variants.

    Dense: (FP32,INT8) x (generic,sm80) x (no,yes) = 8
         + MXFP4 x generic x (no,yes) = 2 => 10 dense
    MoE:  (FP32,INT8) x (generic,sm80) x no_d16 = 4
         + MXFP4 x generic x (no,yes) = 2 => 6 MoE
    Total = 16
    """
    variants = []
    # Dense variants
    for expert, hw, d16 in itertools.product(EXPERTS, HW_OPTS, D16_OPTS):
        if expert == "mxfp4" and hw == "sm80":
            continue  # MXFP4 only generic
        variants.append((expert, hw, "D", d16))
    # MoE variants to reach 16
    for expert, hw in itertools.product(["fp32", "int8"], HW_OPTS):
        variants.append((expert, hw, "M", False))
    # MXFP4 MoE generic
    for d16 in D16_OPTS:
        variants.append(("mxfp4", "generic", "M", d16))
    return variants


def enumerate_pscan_variants():
    """7 persistent scan fusion variants.

    State(F/Q) x HW(generic/sm80) x d16(no/yes) = 2*2*2 = 8
    Minus the base (F_generic_no_d16) = 7
    """
    variants = []
    for state, hw, d16 in itertools.product(STATES, HW_OPTS, D16_OPTS):
        if state == "F" and hw == "generic" and not d16:
            continue  # already exists in supergrok2_mamba_peer_kernels.cu
        variants.append((state, hw, d16))
    return variants


# ---------------------------------------------------------------------------
#  File writers
# ---------------------------------------------------------------------------

def write_fused_elem_file(output_dir):
    """Write sg2_fused_elem_generated.cu with all fused_elem variants."""
    variants = enumerate_fused_elem_variants()
    path = output_dir / "sg2_fused_elem_generated.cu"

    with open(path, "w") as f:
        f.write(FILE_HEADER)
        f.write(f"// {len(variants)} SG2 fused_elem kernel variants\n")
        f.write(f"// Axes: State(F/Q) x Expert(fp32/int8/mxfp4) x HW(generic/sm80) x MoE(D/M) x d16\n\n")

        for state, expert, hw, moe, d16 in variants:
            kname = fused_elem_kernel_name(state, expert, hw, moe, d16)
            tag = f"{state}/{expert}/{hw}/{moe}"
            if d16:
                tag += "/d16"
            f.write(f"// {'=' * 59}\n")
            f.write(f"//  {kname}  [{tag}]\n")
            f.write(f"// {'=' * 59}\n\n")
            f.write(gen_fused_elem_kernel(state, expert, hw, moe, d16))
            f.write("\n")
            f.write(gen_launcher_fused(state, expert, hw, moe, d16))
            f.write("\n")

    return len(variants), path


def write_meta_file(output_dir):
    """Write sg2_metanet_only_generated.cu."""
    variants = enumerate_meta_variants()
    path = output_dir / "sg2_metanet_only_generated.cu"

    with open(path, "w") as f:
        f.write(FILE_HEADER)
        f.write(f"// {len(variants)} SG2 meta-net-only async kernel variants\n")
        f.write(f"// Steps 1-4 only (no Adam). Output: smart_grad_out buffer.\n\n")

        for expert, hw, moe, d16 in variants:
            kname = meta_kernel_name(expert, hw, moe, d16)
            tag = f"{expert}/{hw}/{moe}"
            if d16:
                tag += "/d16"
            f.write(f"// {'=' * 59}\n")
            f.write(f"//  {kname}  [{tag}]\n")
            f.write(f"// {'=' * 59}\n\n")
            f.write(gen_meta_kernel(expert, hw, moe, d16))
            f.write("\n")
            f.write(gen_launcher_meta(expert, hw, moe, d16))
            f.write("\n")

    return len(variants), path


def write_pscan_file(output_dir):
    """Write sg2_persistent_scan_generated.cu."""
    variants = enumerate_pscan_variants()
    path = output_dir / "sg2_persistent_scan_generated.cu"

    with open(path, "w") as f:
        f.write(FILE_HEADER)
        f.write(f"// {len(variants)} persistent scan fusion kernel variants\n")
        f.write(f"// Fuses scan + unsort + fused_elem into one kernel.\n\n")

        for state, hw, d16 in variants:
            kname = pscan_kernel_name(state, hw, d16)
            tag = f"{state}/{hw}"
            if d16:
                tag += "/d16"
            f.write(f"// {'=' * 59}\n")
            f.write(f"//  {kname}  [{tag}]\n")
            f.write(f"// {'=' * 59}\n\n")
            f.write(gen_pscan_kernel(state, hw, d16))
            f.write("\n")
            f.write(gen_launcher_pscan(state, hw, d16))
            f.write("\n")

    return len(variants), path


# ---------------------------------------------------------------------------
#  Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Generate SG2 fused_elem, meta-net, and persistent scan CUDA kernels"
    )
    parser.add_argument(
        "--output",
        type=str,
        default=str(DEFAULT_OUTPUT),
        help="Output directory for generated .cu files",
    )
    args = parser.parse_args()

    output_dir = Path(args.output).resolve()
    os.makedirs(output_dir, exist_ok=True)

    print(f"SG2 Kernel Code Generator")
    print(f"Output directory: {output_dir}")
    print()

    n_fused, p_fused = write_fused_elem_file(output_dir)
    n_meta, p_meta = write_meta_file(output_dir)
    n_pscan, p_pscan = write_pscan_file(output_dir)

    print(f"Generated files:")
    print(f"  {p_fused.name:<45s}  ({n_fused} kernels)")
    print(f"  {p_meta.name:<45s}  ({n_meta} kernels)")
    print(f"  {p_pscan.name:<45s}  ({n_pscan} kernels)")
    print(f"  Total: {n_fused + n_meta + n_pscan} kernels")


if __name__ == "__main__":
    main()
