"""tests/hw/test_parallel_instantiation.py — Phase-2 template-instantiation gate.

IMPLEMENTS /workspace/.parallelism_design.md §7.2 (the cheapest, highest-leverage
pre-work): the build instantiates a FIXED ALLOW-LIST of ``ParConfig`` points (the
only ones ``dispatch.cpp`` can route to). This test asserts every allow-listed
point COMPILES (``nvcc -c`` only — no GPU, no run), front-loading every
``if constexpr`` / ABI breakage in ``parallel_config.cuh`` BEFORE the 8×H100
rental window.

The allow-list is the campaign's real points (design §7.2):

    <SingleGPU>            -- the bit-identical baseline (PTX-diff gated, §1.2)
    <8,1,1,1,Z2>          -- DP8 + ZeRO-2  (increment 1)
    <8,1,1,1,Z3>          -- DP8 + ZeRO-3  (increment 2)
    <4,1,2,1,Z3>          -- + PP2         (increment 3)
    <2,4,1,1,Z3>          -- + TP4         (increment 4, frontier)

CPU-ONLY. This test only INVOKES nvcc on a tiny generated harness ``.cu`` that
includes ``parallel_config.cuh`` and ``static_assert``s the derived flags of each
point. It compiles to ``-o /dev/null`` (no run, no link, no device execution), so
it is green on any box with a CUDA toolchain — including this single-GPU host.

SUITE SAFETY (matches tests/hw/test_3d_parallel.py's discipline):
  * imports cleanly with no GPU and no nvcc;
  * SKIPS (never fails/errors) when ``nvcc`` is absent, so a CPU/CI box without a
    CUDA toolchain stays green;
  * writes its scratch ``.cu`` / ``.o`` under a temp dir, never into the repo.

Run:
    pytest tests/hw/test_parallel_instantiation.py -q
"""

from __future__ import annotations

import os
import shutil
import subprocess
import tempfile
from typing import List, Optional, Tuple

try:  # pragma: no cover - trivial import guard (file is also runnable as a script)
    import pytest
except Exception:  # pragma: no cover
    pytest = None  # type: ignore[assignment]


# ─────────────────────────────── repo / toolchain probes ─────────────────────

# tests/hw/<this file>  →  repo root is two dirs up.
_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
_PARALLEL_CONFIG = os.path.join(
    _REPO_ROOT, "csrc", "fused", "sm_90", "parallel_config.cuh"
)


def _nvcc() -> Optional[str]:
    """Absolute path to nvcc, or None if no CUDA toolchain is visible."""
    return shutil.which("nvcc")


def _skip_reason() -> Optional[str]:
    """Return a skip reason, or None if the compile gate can really run."""
    if _nvcc() is None:
        return "nvcc not on PATH — template-instantiation gate is toolchain-deferred"
    if not os.path.isfile(_PARALLEL_CONFIG):
        return f"parallel_config.cuh missing at {_PARALLEL_CONFIG}"
    return None


# ─────────────────────────────── the allow-list (§7.2) ───────────────────────
# (name, DP, TP, PP, SP, ZeROStage-enumerator, EP). SP is pinned 1 (design §1.1);
# EP defaults to 1 (the dense, byte-identical trailing-default — adaptive_parallelism.md §2).
ALLOW_LIST: List[Tuple[str, int, int, int, int, str, int]] = [
    ("SingleGPU", 1, 1, 1, 1, "Z0", 1),  # bit-identical baseline (§1.2)
    ("DP8_ZeRO2", 8, 1, 1, 1, "Z2", 1),  # increment 1
    ("DP8_ZeRO3", 8, 1, 1, 1, "Z3", 1),  # increment 2
    ("DP4_PP2_ZeRO3", 4, 1, 2, 1, "Z3", 1),  # increment 3 (+PP)
    ("DP2_TP4_ZeRO3", 2, 4, 1, 1, "Z3", 1),  # increment 4 (+TP, frontier)
    ("DP1_TP1_EP8_ZeRO3", 1, 1, 1, 1, "Z3", 8),  # increment 5 (+EP, MoE frontier)
]


def _expected_flags(dp: int, tp: int, pp: int, sp: int, zero: str, ep: int = 1) -> List[str]:
    """The derived ParConfig predicates each point MUST satisfy (design §1.1).

    These mirror the constexpr derivations in parallel_config.cuh, so the harness
    static_asserts both that the point compiles AND that its gates fold to the
    right values (a typo in the header's derivation fails the build loudly). EP
    folds into kIsSingleGPU/kEmitComm and drives kEPComm (adaptive_parallelism.md §2).
    """
    is_single = dp == 1 and tp == 1 and pp == 1 and sp == 1 and ep == 1
    zero_rank = {"Z0": 0, "Z1": 1, "Z2": 2, "Z3": 3}[zero]
    return [
        f"P::kDP == {dp}",
        f"P::kTP == {tp}",
        f"P::kPP == {pp}",
        f"P::kSP == {sp}",
        f"P::kEP == {ep}",
        f"P::kIsSingleGPU == {'true' if is_single else 'false'}",
        f"P::kEmitComm == {'false' if is_single else 'true'}",
        f"P::kShardParams == {'true' if zero_rank == 3 else 'false'}",
        f"P::kShardOptGrad == {'true' if zero_rank >= 2 else 'false'}",
        f"P::kTPComm == {'true' if tp > 1 else 'false'}",
        f"P::kPPStage == {'true' if pp > 1 else 'false'}",
        f"P::kEPComm == {'true' if ep > 1 else 'false'}",
    ]


def _emit_harness(points: List[Tuple[str, int, int, int, int, str, int]]) -> str:
    """Generate the minimal harness .cu source for the given allow-list points."""
    lines = [
        "// AUTO-GENERATED by tests/hw/test_parallel_instantiation.py (design §7.2).",
        "// Minimal harness: include parallel_config.cuh and static_assert the",
        "// derived gates of every allow-listed ParConfig point. nvcc -c only.",
        '#include "csrc/fused/sm_90/parallel_config.cuh"',
        "namespace par = ::sg::fused::par;",
    ]
    for (name, dp, tp, pp, sp, zero, ep) in points:
        # EP==1 emits the 5-arg template (the trailing default — proves the legacy
        # point is byte-compatible); EP>1 emits the explicit 6-arg template.
        if ep == 1:
            tmpl = f"par::ParConfig<{dp},{tp},{pp},{sp}, par::ZeROStage::{zero}>"
        else:
            tmpl = f"par::ParConfig<{dp},{tp},{pp},{sp}, par::ZeROStage::{zero}, {ep}>"
        lines.append(f"using P_{name} = {tmpl};")
        for flag in _expected_flags(dp, tp, pp, sp, zero, ep):
            expr = flag.replace("P::", f"P_{name}::")
            lines.append(f'static_assert({expr}, "{name}: {flag}");')
    # SingleGPU must be exactly ParConfig<1,1,1,1,Z0> (the named alias).
    lines.append(
        'static_assert(par::SingleGPU::kIsSingleGPU, "SingleGPU alias must be single-GPU");'
    )
    # The EP default must be 1: a 5-arg point must equal the same point with EP=1.
    lines.append(
        'static_assert(par::ParConfig<1,1,1,1,par::ZeROStage::Z0>::kEP == 1, '
        '"EP must default to 1 (dense) for the legacy 5-arg point");'
    )
    lines.append(
        'static_assert(par::ParConfig<1,1,1,1,par::ZeROStage::Z0>::kEPComm == false, '
        '"EP=1 must fold kEPComm to false (byte-identical dense path)");'
    )
    lines.append("int main() { return 0; }")
    return "\n".join(lines) + "\n"


def _compile(cu_path: str, out_path: str) -> subprocess.CompletedProcess:
    """nvcc -c the harness with the repo-root include (design's repo-relative
    include convention) for sm_90a. No torch include needed: parallel_config.cuh
    is pure C++/constexpr (only <cstdint>)."""
    nvcc = _nvcc()
    assert nvcc is not None
    cmd = [
        nvcc, "-c", "-std=c++17",
        "-gencode", "arch=compute_90a,code=sm_90a",
        "-I", _REPO_ROOT,
        cu_path, "-o", out_path,
    ]
    return subprocess.run(cmd, cwd=_REPO_ROOT, capture_output=True, text=True)


# ──────────────────────────────────── tests ──────────────────────────────────


def _maybe_skip():
    reason = _skip_reason()
    if reason is not None:
        if pytest is not None:
            pytest.skip(reason)
        else:  # pragma: no cover - non-pytest path
            raise SystemExit(0)


def test_allow_list_points_compile():
    """Every allow-listed ParConfig point compiles (design §7.2, full set)."""
    _maybe_skip()
    src = _emit_harness(ALLOW_LIST)
    with tempfile.TemporaryDirectory() as td:
        cu = os.path.join(td, "parallel_instantiation_harness.cu")
        obj = os.path.join(td, "parallel_instantiation_harness.o")
        with open(cu, "w") as f:
            f.write(src)
        proc = _compile(cu, obj)
        assert proc.returncode == 0, (
            "ParConfig allow-list failed to compile (design §7.2):\n"
            f"--- stderr ---\n{proc.stderr}\n--- source ---\n{src}"
        )
        assert os.path.isfile(obj), "nvcc reported success but produced no object"


def test_each_point_compiles_in_isolation():
    """Each point also compiles ALONE — isolates which point breaks if one does."""
    _maybe_skip()
    with tempfile.TemporaryDirectory() as td:
        for point in ALLOW_LIST:
            name = point[0]
            src = _emit_harness([point])
            cu = os.path.join(td, f"pi_{name}.cu")
            obj = os.path.join(td, f"pi_{name}.o")
            with open(cu, "w") as f:
                f.write(src)
            proc = _compile(cu, obj)
            assert proc.returncode == 0, (
                f"ParConfig point {name} failed to compile in isolation:\n"
                f"{proc.stderr}\n--- source ---\n{src}"
            )


def test_sp_not_one_is_a_compile_error():
    """SP != 1 must be a LOUD build error (design §1.1 static_assert), proving the
    seq-parallel axis is gated, not silently broken."""
    _maybe_skip()
    src = (
        '#include "csrc/fused/sm_90/parallel_config.cuh"\n'
        "namespace par = ::sg::fused::par;\n"
        "using Bad = par::ParConfig<1,1,1,2, par::ZeROStage::Z0>;  // SP=2 illegal\n"
        "Bad b;\n"
        "int main() { (void)sizeof(b); return 0; }\n"
    )
    with tempfile.TemporaryDirectory() as td:
        cu = os.path.join(td, "pi_sp_bad.cu")
        obj = os.path.join(td, "pi_sp_bad.o")
        with open(cu, "w") as f:
            f.write(src)
        proc = _compile(cu, obj)
        assert proc.returncode != 0, (
            "SP=2 must NOT compile (the SP==1 static_assert is the gate)"
        )
        assert "SP axis" in (proc.stderr + proc.stdout), (
            "SP=2 failed for the wrong reason — expected the SP==1 static_assert "
            f"message, got:\n{proc.stderr}"
        )


# ─────────────────────────────────── script main ─────────────────────────────


def main() -> int:
    reason = _skip_reason()
    if reason is not None:
        print(f"[parallel-instantiation] SKIP: {reason}")
        return 0
    test_allow_list_points_compile()
    test_each_point_compiles_in_isolation()
    test_sp_not_one_is_a_compile_error()
    print(
        "[parallel-instantiation] OK: "
        f"{len(ALLOW_LIST)} ParConfig points compile; SP!=1 correctly rejected."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
