"""grokking_optimizers.megakernel_codegen — Stage 6 L3 megakernel generator.

Given the feasibility solver (``megakernel.solve_all`` / ``megakernel.solve``),
this module EMITS the per-(model × optimizer × arch) megakernel source by
instantiating the ONE templated L3 megakernel from
``csrc/fused/<arch>/megakernel_demo.{cu,hip.hpp}`` at the solver-chosen tier.

You do NOT hand-write 99 kernels: the demo TU is the structural template, and
the generator re-instantiates ``l3_megakernel<Model, Optimizer>`` (sm_90 /
gfx942) or emits the Pallas program (tpu_v5p) per cell. It can emit a single
cell's source string (``--emit <model> <optimizer> <arch>``) or report the full
99-cell manifest with tiers (``--emit-all``).

The set of cells that already have a REAL, wired fused TU (the three the demo
instantiates + dispatch.cpp routes to) is :data:`WIRED_CELLS`; every other cell
is generator-emittable but not yet compiled into the extension (the manifest
flags which is which, mirroring dispatch.cpp's honesty contract, §1.12).
"""

from __future__ import annotations

import argparse
import sys
from typing import Dict, List, Optional, Tuple

from grokking_optimizers import megakernel as mk
from grokking_optimizers.megakernel import FusionPlan, FusionTier

# ── Template ↔ enum mapping ──────────────────────────────────────────────
# The C++ demo template parameterizes on Model / Optimizer enums. The generator
# maps the solver's string identities to those enum spellings. Optimizers the
# demo template specializes elementwise are mapped directly; the rest reuse the
# nearest elementwise tail spelling and are flagged in the manifest (the real
# generator would add the template case — here the demo covers the wired set).
_MODEL_ENUM: Dict[str, str] = {
    "transformer_decoder": "TransformerDecoder",
    "vit": "ViT",
    "mamba3": "Mamba3",
}
# The optimizer-tail template cases the demo implements directly.
_OPT_ENUM: Dict[str, str] = {
    "adamw": "AdamW",
    "lion": "Lion",
    "muon": "Muon",
    "supergrok15": "SuperGrok15",
}
# Optimizers without a dedicated demo template case fall back to the nearest
# elementwise tail (the generator records the substitution in the manifest so
# the coverage is self-explaining; the production generator emits the exact
# tail). adamw is the conservative default elementwise tail.
_OPT_FALLBACK = "adamw"

# Cells whose megakernel is actually instantiated in a demo TU AND routed by
# dispatch.cpp::fused_step. These are the only cells fused_step dispatches to.
# Today the dispatch routes the sm_90 cells (the .cu TU is compiled into the
# CUDA extension); the gfx942 twins are gate-verified headers pending a hipcc
# .hip TU on MI300X (🟡), so they are emittable but not yet routed. The manifest
# marks wired=True only for an arch where dispatch.cpp really routes the cell.
# (Mirror of dispatch.cpp::wired_fused_cell.)
WIRED_CELLS: Tuple[Tuple[str, str, str], ...] = (
    ("mamba3", "adamw", "sm_90"),
    ("transformer_decoder", "lion", "sm_90"),
    ("vit", "supergrok15", "sm_90"),
)


def _opt_enum(optimizer: str) -> Tuple[str, bool]:
    """Return (enum_spelling, is_exact). is_exact is False when the optimizer
    has no dedicated demo template case and reuses a fallback tail."""
    if optimizer in _OPT_ENUM:
        return _OPT_ENUM[optimizer], True
    return _OPT_ENUM[_OPT_FALLBACK], False


def _cell_symbol(model: str, optimizer: str) -> str:
    """The non-templated host-launcher symbol name for a cell."""
    return f"mega_{model}_{optimizer}"


# ── Per-arch source emission ─────────────────────────────────────────────

def _emit_cuda(plan: FusionPlan) -> str:
    """Emit the sm_90 .cu source for a cell: it includes the demo template and
    instantiates l3_megakernel<Model, Optimizer> + the host launcher symbol."""
    m_enum = _MODEL_ENUM[plan.model]
    o_enum, exact = _opt_enum(plan.optimizer)
    sym = _cell_symbol(plan.model, plan.optimizer)
    note = "" if exact else (
        f"\n// NOTE: optimizer '{plan.optimizer}' has no dedicated demo tail; "
        f"instantiated with the '{_OPT_FALLBACK}' elementwise tail as a "
        f"structural placeholder (production generator emits the exact tail).")
    wired = (plan.model, plan.optimizer, plan.arch) in WIRED_CELLS
    wired_note = (
        "\n// This cell is ALREADY wired in the canonical demo TU "
        "(megakernel_demo.cu);\n// the generator would normally SKIP emitting it "
        "to disk. Shown here for\n// completeness — the launcher below is named "
        "distinctly to avoid a clash.") if wired else ""
    return f"""// csrc/fused/sm_90/{sym}.cu  — GENERATED by megakernel_codegen.py
// Cell: ({plan.model}, {plan.optimizer}, {plan.arch})  tier={plan.tier.name}
//   regs={plan.regs}/{plan.budget_regs}  smem={plan.smem}/{plan.budget_smem}
//   {plan.note or 'fits L3'}{note}{wired_note}
//
// Instantiates the ONE templated L3 persistent megakernel for this (model,
// optimizer). SG_MEGAKERNEL_DEMO_TEMPLATE_ONLY pulls in JUST the template
// machinery (scheduler/barrier substrate, SM-pinning, fused-optimizer tail —
// all comdat-folded across TUs); this TU adds only its own unique launcher.
#define SG_MEGAKERNEL_DEMO_TEMPLATE_ONLY
#include "csrc/fused/sm_90/megakernel_demo.cu"

namespace sg {{ namespace fused {{ namespace sm90 {{

cudaError_t {sym}(
        PersistentContext ctx, float* params, const float* input, float* acts,
        float* grad, float* m, float* v, const int* sizes, const int* offsets,
        float lr, int step, cudaStream_t stream) {{
    return launch_l3_megakernel<Model::{m_enum}, Optimizer::{o_enum}>(
        ctx, params, input, acts, grad, m, v, sizes, offsets, lr, step, stream);
}}

}}}}}}  // namespace sg::fused::sm90
"""


def _emit_hip(plan: FusionPlan) -> str:
    """Emit the gfx942 .hip source for a cell. Mirrors the CUDA emission but
    targets the gfx942 demo header (ping-pong/4-wave-interleave, §1.13)."""
    m_enum = _MODEL_ENUM[plan.model]
    o_enum, exact = _opt_enum(plan.optimizer)
    sym = _cell_symbol(plan.model, plan.optimizer)
    note = "" if exact else (
        f"\n// NOTE: optimizer '{plan.optimizer}' reuses the '{_OPT_FALLBACK}' "
        f"elementwise tail (structural placeholder).")
    return f"""// csrc/fused/gfx942/{sym}.hip  — GENERATED by megakernel_codegen.py
// Cell: ({plan.model}, {plan.optimizer}, {plan.arch})  tier={plan.tier.name}
//   §1.13 ping-pong / 4-wave-interleave (NOT warp-specialized).{note}
#include "csrc/fused/gfx942/megakernel_demo.hip.hpp"

namespace sg {{ namespace fused {{ namespace gfx942_mega {{

// Force this cell's kernel instantiation (host launcher wiring is added once
// the gfx942 megakernel migrates to a compiled .hip TU on MI300X, 🟡).
template __global__ void l3_megakernel<Model::{m_enum}, Optimizer::{o_enum}>(
    PersistentContext, float*, const float*, float*, float*, float*, float*,
    const int*, const int*, float, int);

}}}}}}  // namespace sg::fused::gfx942_mega
"""


def _emit_pallas(plan: FusionPlan) -> str:
    """Emit a tpu_v5p Pallas program stub for a cell. The TPU megakernel is a
    single fused XLA program (the solver reports L3, allocator-managed)."""
    return f"""# csrc/fused/tpu_v5p/{_cell_symbol(plan.model, plan.optimizer)}.py
# GENERATED by megakernel_codegen.py — cell ({plan.model}, {plan.optimizer},
# {plan.arch}), tier={plan.tier.name} (pallas: single fused program).
#
# The TPU L3 megakernel is one pl.pallas_call composing forward → backward →
# optimizer; XLA owns the allocation so the solver always reports L3. The body
# is emitted from the JAX kernel tree (grokking_optimizers/kernels/tpu_v5p).
import jax  # noqa: F401  (structural stub; production generator emits the body)
"""


def emit_cell(model: str, optimizer: str, arch: str) -> str:
    """Emit the megakernel source string for ONE (model, optimizer, arch) cell,
    at the solver-chosen tier. Raises if the solver finds the cell infeasible
    (§1.11 — no silent slow path)."""
    plan = mk.solve(model, optimizer, arch)  # raises on infeasible
    if arch == "sm_90":
        return _emit_cuda(plan)
    if arch == "gfx942":
        return _emit_hip(plan)
    if arch == "tpu_v5p":
        return _emit_pallas(plan)
    raise KeyError(f"unknown arch '{arch}' (not a megakernel target)")


# ── Manifest ─────────────────────────────────────────────────────────────

def manifest() -> List[Dict[str, object]]:
    """The full 99-cell manifest: every (model, optimizer, arch) with its
    solver tier, the template enum pair it instantiates, whether the optimizer
    tail is an exact demo case, and whether the cell is WIRED into fused_step."""
    rows: List[Dict[str, object]] = []
    for plan in mk.solve_all():
        o_enum, exact = _opt_enum(plan.optimizer)
        rows.append({
            "model": plan.model,
            "optimizer": plan.optimizer,
            "arch": plan.arch,
            "tier": plan.tier.name,
            "feasible": plan.fits,
            "model_enum": _MODEL_ENUM.get(plan.model, "?"),
            "opt_enum": o_enum,
            "opt_exact": exact,
            "wired": (plan.model, plan.optimizer, plan.arch) in WIRED_CELLS,
            "symbol": _cell_symbol(plan.model, plan.optimizer),
            "regs": plan.regs,
            "smem": plan.smem,
            "note": plan.note,
        })
    return rows


def _format_manifest(rows: List[Dict[str, object]]) -> str:
    out: List[str] = []
    out.append(f"Stage 6 megakernel manifest — {len(rows)} cells "
               f"(3 models × 11 optimizers × 3 archs)")
    # Tier coverage.
    tiers: Dict[str, int] = {}
    wired = 0
    for r in rows:
        tiers[str(r["tier"])] = tiers.get(str(r["tier"]), 0) + 1
        if r["wired"]:
            wired += 1
    out.append("  tier coverage: " +
               ", ".join(f"{k}={v}" for k, v in sorted(tiers.items())))
    out.append(f"  wired into fused_step: {wired} cell(s) "
               f"(real fused TU + dispatch route)")
    out.append("")
    out.append(f"  {'model':<20} {'optimizer':<13} {'arch':<9} "
               f"{'tier':<16} {'wired':<6} {'exact_tail':<10} note")
    out.append("  " + "-" * 96)
    for r in rows:
        out.append(
            f"  {r['model']:<20} {r['optimizer']:<13} {r['arch']:<9} "
            f"{r['tier']:<16} {'yes' if r['wired'] else '':<6} "
            f"{'yes' if r['opt_exact'] else 'fallback':<10} "
            f"{r['note'] or ''}")
    return "\n".join(out)


# ── CLI ──────────────────────────────────────────────────────────────────

def main(argv: Optional[List[str]] = None) -> int:
    ap = argparse.ArgumentParser(
        prog="megakernel_codegen",
        description="Stage 6 L3 megakernel generator (emits per-cell source).")
    ap.add_argument("--emit", nargs=3, metavar=("MODEL", "OPTIMIZER", "ARCH"),
                    help="emit ONE cell's megakernel source to stdout")
    ap.add_argument("--emit-all", action="store_true",
                    help="report the full 99-cell manifest with tiers")
    args = ap.parse_args(argv)

    if args.emit:
        model, optimizer, arch = args.emit
        try:
            sys.stdout.write(emit_cell(model, optimizer, arch))
        except (KeyError, RuntimeError) as exc:
            sys.stderr.write(f"emit failed: {exc}\n")
            return 2
        return 0

    if args.emit_all:
        sys.stdout.write(_format_manifest(manifest()) + "\n")
        return 0

    ap.print_help()
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
