# csrc/fused/tpu_v6e/mega_mamba3_looksam.py
# GENERATED by megakernel_codegen.py — cell (mamba3, looksam,
# tpu_v6e), tier=L3_FWD_BWD_OPT.
#
# REAL fused composition: binds (model=mamba3, optimizer=looksam)
# to the real fused program csrc/backends/pallas/_pallas_fused.py::fused_step,
# which composes the real TPU model fwd/bwd with the real per-optimizer TPU
# step inside one jax.jit (XLA fuses fwd->bwd->opt for L3, opt-only for L1).
# NO stub — verified via trace_check (jax.eval_shape + jit.lower).
from functools import partial

from csrc.backends.pallas._pallas_fused import fused_step, trace_check

MODEL = "mamba3"
OPTIMIZER = "looksam"
TIER = "L3"

# The fused step for this cell (model+optimizer bound; tier from the solver).
step = partial(fused_step, MODEL, OPTIMIZER, tier=TIER)


def verify():
    """Trace+lower this cell's fused program (no hardware needed)."""
    return trace_check(MODEL, OPTIMIZER, TIER)
