#ifndef SG_FUSED_SM90_DECODER_LAYOUT_CUH_
#define SG_FUSED_SM90_DECODER_LAYOUT_CUH_
// ============================================================================
// csrc/fused/sm_90/decoder_layout.cuh — GENERATED weight-layout mirror for the
// L3-REAL transformer-decoder megakernel (PHASE 1).
//
// AUTO-GENERATED by: python -m grokking_optimizers.megakernel_codegen \
//     --decoder-layout > csrc/fused/sm_90/decoder_layout.cuh
// Do NOT hand-edit the numbers. SINGLE SOURCE OF TRUTH: megakernel_codegen.py
// _decoder_param_sizes() (mirrored by tests/hw/decoder_oracle.py, asserted ==
// the eager model's named_parameters() order in the parity test). The flat blob
// is torch.cat([p.reshape(-1) for _, p in model.named_parameters()]); the kernel
// addresses tensor i at params + kDecOffsets[i] for kDecSizes[i] elements.
//
// A count/total mismatch fails the BUILD loudly (a static_assert below), never
// corrupts at dispatch.
// ============================================================================

#include <cstdint>

namespace sg { namespace fused { namespace sm90 {

constexpr int SG_DEC_VOCAB  = 99;
constexpr int SG_DEC_D      = 128;
constexpr int SG_DEC_HEADS  = 4;
constexpr int SG_DEC_LAYERS = 2;
constexpr int SG_DEC_SEQ    = 4;
constexpr int SG_DEC_DFF    = 4 * SG_DEC_D;   // 512

constexpr int     kDecNumTensors = 30;
constexpr int64_t kDecTotalElems = 422755;

// Per-tensor element offsets into the flat param blob, named_parameters() order.
__device__ __constant__ int kDecOffsets[kDecNumTensors] = {
    0, 12672, 13184, 62336, 62720, 79104, 79232, 79360, 79488, 79616,
    79744, 145280, 145792, 211328, 211456, 260608, 260992, 277376, 277504, 277632,
    277760, 277888, 278016, 343552, 344064, 409600, 409728, 409856, 409984, 422656
};

// Per-tensor element sizes (numel), same order.
__device__ __constant__ int kDecSizes[kDecNumTensors] = {
    12672, 512, 49152, 384, 16384, 128, 128, 128, 128, 128,
    65536, 512, 65536, 128, 49152, 384, 16384, 128, 128, 128,
    128, 128, 65536, 512, 65536, 128, 128, 128, 12672, 99
};

static_assert(kDecNumTensors == 30,
              "decoder_layout: tensor count drifted. Regenerate via "
              "megakernel_codegen.py --decoder-layout.");
static_assert(kDecTotalElems == 422755,
              "decoder_layout: total param count drifted. Regenerate.");

// Host-constexpr mirrors so a sum/offset cross-check folds at compile time (a
// __constant__ array can't be folded in a constexpr). These guarantee
// offsets/sizes/total agree.
namespace dec_layout_check {
constexpr int kSizes[kDecNumTensors] = {
    12672, 512, 49152, 384, 16384, 128, 128, 128, 128, 128,
    65536, 512, 65536, 128, 49152, 384, 16384, 128, 128, 128,
    128, 128, 65536, 512, 65536, 128, 128, 128, 12672, 99
};
constexpr int kOffsets[kDecNumTensors] = {
    0, 12672, 13184, 62336, 62720, 79104, 79232, 79360, 79488, 79616,
    79744, 145280, 145792, 211328, 211456, 260608, 260992, 277376, 277504, 277632,
    277760, 277888, 278016, 343552, 344064, 409600, 409728, 409856, 409984, 422656
};
constexpr int64_t sum_sizes() {
    int64_t s = 0;
    for (int i = 0; i < kDecNumTensors; ++i) s += kSizes[i];
    return s;
}
constexpr bool offsets_consistent() {
    int64_t acc = 0;
    for (int i = 0; i < kDecNumTensors; ++i) {
        if (kOffsets[i] != (int)acc) return false;
        acc += kSizes[i];
    }
    return true;
}
static_assert(sum_sizes() == kDecTotalElems,
              "decoder_layout: sum(kDecSizes) != kDecTotalElems. Regenerate.");
static_assert(offsets_consistent(),
              "decoder_layout: kDecOffsets[i] != sum(kDecSizes[0..i)). Regenerate.");
}  // namespace dec_layout_check

}}} // namespace sg::fused::sm90

#endif  // SG_FUSED_SM90_DECODER_LAYOUT_CUH_
