#ifndef SG_FUSED_SM90_DECODER_LAYOUT_CUH_
#define SG_FUSED_SM90_DECODER_LAYOUT_CUH_
// ============================================================================
// csrc/fused/sm_90/decoder_layout.cuh — GENERATED weight-layout mirror for the
// L3-REAL transformer-decoder megakernel (PHASE 1).
//
// AUTO-GENERATED by: python -m grokking_optimizers.megakernel_codegen \
//     --decoder-layout > csrc/fused/sm_90/decoder_layout.cuh
// Do NOT hand-edit the numbers. SINGLE SOURCE OF TRUTH: megakernel_codegen.py
// _decoder_param_sizes() (mirrored by tests/hw/decoder_oracle.py, asserted ==
// the eager model's named_parameters() order in the parity test). The flat blob
// is torch.cat([p.reshape(-1) for _, p in model.named_parameters()]); the kernel
// addresses tensor i at params + kDecOffsets[i] for kDecSizes[i] elements.
//
// A count/total mismatch fails the BUILD loudly (a static_assert below), never
// corrupts at dispatch.
//
// ── SG_DEC_BENCH_LAYOUT (hill-climb d-scaled bench variant) ──────────────────
// Two layouts coexist under the single include guard. SG_DEC_BENCH_LAYOUT is
// UNSET on the production _ops build (→ the d=128 branch, byte-identical to
// the historical header), and set to 1 ONLY by the d-scaled benchmark TU / the
// _ops_bench variant extension (→ the d=1024 branch). The branches are
// mutually exclusive at preprocess time, so a TU compiles exactly one consistent
// (constants, __constant__ table, static-assert) set; production never sees the
// bench numbers. This is the loop infra for task #13 — see /workspace/.hillclimb_loop.md.
// ============================================================================

#include <cstdint>

#ifndef SG_DEC_BENCH_LAYOUT
#define SG_DEC_BENCH_LAYOUT 0
#endif

namespace sg { namespace fused { namespace sm90 {

#if SG_DEC_BENCH_LAYOUT
// ── d-SCALED BENCH VARIANT (d=1024): the persistent-megakernel roofline
//    build. NOT on the production path; selected ONLY by -DSG_DEC_BENCH_LAYOUT=1. ──
constexpr int SG_DEC_VOCAB  = 99;
constexpr int SG_DEC_D      = 1024;
constexpr int SG_DEC_HEADS  = 4;
constexpr int SG_DEC_LAYERS = 2;
constexpr int SG_DEC_SEQ    = 4;
constexpr int SG_DEC_DFF    = 4 * SG_DEC_D;   // 4096

constexpr int     kDecNumTensors = 30;
constexpr int64_t kDecTotalElems = 25401443;

// Per-tensor element offsets into the flat param blob, named_parameters() order.
__device__ __constant__ int kDecOffsets[kDecNumTensors] = {
    0, 101376, 105472, 3251200, 3254272, 4302848, 4303872, 4304896, 4305920, 4306944,
    4307968, 8502272, 8506368, 12700672, 12701696, 15847424, 15850496, 16899072, 16900096, 16901120,
    16902144, 16903168, 16904192, 21098496, 21102592, 25296896, 25297920, 25298944, 25299968, 25401344
};

// Per-tensor element sizes (numel), same order.
__device__ __constant__ int kDecSizes[kDecNumTensors] = {
    101376, 4096, 3145728, 3072, 1048576, 1024, 1024, 1024, 1024, 1024,
    4194304, 4096, 4194304, 1024, 3145728, 3072, 1048576, 1024, 1024, 1024,
    1024, 1024, 4194304, 4096, 4194304, 1024, 1024, 1024, 101376, 99
};

static_assert(kDecNumTensors == 30,
              "decoder_layout: tensor count drifted. Regenerate via "
              "megakernel_codegen.py --decoder-layout.");
static_assert(kDecTotalElems == 25401443,
              "decoder_layout: total param count drifted. Regenerate.");

// Host-constexpr mirrors so a sum/offset cross-check folds at compile time (a
// __constant__ array can't be folded in a constexpr). These guarantee
// offsets/sizes/total agree.
namespace dec_layout_check {
constexpr int kSizes[kDecNumTensors] = {
    101376, 4096, 3145728, 3072, 1048576, 1024, 1024, 1024, 1024, 1024,
    4194304, 4096, 4194304, 1024, 3145728, 3072, 1048576, 1024, 1024, 1024,
    1024, 1024, 4194304, 4096, 4194304, 1024, 1024, 1024, 101376, 99
};
constexpr int kOffsets[kDecNumTensors] = {
    0, 101376, 105472, 3251200, 3254272, 4302848, 4303872, 4304896, 4305920, 4306944,
    4307968, 8502272, 8506368, 12700672, 12701696, 15847424, 15850496, 16899072, 16900096, 16901120,
    16902144, 16903168, 16904192, 21098496, 21102592, 25296896, 25297920, 25298944, 25299968, 25401344
};
constexpr int64_t sum_sizes() {
    int64_t s = 0;
    for (int i = 0; i < kDecNumTensors; ++i) s += kSizes[i];
    return s;
}
constexpr bool offsets_consistent() {
    int64_t acc = 0;
    for (int i = 0; i < kDecNumTensors; ++i) {
        if (kOffsets[i] != (int)acc) return false;
        acc += kSizes[i];
    }
    return true;
}
// Largest per-tensor numel (folds at compile time from the layout table). The
// d-INDEPENDENT optimizer tails (SuperGrok2's per-CTA workspace stride, sized for
// the LARGEST tensor) re-derive their capacity from THIS instead of a d=128-pinned
// 65536 literal, so the SAME tail code is correct at every ladder width.
constexpr int max_size() {
    int m = 0;
    for (int i = 0; i < kDecNumTensors; ++i) if (kSizes[i] > m) m = kSizes[i];
    return m;
}
static_assert(sum_sizes() == kDecTotalElems,
              "decoder_layout: sum(kDecSizes) != kDecTotalElems. Regenerate.");
static_assert(offsets_consistent(),
              "decoder_layout: kDecOffsets[i] != sum(kDecSizes[0..i)). Regenerate.");
}  // namespace dec_layout_check

// Largest per-tensor numel, hoisted to namespace scope. dec_tc_sg2_floats /
// dec_sg2_ws_stride_floats size their per-CTA SuperGrok2 workspace from THIS
// (max tensor numel) rather than a d=128-pinned 65536, so the tail is ladder-correct.
constexpr int kDecMaxTensorNumel = dec_layout_check::max_size();
#else
// ── PRODUCTION (d=128): the 33/33 wiring_check path. Byte-identical to the
//    historical generated header (the default when SG_DEC_BENCH_LAYOUT is unset). ──
constexpr int SG_DEC_VOCAB  = 99;
constexpr int SG_DEC_D      = 128;
constexpr int SG_DEC_HEADS  = 4;
constexpr int SG_DEC_LAYERS = 2;
constexpr int SG_DEC_SEQ    = 4;
constexpr int SG_DEC_DFF    = 4 * SG_DEC_D;   // 512

constexpr int     kDecNumTensors = 30;
constexpr int64_t kDecTotalElems = 422755;

// Per-tensor element offsets into the flat param blob, named_parameters() order.
__device__ __constant__ int kDecOffsets[kDecNumTensors] = {
    0, 12672, 13184, 62336, 62720, 79104, 79232, 79360, 79488, 79616,
    79744, 145280, 145792, 211328, 211456, 260608, 260992, 277376, 277504, 277632,
    277760, 277888, 278016, 343552, 344064, 409600, 409728, 409856, 409984, 422656
};

// Per-tensor element sizes (numel), same order.
__device__ __constant__ int kDecSizes[kDecNumTensors] = {
    12672, 512, 49152, 384, 16384, 128, 128, 128, 128, 128,
    65536, 512, 65536, 128, 49152, 384, 16384, 128, 128, 128,
    128, 128, 65536, 512, 65536, 128, 128, 128, 12672, 99
};

static_assert(kDecNumTensors == 30,
              "decoder_layout: tensor count drifted. Regenerate via "
              "megakernel_codegen.py --decoder-layout.");
static_assert(kDecTotalElems == 422755,
              "decoder_layout: total param count drifted. Regenerate.");

// Host-constexpr mirrors so a sum/offset cross-check folds at compile time (a
// __constant__ array can't be folded in a constexpr). These guarantee
// offsets/sizes/total agree.
namespace dec_layout_check {
constexpr int kSizes[kDecNumTensors] = {
    12672, 512, 49152, 384, 16384, 128, 128, 128, 128, 128,
    65536, 512, 65536, 128, 49152, 384, 16384, 128, 128, 128,
    128, 128, 65536, 512, 65536, 128, 128, 128, 12672, 99
};
constexpr int kOffsets[kDecNumTensors] = {
    0, 12672, 13184, 62336, 62720, 79104, 79232, 79360, 79488, 79616,
    79744, 145280, 145792, 211328, 211456, 260608, 260992, 277376, 277504, 277632,
    277760, 277888, 278016, 343552, 344064, 409600, 409728, 409856, 409984, 422656
};
constexpr int64_t sum_sizes() {
    int64_t s = 0;
    for (int i = 0; i < kDecNumTensors; ++i) s += kSizes[i];
    return s;
}
constexpr bool offsets_consistent() {
    int64_t acc = 0;
    for (int i = 0; i < kDecNumTensors; ++i) {
        if (kOffsets[i] != (int)acc) return false;
        acc += kSizes[i];
    }
    return true;
}
// Largest per-tensor numel (folds at compile time from the layout table). The
// d-INDEPENDENT optimizer tails (SuperGrok2's per-CTA workspace stride, sized for
// the LARGEST tensor) re-derive their capacity from THIS instead of a d=128-pinned
// 65536 literal, so the SAME tail code is correct at every ladder width.
constexpr int max_size() {
    int m = 0;
    for (int i = 0; i < kDecNumTensors; ++i) if (kSizes[i] > m) m = kSizes[i];
    return m;
}
static_assert(sum_sizes() == kDecTotalElems,
              "decoder_layout: sum(kDecSizes) != kDecTotalElems. Regenerate.");
static_assert(offsets_consistent(),
              "decoder_layout: kDecOffsets[i] != sum(kDecSizes[0..i)). Regenerate.");
}  // namespace dec_layout_check

// Largest per-tensor numel, hoisted to namespace scope. dec_tc_sg2_floats /
// dec_sg2_ws_stride_floats size their per-CTA SuperGrok2 workspace from THIS
// (max tensor numel) rather than a d=128-pinned 65536, so the tail is ladder-correct.
constexpr int kDecMaxTensorNumel = dec_layout_check::max_size();
#endif  // SG_DEC_BENCH_LAYOUT

}}} // namespace sg::fused::sm90

#endif  // SG_FUSED_SM90_DECODER_LAYOUT_CUH_
