#ifndef SG_FUSED_SM90_MAMBA3_LAYOUT_CUH_
#define SG_FUSED_SM90_MAMBA3_LAYOUT_CUH_
// ============================================================================
// csrc/fused/sm_90/mamba3_layout.cuh — weight-layout mirror for the L3-REAL
// Mamba megakernel (PHASE 2).
//
// AUTO-GENERATED by: python -m grokking_optimizers.megakernel_codegen \
//     --mamba-layout > csrc/fused/sm_90/mamba3_layout.cuh
// Do NOT hand-edit the numbers. SINGLE SOURCE OF TRUTH: megakernel_codegen.py
// _mamba_param_sizes() (mirrored by tests/hw/mamba_oracle.py::mamba_param_layout(),
// asserted == the eager model's named_parameters() ORDER + count + total in the
// parity test tests/hw/test_mamba_megakernel.py). The flat blob is
// torch.cat([p.reshape(-1) for _, p in model.named_parameters()]); the kernel
// addresses tensor i at params + kMambaOffsets[i] for kMambaSizes[i] elements.
//
// CRITICAL ORDERING NOTE: PyTorch yields a module's OWN nn.Parameters before its
// submodules, so within each SelectiveSSMLayer **A_log and D come BEFORE in_proj**
// (NOT the __init__ visual order). The order below matches the verified dump.
//
// A count/total mismatch fails the BUILD loudly (the static_asserts below), never
// corrupts at dispatch.
//
// ── SG_MB_BENCH_LAYOUT (size-ladder d-scaled bench variant) ──────────────────
// Two layouts coexist under the single include guard. SG_MB_BENCH_LAYOUT is UNSET
// on the production _ops build (→ the d=128 branch, byte-identical to the
// historical header), and set to 1 ONLY by the d-scaled benchmark TU / the
// _ops_bench variant extension (→ the d=1024 branch: d_inner=2048,
// dt_rank=64). The branches are mutually exclusive at preprocess time,
// so a TU compiles exactly one consistent (constants, __constant__ table,
// static-assert) set; production never sees the bench numbers. Mirrors the
// decoder's SG_DEC_BENCH_LAYOUT (commit 79d3840).
// ============================================================================

#include <cstdint>

#ifndef SG_MB_BENCH_LAYOUT
#define SG_MB_BENCH_LAYOUT 0
#endif

namespace sg { namespace fused { namespace sm90 {

#if SG_MB_BENCH_LAYOUT
// ── d-SCALED BENCH VARIANT (d=1024): the Mamba-megakernel roofline build.
//    NOT on the production path; selected ONLY by -DSG_MB_BENCH_LAYOUT=1. ──
constexpr int SG_MB_VOCAB  = 99;    // ntok (tok embedding rows)
constexpr int SG_MB_PHEAD  = 97;    // p (head width = out Linear cols)
constexpr int SG_MB_D      = 1024;   // d_model
constexpr int SG_MB_LAYERS = 2;     // nl
constexpr int SG_MB_SEQ    = 8;     // seq_len
constexpr int SG_MB_DINNER = 2048;   // d_inner (= d * expand_factor=2)
constexpr int SG_MB_STATE  = 16;    // state_dim
constexpr int SG_MB_DTRANK = 64;     // dt_rank = max(d/16,1)
constexpr int SG_MB_CONVK  = 3;     // conv1d kernel size

constexpr int     kMambaNumTensors = 28;
constexpr int64_t kMambaTotalElems = 13543521;

// Per-tensor element offsets into the flat param blob, named_parameters() order.
__device__ __constant__ int kMambaOffsets[kMambaNumTensors] = {
    0, 101376, 109568, 142336, 144384, 4338688, 4344832, 4346880, 4543488, 4674560,
    4676608, 6773760, 6774784, 6775808, 6808576, 6810624, 11004928, 11011072, 11013120, 11209728,
    11340800, 11342848, 13440000, 13441024, 13442048, 13443072, 13444096, 13543424
};

// Per-tensor element sizes (numel), same order.
__device__ __constant__ int kMambaSizes[kMambaNumTensors] = {
    101376, 8192, 32768, 2048, 4194304, 6144, 2048, 196608, 131072, 2048,
    2097152, 1024, 1024, 32768, 2048, 4194304, 6144, 2048, 196608, 131072,
    2048, 2097152, 1024, 1024, 1024, 1024, 99328, 97
};

static_assert(kMambaNumTensors == 28,
              "mamba3_layout: tensor count drifted from the oracle layout (28).");
static_assert(kMambaTotalElems == 13543521,
              "mamba3_layout: total param count drifted (13543521).");

// Host-constexpr mirrors so a sum/offset cross-check folds at compile time (a
// __constant__ array can't be folded in a constexpr).
namespace mamba_layout_check {
constexpr int kSizes[kMambaNumTensors] = {
    101376, 8192, 32768, 2048, 4194304, 6144, 2048, 196608, 131072, 2048,
    2097152, 1024, 1024, 32768, 2048, 4194304, 6144, 2048, 196608, 131072,
    2048, 2097152, 1024, 1024, 1024, 1024, 99328, 97
};
constexpr int kOffsets[kMambaNumTensors] = {
    0, 101376, 109568, 142336, 144384, 4338688, 4344832, 4346880, 4543488, 4674560,
    4676608, 6773760, 6774784, 6775808, 6808576, 6810624, 11004928, 11011072, 11013120, 11209728,
    11340800, 11342848, 13440000, 13441024, 13442048, 13443072, 13444096, 13543424
};
constexpr int64_t sum_sizes() {
    int64_t s = 0;
    for (int i = 0; i < kMambaNumTensors; ++i) s += kSizes[i];
    return s;
}
constexpr bool offsets_consistent() {
    int64_t acc = 0;
    for (int i = 0; i < kMambaNumTensors; ++i) {
        if (kOffsets[i] != (int)acc) return false;
        acc += kSizes[i];
    }
    return true;
}
// Largest per-tensor numel (folds at compile time from the layout table). The
// d-INDEPENDENT optimizer tails (SuperGrok2's per-CTA workspace stride, sized for
// the LARGEST tensor) re-derive their capacity from THIS instead of a d=128-pinned
// 65536 literal, so the SAME tail code is correct at every ladder width.
constexpr int max_size() {
    int m = 0;
    for (int i = 0; i < kMambaNumTensors; ++i) if (kSizes[i] > m) m = kSizes[i];
    return m;
}
static_assert(sum_sizes() == kMambaTotalElems,
              "mamba3_layout: sum(kMambaSizes) != kMambaTotalElems. Re-derive "
              "from tests/hw/mamba_oracle.py::mamba_param_layout().");
static_assert(offsets_consistent(),
              "mamba3_layout: kMambaOffsets[i] != sum(kMambaSizes[0..i)).");
}  // namespace mamba_layout_check

// Largest per-tensor numel, hoisted to namespace scope. mb_tc_sg2_floats /
// mb_sg2_ws_stride_floats size their per-CTA SuperGrok2 workspace from THIS
// (max tensor numel) rather than a d=128-pinned 65536, so the tail is ladder-correct.
constexpr int kMambaMaxTensorNumel = mamba_layout_check::max_size();

// ── SMEM footprint of MambaSampleSmem (model_stage_mamba3.cuh), d-SCALED BENCH.
//    At D=1024: d_inner=2048, dt_rank=64, dbc=96. sizeof(MambaSampleSmem) is
//    1121764 bytes (1095.47 KB) — OVER the sm_90 ~228 KB/SM
//    budget, so the SCALAR Mamba megakernel (the ONLY MambaSampleSmem consumer)
//    cannot place one block/SM at this width and is compiled OUT on the bench TU
//    (SG_MB_SCALAR_MEGAKERNEL=0), exactly as the decoder bench gates its scalar
//    megakernel. The TC engine the bench drives uses the small d-independent static
//    MbTcSmem and DOES fit, so the `< 224 KB` cap assert is intentionally NOT
//    emitted in this branch. Field-by-field (all float, 4 B, no padding):
//      layer_in 2*8*1024 + final_in 8*1024
//      + act[2] each (5*8*2048 + 2*8*16 + 8*1024 + 8) = 90376
//      + fn_xhat 8*1024 + fn_inv 8 + logits 97
//      + dh,dr 2*8*1024 + adj_a/b/c 3*8*2048 + dbc 8*96
//      + dBmat,dCmat 2*8*16 + red 256  = 280441 floats = 1121764 bytes
constexpr int64_t kMambaSmemFloats = 280441;
constexpr int64_t kMambaSmemBytes  = kMambaSmemFloats * (int64_t)sizeof(float); // 1121764
static_assert(kMambaSmemBytes > 48 * 1024,
              "mamba3_layout: if the smem ever drops below 48KB, switch the "
              "launcher back to STATIC smem (no opt-in needed).");
#else
// ── PRODUCTION (d=128): the 33/33 wiring_check path. Byte-identical to the
//    historical generated header (the default when SG_MB_BENCH_LAYOUT is unset). ──
constexpr int SG_MB_VOCAB  = 99;    // ntok (tok embedding rows)
constexpr int SG_MB_PHEAD  = 97;    // p (head width = out Linear cols)
constexpr int SG_MB_D      = 128;   // d_model
constexpr int SG_MB_LAYERS = 2;     // nl
constexpr int SG_MB_SEQ    = 8;     // seq_len
constexpr int SG_MB_DINNER = 256;   // d_inner (= d * expand_factor=2)
constexpr int SG_MB_STATE  = 16;    // state_dim
constexpr int SG_MB_DTRANK = 8;     // dt_rank = max(d/16,1)
constexpr int SG_MB_CONVK  = 3;     // conv1d kernel size

constexpr int     kMambaNumTensors = 28;
constexpr int64_t kMambaTotalElems = 259425;

// Per-tensor element offsets into the flat param blob, named_parameters() order.
__device__ __constant__ int kMambaOffsets[kMambaNumTensors] = {
    0, 12672, 13696, 17792, 18048, 83584, 84352, 84608, 94848, 96896,
    97152, 129920, 130048, 130176, 134272, 134528, 200064, 200832, 201088, 211328,
    213376, 213632, 246400, 246528, 246656, 246784, 246912, 259328
};

// Per-tensor element sizes (numel), same order.
__device__ __constant__ int kMambaSizes[kMambaNumTensors] = {
    12672, 1024, 4096, 256, 65536, 768, 256, 10240, 2048, 256,
    32768, 128, 128, 4096, 256, 65536, 768, 256, 10240, 2048,
    256, 32768, 128, 128, 128, 128, 12416, 97
};

static_assert(kMambaNumTensors == 28,
              "mamba3_layout: tensor count drifted from the oracle layout (28).");
static_assert(kMambaTotalElems == 259425,
              "mamba3_layout: total param count drifted (259425).");

// Host-constexpr mirrors so a sum/offset cross-check folds at compile time (a
// __constant__ array can't be folded in a constexpr).
namespace mamba_layout_check {
constexpr int kSizes[kMambaNumTensors] = {
    12672, 1024, 4096, 256, 65536, 768, 256, 10240, 2048, 256,
    32768, 128, 128, 4096, 256, 65536, 768, 256, 10240, 2048,
    256, 32768, 128, 128, 128, 128, 12416, 97
};
constexpr int kOffsets[kMambaNumTensors] = {
    0, 12672, 13696, 17792, 18048, 83584, 84352, 84608, 94848, 96896,
    97152, 129920, 130048, 130176, 134272, 134528, 200064, 200832, 201088, 211328,
    213376, 213632, 246400, 246528, 246656, 246784, 246912, 259328
};
constexpr int64_t sum_sizes() {
    int64_t s = 0;
    for (int i = 0; i < kMambaNumTensors; ++i) s += kSizes[i];
    return s;
}
constexpr bool offsets_consistent() {
    int64_t acc = 0;
    for (int i = 0; i < kMambaNumTensors; ++i) {
        if (kOffsets[i] != (int)acc) return false;
        acc += kSizes[i];
    }
    return true;
}
// Largest per-tensor numel (folds at compile time from the layout table). The
// d-INDEPENDENT optimizer tails (SuperGrok2's per-CTA workspace stride, sized for
// the LARGEST tensor) re-derive their capacity from THIS instead of a d=128-pinned
// 65536 literal, so the SAME tail code is correct at every ladder width.
constexpr int max_size() {
    int m = 0;
    for (int i = 0; i < kMambaNumTensors; ++i) if (kSizes[i] > m) m = kSizes[i];
    return m;
}
static_assert(sum_sizes() == kMambaTotalElems,
              "mamba3_layout: sum(kMambaSizes) != kMambaTotalElems. Re-derive "
              "from tests/hw/mamba_oracle.py::mamba_param_layout().");
static_assert(offsets_consistent(),
              "mamba3_layout: kMambaOffsets[i] != sum(kMambaSizes[0..i)).");
}  // namespace mamba_layout_check

// Largest per-tensor numel, hoisted to namespace scope. mb_tc_sg2_floats /
// mb_sg2_ws_stride_floats size their per-CTA SuperGrok2 workspace from THIS
// (max tensor numel) rather than a d=128-pinned 65536, so the tail is ladder-correct.
constexpr int kMambaMaxTensorNumel = mamba_layout_check::max_size();

// ── SMEM footprint of MambaSampleSmem (model_stage_mamba3.cuh). The Mamba CTA
//    smem EXCEEDS the 48 KB static cap (d_inner=256 + both-layer caching), so the
//    launcher MUST declare it DYNAMIC and opt in via
//    cudaFuncSetAttribute(kernel, cudaFuncAttributeMaxDynamicSharedMemorySize,
//    kMambaSmemBytes) before launch (sm_90 has ~228 KB smem/SM; one persistent
//    block/SM still places, occupancy>=1 holds, NO CUDA graphs). This is the
//    HONEST deviation from the decoder's <48 KB static footprint — see the
//    SMEM BUDGET note in model_stage_mamba3.cuh and INTEGRATION-MAMBA.md.
//
//    The number below is a static_assert-guarded mirror of sizeof(MambaSampleSmem)
//    computed field-by-field (all fields are float, 4-byte aligned -> no padding):
//      layer_in   [2][8][128]              = 2048
//      final_in   [8][128]                 = 1024
//      act[2].{ x_main_raw,z,conv,dt_pre,y_scan [8][256] (5*2048),
//               Bmat,Cmat [8][16] (2*128), ln_xhat [8][128], ln_inv [8] }
//                 per layer = 11528 ; x2  = 23056
//      fn_xhat[8][128]=1024; fn_inv[8]=8; logits[97]=97
//      dh,dr [8][128] (2*1024); adj_a,adj_b,adj_c [8][256] (3*2048)
//      dbc [8][40]=320; dBmat,dCmat [8][16] (2*128); red[256]
//      ------------------------------------------------------- = 36281 floats
constexpr int64_t kMambaSmemFloats = 36281;
constexpr int64_t kMambaSmemBytes  = kMambaSmemFloats * (int64_t)sizeof(float); // 145124
static_assert(kMambaSmemBytes > 48 * 1024,
              "mamba3_layout: if the smem ever drops below 48KB, switch the "
              "launcher back to STATIC smem (no opt-in needed).");
static_assert(kMambaSmemBytes < 224 * 1024,
              "mamba3_layout: CTA smem exceeds the sm_90 ~228KB/SM budget; "
              "one-block-per-SM would fail to place (GridBarrier hang). Shrink "
              "the live set (e.g. drop a cached LayerAct buffer).");
#endif  // SG_MB_BENCH_LAYOUT

}}} // namespace sg::fused::sm90

#endif  // SG_FUSED_SM90_MAMBA3_LAYOUT_CUH_
