#ifndef SG_FUSED_SM90_MAMBA3_LAYOUT_CUH_
#define SG_FUSED_SM90_MAMBA3_LAYOUT_CUH_
// ============================================================================
// csrc/fused/sm_90/mamba3_layout.cuh — weight-layout mirror for the L3-REAL
// Mamba megakernel (PHASE 2).
//
// AUTO-GENERATED by: python -m grokking_optimizers.megakernel_codegen \
//     --mamba-layout > csrc/fused/sm_90/mamba3_layout.cuh
// Do NOT hand-edit the numbers. SINGLE SOURCE OF TRUTH: megakernel_codegen.py
// _mamba_param_sizes(), which mirrors the eager Mamba-3 model
// grokking_optimizers/mamba3_block.py::Mamba3Model — asserted == its
// named_parameters() ORDER + count + total in the parity test
// tests/hw/test_mamba_megakernel.py. The flat blob is
// torch.cat([p.reshape(-1) for _, p in model.named_parameters()]); the kernel
// addresses tensor i at params + kMambaOffsets[i] for kMambaSizes[i] elements.
//
// CRITICAL ORDERING NOTE: PyTorch yields a module's OWN nn.Parameters before its
// submodules. The Mamba-3 model is a Llama-style stack of Mamba3Block layers; the
// 45-tensor order (nl=2) is: tok.weight, pos.weight, then per Mamba3Block
//   mixer_norm.weight,
//   mixer OWN params: A_log, D, B_bias, Bhat_bias, C_bias, Chat_bias,
//   mixer submodules: in_proj, x_proj, dt_proj.weight, dt_proj.bias,
//                     B_norm, Bhat_norm, C_norm, Chat_norm, out_proj,
//   mlp_norm.weight, then SwiGLU mlp: gate_proj, up_proj, down_proj,
// then norm.weight, out.weight, out.bias. So within each block **mixer_norm comes
// first, then the mixer's leaf params A_log/D/4-biases BEFORE its submodules** (NOT
// the __init__ visual order). Mamba-3 has NO conv1d and NO norm bias (RMSNorm). The
// order above matches the verified named_parameters() dump.
//
// A count/total mismatch fails the BUILD loudly (the static_asserts below), never
// corrupts at dispatch.
//
// ── SG_MB_BENCH_LAYOUT (size-ladder d-scaled bench variant) ──────────────────
// Two layouts coexist under the single include guard. SG_MB_BENCH_LAYOUT is UNSET
// on the production _ops build (→ the d=128 branch), and set to 1 ONLY by the
// d-scaled benchmark TU / the _ops_bench variant extension (→ the d=1024
// branch: d_inner=2048, n_heads=32,
// dt_rank=64). The branches are mutually exclusive at
// preprocess time, so a TU compiles exactly one consistent (constants, __constant__
// table, static-assert) set; production never sees the bench numbers. Mirrors the
// decoder's SG_DEC_BENCH_LAYOUT (commit 79d3840).
// ============================================================================

#include <cstdint>

#ifndef SG_MB_BENCH_LAYOUT
#define SG_MB_BENCH_LAYOUT 0
#endif

namespace sg { namespace fused { namespace sm90 {

#if SG_MB_BENCH_LAYOUT
// ── d-SCALED BENCH VARIANT (d=1024): the Mamba-megakernel roofline build.
//    NOT on the production path; selected ONLY by -DSG_MB_BENCH_LAYOUT=1. ──
constexpr int SG_MB_VOCAB   = 99;    // ntok (tok embedding rows)
constexpr int SG_MB_PHEAD   = 97;    // p (head width = out Linear cols)
constexpr int SG_MB_D       = 1024;   // d_model
constexpr int SG_MB_LAYERS  = 2;     // nl (Mamba3Block count)
constexpr int SG_MB_SEQ     = 8;     // seq_len
constexpr int SG_MB_DINNER  = 2048;   // d_inner (= d * expand_factor=2)
constexpr int SG_MB_STATE   = 128;   // REAL SSM state size N
constexpr int SG_MB_STATEC  = 64;    // complex state dim Nc (= N/2)
constexpr int SG_MB_HEADDIM = 64;    // SSM head dim P
constexpr int SG_MB_NHEADS  = 32;     // n_heads (= d_inner / head_dim)
constexpr int SG_MB_DTRANK  = 64;     // dt_rank = max(d/16,1)
constexpr int SG_MB_XPROJ   = 448;   // x_proj_out (= dt_rank + 2*n_heads + 5*Nc)
constexpr int SG_MB_DFF     = 2048;   // SwiGLU inner d_ff (= mlp_ratio * d)

constexpr int     kMambaNumTensors = 45;
constexpr int64_t kMambaTotalElems = 27224289;

// Per-tensor element offsets into the flat param blob, named_parameters() order.
__device__ __constant__ int kMambaOffsets[kMambaNumTensors] = {
    0, 101376, 109568, 110592, 110624, 112672, 112736, 112800, 112864, 112928,
    4307232, 5224736, 5226784, 5226816, 5226880, 5226944, 5227008, 5227072, 7324224, 7325248,
    9422400, 11519552, 13616704, 13617728, 13617760, 13619808, 13619872, 13619936, 13620000, 13620064,
    17814368, 18731872, 18733920, 18733952, 18734016, 18734080, 18734144, 18734208, 20831360, 20832384,
    22929536, 25026688, 27123840, 27124864, 27224192
};

// Per-tensor element sizes (numel), same order.
__device__ __constant__ int kMambaSizes[kMambaNumTensors] = {
    101376, 8192, 1024, 32, 2048, 64, 64, 64, 64, 4194304,
    917504, 2048, 32, 64, 64, 64, 64, 2097152, 1024, 2097152,
    2097152, 2097152, 1024, 32, 2048, 64, 64, 64, 64, 4194304,
    917504, 2048, 32, 64, 64, 64, 64, 2097152, 1024, 2097152,
    2097152, 2097152, 1024, 99328, 97
};

static_assert(kMambaNumTensors == 45,
              "mamba3_layout: tensor count drifted from the Mamba3Model layout (45).");
static_assert(kMambaTotalElems == 27224289,
              "mamba3_layout: total param count drifted (27224289).");

// Host-constexpr mirrors so a sum/offset cross-check folds at compile time (a
// __constant__ array can't be folded in a constexpr).
namespace mamba_layout_check {
constexpr int kSizes[kMambaNumTensors] = {
    101376, 8192, 1024, 32, 2048, 64, 64, 64, 64, 4194304,
    917504, 2048, 32, 64, 64, 64, 64, 2097152, 1024, 2097152,
    2097152, 2097152, 1024, 32, 2048, 64, 64, 64, 64, 4194304,
    917504, 2048, 32, 64, 64, 64, 64, 2097152, 1024, 2097152,
    2097152, 2097152, 1024, 99328, 97
};
constexpr int kOffsets[kMambaNumTensors] = {
    0, 101376, 109568, 110592, 110624, 112672, 112736, 112800, 112864, 112928,
    4307232, 5224736, 5226784, 5226816, 5226880, 5226944, 5227008, 5227072, 7324224, 7325248,
    9422400, 11519552, 13616704, 13617728, 13617760, 13619808, 13619872, 13619936, 13620000, 13620064,
    17814368, 18731872, 18733920, 18733952, 18734016, 18734080, 18734144, 18734208, 20831360, 20832384,
    22929536, 25026688, 27123840, 27124864, 27224192
};
constexpr int64_t sum_sizes() {
    int64_t s = 0;
    for (int i = 0; i < kMambaNumTensors; ++i) s += kSizes[i];
    return s;
}
constexpr bool offsets_consistent() {
    int64_t acc = 0;
    for (int i = 0; i < kMambaNumTensors; ++i) {
        if (kOffsets[i] != (int)acc) return false;
        acc += kSizes[i];
    }
    return true;
}
// Largest per-tensor numel (folds at compile time from the layout table). The
// d-INDEPENDENT optimizer tails (SuperGrok2's per-CTA workspace stride, sized for
// the LARGEST tensor) re-derive their capacity from THIS instead of a d=128-pinned
// 65536 literal, so the SAME tail code is correct at every ladder width.
constexpr int max_size() {
    int m = 0;
    for (int i = 0; i < kMambaNumTensors; ++i) if (kSizes[i] > m) m = kSizes[i];
    return m;
}
static_assert(sum_sizes() == kMambaTotalElems,
              "mamba3_layout: sum(kMambaSizes) != kMambaTotalElems. Re-derive "
              "from grokking_optimizers/mamba3_block.py::Mamba3Model.");
static_assert(offsets_consistent(),
              "mamba3_layout: kMambaOffsets[i] != sum(kMambaSizes[0..i)).");
}  // namespace mamba_layout_check

// Largest per-tensor numel, hoisted to namespace scope. mb_tc_sg2_floats /
// mb_sg2_ws_stride_floats size their per-CTA SuperGrok2 workspace from THIS
// (max tensor numel) rather than a d=128-pinned 65536, so the tail is ladder-correct.
constexpr int kMambaMaxTensorNumel = mamba_layout_check::max_size();

// ── SMEM footprint of MambaSampleSmem (model_stage_mamba3.cuh), d-SCALED BENCH.
//    At D=1024: d_inner=2048, n_heads=32, dt_rank=64, Nc=64, d_ff=2048. The
//    SCALAR Mamba megakernel (the ONLY MambaSampleSmem consumer) is compiled OUT on
//    the bench TU (SG_MB_SCALAR_MEGAKERNEL=0), exactly as the decoder bench gates
//    its scalar megakernel; the TC engine the bench drives uses the small
//    d-independent static MbTcSmem, so the `< 224 KB` cap assert is intentionally
//    NOT emitted in this branch.
//
//    kMambaSmemFloats is a SAFE LARGE PLACEHOLDER (Mamba-3 rewrite): the exact
//    field count is pinned by model_stage_mamba3.cuh static_assert
//    (sizeof(MambaSampleSmem) == kMambaSmemBytes), which fails the build with the
//    required value if this differs. It is kept strictly inside (48 KB, 224 KB).
constexpr int64_t kMambaSmemFloats = 329481;
constexpr int64_t kMambaSmemBytes  = kMambaSmemFloats * (int64_t)sizeof(float); // 1317924
static_assert(kMambaSmemBytes > 48 * 1024,
              "mamba3_layout: if the smem ever drops below 48KB, switch the "
              "launcher back to STATIC smem (no opt-in needed).");
#else
// ── PRODUCTION (d=128): the wiring_check path (the default when
//    SG_MB_BENCH_LAYOUT is unset). ──
constexpr int SG_MB_VOCAB   = 99;    // ntok (tok embedding rows)
constexpr int SG_MB_PHEAD   = 97;    // p (head width = out Linear cols)
constexpr int SG_MB_D       = 128;   // d_model
constexpr int SG_MB_LAYERS  = 2;     // nl (Mamba3Block count)
constexpr int SG_MB_SEQ     = 8;     // seq_len
constexpr int SG_MB_DINNER  = 256;   // d_inner (= d * expand_factor=2)
constexpr int SG_MB_STATE   = 128;   // REAL SSM state size N
constexpr int SG_MB_STATEC  = 64;    // complex state dim Nc (= N/2)
constexpr int SG_MB_HEADDIM = 64;    // SSM head dim P
constexpr int SG_MB_NHEADS  = 4;     // n_heads (= d_inner / head_dim)
constexpr int SG_MB_DTRANK  = 8;     // dt_rank = max(d/16,1)
constexpr int SG_MB_XPROJ   = 336;   // x_proj_out (= dt_rank + 2*n_heads + 5*Nc)
constexpr int SG_MB_DFF     = 256;   // SwiGLU inner d_ff (= mlp_ratio * d)

constexpr int     kMambaNumTensors = 45;
constexpr int64_t kMambaTotalElems = 593713;

// Per-tensor element offsets into the flat param blob, named_parameters() order.
__device__ __constant__ int kMambaOffsets[kMambaNumTensors] = {
    0, 12672, 13696, 13824, 13828, 14084, 14148, 14212, 14276, 14340,
    79876, 165892, 165924, 165928, 165992, 166056, 166120, 166184, 198952, 199080,
    231848, 264616, 297384, 297512, 297516, 297772, 297836, 297900, 297964, 298028,
    363564, 449580, 449612, 449616, 449680, 449744, 449808, 449872, 482640, 482768,
    515536, 548304, 581072, 581200, 593616
};

// Per-tensor element sizes (numel), same order.
__device__ __constant__ int kMambaSizes[kMambaNumTensors] = {
    12672, 1024, 128, 4, 256, 64, 64, 64, 64, 65536,
    86016, 32, 4, 64, 64, 64, 64, 32768, 128, 32768,
    32768, 32768, 128, 4, 256, 64, 64, 64, 64, 65536,
    86016, 32, 4, 64, 64, 64, 64, 32768, 128, 32768,
    32768, 32768, 128, 12416, 97
};

static_assert(kMambaNumTensors == 45,
              "mamba3_layout: tensor count drifted from the Mamba3Model layout (45).");
static_assert(kMambaTotalElems == 593713,
              "mamba3_layout: total param count drifted (593713).");

// Host-constexpr mirrors so a sum/offset cross-check folds at compile time (a
// __constant__ array can't be folded in a constexpr).
namespace mamba_layout_check {
constexpr int kSizes[kMambaNumTensors] = {
    12672, 1024, 128, 4, 256, 64, 64, 64, 64, 65536,
    86016, 32, 4, 64, 64, 64, 64, 32768, 128, 32768,
    32768, 32768, 128, 4, 256, 64, 64, 64, 64, 65536,
    86016, 32, 4, 64, 64, 64, 64, 32768, 128, 32768,
    32768, 32768, 128, 12416, 97
};
constexpr int kOffsets[kMambaNumTensors] = {
    0, 12672, 13696, 13824, 13828, 14084, 14148, 14212, 14276, 14340,
    79876, 165892, 165924, 165928, 165992, 166056, 166120, 166184, 198952, 199080,
    231848, 264616, 297384, 297512, 297516, 297772, 297836, 297900, 297964, 298028,
    363564, 449580, 449612, 449616, 449680, 449744, 449808, 449872, 482640, 482768,
    515536, 548304, 581072, 581200, 593616
};
constexpr int64_t sum_sizes() {
    int64_t s = 0;
    for (int i = 0; i < kMambaNumTensors; ++i) s += kSizes[i];
    return s;
}
constexpr bool offsets_consistent() {
    int64_t acc = 0;
    for (int i = 0; i < kMambaNumTensors; ++i) {
        if (kOffsets[i] != (int)acc) return false;
        acc += kSizes[i];
    }
    return true;
}
// Largest per-tensor numel (folds at compile time from the layout table). The
// d-INDEPENDENT optimizer tails (SuperGrok2's per-CTA workspace stride, sized for
// the LARGEST tensor) re-derive their capacity from THIS instead of a d=128-pinned
// 65536 literal, so the SAME tail code is correct at every ladder width.
constexpr int max_size() {
    int m = 0;
    for (int i = 0; i < kMambaNumTensors; ++i) if (kSizes[i] > m) m = kSizes[i];
    return m;
}
static_assert(sum_sizes() == kMambaTotalElems,
              "mamba3_layout: sum(kMambaSizes) != kMambaTotalElems. Re-derive "
              "from grokking_optimizers/mamba3_block.py::Mamba3Model.");
static_assert(offsets_consistent(),
              "mamba3_layout: kMambaOffsets[i] != sum(kMambaSizes[0..i)).");
}  // namespace mamba_layout_check

// Largest per-tensor numel, hoisted to namespace scope. mb_tc_sg2_floats /
// mb_sg2_ws_stride_floats size their per-CTA SuperGrok2 workspace from THIS
// (max tensor numel) rather than a d=128-pinned 65536, so the tail is ladder-correct.
constexpr int kMambaMaxTensorNumel = mamba_layout_check::max_size();

// ── SMEM footprint of MambaSampleSmem (model_stage_mamba3.cuh). The Mamba CTA
//    smem EXCEEDS the 48 KB static cap (d_inner + both-layer caching), so the
//    launcher MUST declare it DYNAMIC and opt in via
//    cudaFuncSetAttribute(kernel, cudaFuncAttributeMaxDynamicSharedMemorySize,
//    kMambaSmemBytes) before launch (sm_90 has ~228 KB smem/SM; one persistent
//    block/SM still places, occupancy>=1 holds, NO CUDA graphs). This is the
//    HONEST deviation from the decoder's <48 KB static footprint — see the
//    SMEM BUDGET note in model_stage_mamba3.cuh and INTEGRATION-MAMBA.md.
//
//    kMambaSmemFloats is a SAFE LARGE PLACEHOLDER (Mamba-3 rewrite): the exact
//    field count is pinned by model_stage_mamba3.cuh static_assert
//    (sizeof(MambaSampleSmem) == kMambaSmemBytes), which fails the build with the
//    required value if this differs. It is kept strictly inside (48 KB, 224 KB).
constexpr int64_t kMambaSmemFloats = 53961;
constexpr int64_t kMambaSmemBytes  = kMambaSmemFloats * (int64_t)sizeof(float); // 215844
static_assert(kMambaSmemBytes > 48 * 1024,
              "mamba3_layout: if the smem ever drops below 48KB, switch the "
              "launcher back to STATIC smem (no opt-in needed).");
static_assert(kMambaSmemBytes <= 228 * 1024,
              "mamba3_layout: CTA smem exceeds the sm_90 ~228KB/SM opt-in budget; "
              "one-block-per-SM would fail to place (GridBarrier hang). Shrink "
              "the live set (e.g. drop a cached LayerAct buffer).");
#endif  // SG_MB_BENCH_LAYOUT

}}} // namespace sg::fused::sm90

#endif  // SG_FUSED_SM90_MAMBA3_LAYOUT_CUH_
