// csrc/fused/sm_90/mega_transformer_decoder_muon.cu  — GENERATED by megakernel_codegen.py
// Cell: (transformer_decoder, muon, sm_90)  tier=L3_FWD_BWD_OPT
//   regs=168/255  smem=66560/233472
//   fits L3
//
// REAL component composition (Phase 3 Stage 5): composes the real optimizer
// device-function component (csrc/algorithms/muon.h via
// opt_components.cuh::apply_optimizer<OptId::Muon>) with the real model
// stage component (model_stages.cuh::model_*_stage<ModelId::TransformerDecoder>) over the
// shared persistent-megakernel substrate. Fuse tier L3 chosen by the solver.
#include "csrc/fused/sm_90/fused_megakernel.cuh"

namespace sg { namespace fused { namespace sm90 {

// Uniform host entry (the symbol fused_step dispatches to). Binds this
// optimizer's REAL state buffers: m/v (Adam moments) + the per-optimizer
// `extra` n-slice (ema/sam_dir/s_track/mu/orth/smart_grad). Scalar hyperparams
// (prodigy d, sg gates, neuralgrok psi-net) are host-supplied at runtime (🟡
// no-GPU here) — see HARDWARE_VALIDATION.md. Composition + apply math are
// real + compiled.
cudaError_t mega_transformer_decoder_muon(
        PersistentContext ctx, float* params, const float* input, float* acts,
        float* grad, float* m, float* v, float* extra,
        const int* sizes, const int* offsets,
        float lr, int step, cudaStream_t stream) {
    FusedOptState st;
    st.exp_avg = m;
    st.exp_avg_sq = v;
    st.orth = extra;  // muon's third per-element state buffer
    st.lr = lr;
    return launch_fused_megakernel<ModelId::TransformerDecoder, OptId::Muon,
                                   FuseTier::L3>(
        ctx, params, input, acts, grad, sizes, offsets, lr, step, st, stream);
}

}}}  // namespace sg::fused::sm90
