// csrc/fused/sm_90/mega_transformer_decoder_grokfast.cu  — GENERATED by megakernel_codegen.py
// Cell: (transformer_decoder, grokfast, sm_90)  tier=L3_FWD_BWD_OPT
//   regs=248/255  smem=65536/233472
//   fits L3
// NOTE: optimizer 'grokfast' has no dedicated demo tail; instantiated with the 'adamw' elementwise tail as a structural placeholder (production generator emits the exact tail).
// This cell is ALREADY wired in the canonical demo TU (megakernel_demo.cu);
// the generator would normally SKIP emitting it to disk. Shown here for
// completeness — the launcher below is named distinctly to avoid a clash.
//
// Instantiates the ONE templated L3 persistent megakernel for this (model,
// optimizer). SG_MEGAKERNEL_DEMO_TEMPLATE_ONLY pulls in JUST the template
// machinery (scheduler/barrier substrate, SM-pinning, fused-optimizer tail —
// all comdat-folded across TUs); this TU adds only its own unique launcher.
#define SG_MEGAKERNEL_DEMO_TEMPLATE_ONLY
#include "csrc/fused/sm_90/megakernel_demo.cu"

namespace sg { namespace fused { namespace sm90 {

cudaError_t mega_transformer_decoder_grokfast(
        PersistentContext ctx, float* params, const float* input, float* acts,
        float* grad, float* m, float* v, const int* sizes, const int* offsets,
        float lr, int step, cudaStream_t stream) {
    return launch_l3_megakernel<Model::TransformerDecoder, Optimizer::AdamW>(
        ctx, params, input, acts, grad, m, v, sizes, offsets, lr, step, stream);
}

}}}  // namespace sg::fused::sm90
