// csrc/fused/sm_90/mega_mamba3_neuralgrok.cu  — GENERATED by megakernel_codegen.py
// Cell: (mamba3, neuralgrok, sm_90)  tier=L3_FWD_BWD_OPT
//   regs=176/255  smem=50176/233472
//   fits L3
//
// REAL component composition (Phase 3 Stage 5): composes the real optimizer
// device-function component (csrc/algorithms/neuralgrok.h via
// opt_components.cuh::apply_optimizer<OptId::NeuralGrok>) with the real model
// stage component (model_stages.cuh::model_*_stage<ModelId::Mamba3>) over the
// shared persistent-megakernel substrate. Fuse tier L3 chosen by the solver.
#include "csrc/fused/sm_90/fused_megakernel.cuh"

namespace sg { namespace fused { namespace sm90 {

// Uniform host entry (the symbol fused_step dispatches to). Binds this
// optimizer's REAL state buffers: m/v (Adam moments) + the per-optimizer
// `extra` n-slice (ema/sam_dir/s_track/mu/orth/smart_grad). Scalar hyperparams
// (prodigy d, sg gates, neuralgrok psi-net) are host-supplied at runtime (🟡
// no-GPU here) — see HARDWARE_VALIDATION.md. Composition + apply math are
// real + compiled.
cudaError_t mega_mamba3_neuralgrok(
        PersistentContext ctx, float* params, const float* input, float* acts,
        float* grad, float* m, float* v, float* extra,
        const int* sizes, const int* offsets,
        float lr, int step, cudaStream_t stream) {
    FusedOptState st;
    st.exp_avg = m;
    st.exp_avg_sq = v;
    // #5: bind the psi-net weights from the packed `extra` buffer (layout in
    // opt_components.cuh: W1|b1|W2|b2). Without this the psi pointers stay null
    // and neuralgrok_psi_forward null-derefs on this real path.
    if (extra) {
        st.psi_W1 = extra + kPsiW1Off;
        st.psi_b1 = extra + kPsiB1Off;
        st.psi_W2 = extra + kPsiW2Off;
        // st.psi_b2 stays 0.0f (device scalar at extra[kPsiB2Off]; a host scalar
        // cannot dereference a device pointer — codegen stop, see report).
    }
    st.lr = lr;
    return launch_fused_megakernel<ModelId::Mamba3, OptId::NeuralGrok,
                                   FuseTier::L3>(
        ctx, params, input, acts, grad, sizes, offsets, lr, step, st, stream);
}

}}}  // namespace sg::fused::sm90
