#ifndef SG_FUSED_SM90_VIT_LAYOUT_CUH_
#define SG_FUSED_SM90_VIT_LAYOUT_CUH_
// ============================================================================
// csrc/fused/sm_90/vit_layout.cuh — weight-layout mirror for the L3-REAL
// Vision-Transformer megakernel (PHASE 2).
//
// AUTO-GENERATED by: python -m grokking_optimizers.megakernel_codegen \
//     --vit-layout > csrc/fused/sm_90/vit_layout.cuh
// Do NOT hand-edit the numbers. SINGLE SOURCE OF TRUTH: megakernel_codegen.py
// _vit_param_sizes() (mirrored by tests/hw/vit_oracle.py::vit_param_layout(),
// asserted == the live model's named_parameters() order in the parity test
// tests/hw/test_vit_megakernel.py). The flat blob is
// torch.cat([p.reshape(-1) for _, p in model.named_parameters()]); the kernel
// addresses tensor i at params + kVitOffsets[i] for kVitSizes[i] elems.
//
// A count/total mismatch fails the BUILD loudly (a static_assert below), never
// corrupts at dispatch.
//
// named_parameters() ORDER (32 tensors) — note cls_token (a leaf nn.Parameter on
// the ViT module) is yielded BEFORE the patch_proj submodule's params:
//   0  cls_token              [1,1,128]
//   1  patch_proj.weight      [128,49]
//   2  patch_proj.bias        [128]
//   3  pos.weight             [17,128]
//   4..15   layers.0.{attn.in_proj_w/b, attn.out_proj.w/b, n1.w/b, n2.w/b,
//                     ff.0.w/b, ff.2.w/b}
//   16..27  layers.1.{...same...}
//   28 norm.weight [128]  29 norm.bias [128]  30 out.weight [97,128]  31 out.bias [97]
//
// ── SG_VIT_BENCH_LAYOUT (size-ladder d-scaled bench variant) ─────────────────
// Two layouts coexist under the single include guard. SG_VIT_BENCH_LAYOUT is
// UNSET on the production _ops build (→ the d=128 branch, byte-identical to
// the historical header), and set to 1 ONLY by the d-scaled benchmark TU / the
// _ops_bench variant extension (→ the d=2048 branch, HEADS=32
// via the d/64 head-dim rule). The branches are mutually exclusive at preprocess
// time, so a TU compiles exactly one consistent (constants, __constant__ table,
// static-assert) set; production never sees the bench numbers. Mirrors the
// decoder's SG_DEC_BENCH_LAYOUT (commit 79d3840).
// ============================================================================

#include <cstdint>

#ifndef SG_VIT_BENCH_LAYOUT
#define SG_VIT_BENCH_LAYOUT 0
#endif

namespace sg { namespace fused { namespace sm90 {

#if SG_VIT_BENCH_LAYOUT
// ── d-SCALED BENCH VARIANT (d=2048): the ViT-megakernel roofline build.
//    NOT on the production path; selected ONLY by -DSG_VIT_BENCH_LAYOUT=1. ──
constexpr int SG_VIT_VOCAB  = 97;          // p (head Linear(d, p))
constexpr int SG_VIT_D      = 2048;
constexpr int SG_VIT_HEADS  = 32;
constexpr int SG_VIT_LAYERS = 2;
constexpr int SG_VIT_PATCH  = 49;          // patch pixel count (7×7)
constexpr int SG_VIT_NPATCH = 16;          // image patches
constexpr int SG_VIT_SEQ    = SG_VIT_NPATCH + 1;  // 17 (CLS + 16 patches)
constexpr int SG_VIT_DFF    = 4 * SG_VIT_D;       // 8192

constexpr int     kVitNumTensors = 32;
constexpr int64_t kVitTotalElems = 101058657;

// Per-tensor element offsets into the flat param blob, named_parameters() order.
__device__ __constant__ int kVitOffsets[kVitNumTensors] = {
    0, 2048, 102400, 104448, 139264, 12722176, 12728320, 16922624, 16924672, 16926720,
    16928768, 16930816, 16932864, 33710080, 33718272, 50495488, 50497536, 63080448, 63086592, 67280896,
    67282944, 67284992, 67287040, 67289088, 67291136, 84068352, 84076544, 100853760, 100855808, 100857856,
    100859904, 101058560
};

// Per-tensor element sizes (numel), same order.
__device__ __constant__ int kVitSizes[kVitNumTensors] = {
    2048, 100352, 2048, 34816, 12582912, 6144, 4194304, 2048, 2048, 2048,
    2048, 2048, 16777216, 8192, 16777216, 2048, 12582912, 6144, 4194304, 2048,
    2048, 2048, 2048, 2048, 16777216, 8192, 16777216, 2048, 2048, 2048,
    198656, 97
};

static_assert(kVitNumTensors == 32,
              "vit_layout: tensor count drifted. Regenerate from "
              "vit_oracle.py::vit_param_layout() (codegen adoption: --vit-layout).");
static_assert(kVitTotalElems == 101058657,
              "vit_layout: total param count drifted. Regenerate.");

// Host-constexpr mirrors so a sum/offset cross-check folds at compile time (a
// __constant__ array can't be folded in a constexpr). These guarantee
// offsets/sizes/total agree.
namespace vit_layout_check {
constexpr int kSizes[kVitNumTensors] = {
    2048, 100352, 2048, 34816, 12582912, 6144, 4194304, 2048, 2048, 2048,
    2048, 2048, 16777216, 8192, 16777216, 2048, 12582912, 6144, 4194304, 2048,
    2048, 2048, 2048, 2048, 16777216, 8192, 16777216, 2048, 2048, 2048,
    198656, 97
};
constexpr int kOffsets[kVitNumTensors] = {
    0, 2048, 102400, 104448, 139264, 12722176, 12728320, 16922624, 16924672, 16926720,
    16928768, 16930816, 16932864, 33710080, 33718272, 50495488, 50497536, 63080448, 63086592, 67280896,
    67282944, 67284992, 67287040, 67289088, 67291136, 84068352, 84076544, 100853760, 100855808, 100857856,
    100859904, 101058560
};
constexpr int64_t sum_sizes() {
    int64_t s = 0;
    for (int i = 0; i < kVitNumTensors; ++i) s += kSizes[i];
    return s;
}
constexpr bool offsets_consistent() {
    int64_t acc = 0;
    for (int i = 0; i < kVitNumTensors; ++i) {
        if (kOffsets[i] != (int)acc) return false;
        acc += kSizes[i];
    }
    return true;
}
// Largest per-tensor numel (folds at compile time from the layout table). The
// d-INDEPENDENT optimizer tails (SuperGrok2's per-CTA workspace stride, sized for
// the LARGEST tensor) re-derive their capacity from THIS instead of a d=128-pinned
// 65536 literal, so the SAME tail code is correct at every ladder width.
constexpr int max_size() {
    int m = 0;
    for (int i = 0; i < kVitNumTensors; ++i) if (kSizes[i] > m) m = kSizes[i];
    return m;
}
static_assert(sum_sizes() == kVitTotalElems,
              "vit_layout: sum(kVitSizes) != kVitTotalElems. Regenerate.");
static_assert(offsets_consistent(),
              "vit_layout: kVitOffsets[i] != sum(kVitSizes[0..i)). Regenerate.");

// ── Per-CTA dynamic-smem budget (d-SCALED BENCH). The ViT per-sample working set
//    (VitSampleSmem, model_stage_vit.cuh) is ≈ 2864016 bytes (2796.89 KB) at
//    seq=17, D=2048, HEADS=32 — over the sm_90 227 KB per-block dynamic cap, so
//    the SCALAR ViT megakernel (the ONLY VitSampleSmem consumer) cannot launch at
//    this width and is compiled OUT on the bench TU (SG_VIT_SCALAR_MEGAKERNEL=0),
//    exactly as the decoder bench gates its scalar megakernel. The TC engine the
//    bench drives uses the small, d-independent static VitTcSmem and DOES fit, so
//    the `< 227 KB` cap assert below is intentionally NOT emitted in this branch.
//    Computed from the field list (all float, 4 B, no padding):
//      patch 16*49 + layer_in 2*17*2048 + final_in 17*2048 + qkv 17*6144
//      + ctx 17*2048 + x1 17*2048 + ff0 17*8192 + gact 17*8192 + attn 32*17*17
//      + n1_xhat 17*2048 + n1_inv 17 + n2_xhat 17*2048 + n2_inv 17
//      + fn_xhat 17*2048 + fn_inv 17 + dh 17*2048 + logits 97 + dsc 32*17*17
//      + red 256  = 716004 floats = 2864016 bytes. ─
constexpr int kVitSampleSmemFloats =
    16 * 49
  + 2 * 17 * 2048
  + 17 * 2048
  + 17 * 6144
  + 17 * 2048
  + 17 * 2048
  + 17 * 8192
  + 17 * 8192
  + 32 * 17 * 17
  + 17 * 2048 + 17
  + 17 * 2048 + 17
  + 17 * 2048 + 17
  + 17 * 2048
  + 97
  + 32 * 17 * 17
  + 256;
constexpr int kVitSampleSmemBytes = kVitSampleSmemFloats * (int)sizeof(float);
static_assert(kVitSampleSmemBytes == 2864016,
              "vit_layout: VitSampleSmem byte budget drifted from 2864016.");
}  // namespace vit_layout_check

// Largest per-tensor numel, hoisted to namespace scope. vit_tc_sg2_floats /
// vit_sg2_ws_stride_floats size their per-CTA SuperGrok2 workspace from THIS
// (max tensor numel) rather than a d=128-pinned 65536, so the tail is ladder-correct.
constexpr int kVitMaxTensorNumel = vit_layout_check::max_size();
#else
// ── PRODUCTION (d=128): the 33/33 wiring_check path. Byte-identical to the
//    historical generated header (the default when SG_VIT_BENCH_LAYOUT is unset). ──
constexpr int SG_VIT_VOCAB  = 97;          // p (head Linear(d, p))
constexpr int SG_VIT_D      = 128;
constexpr int SG_VIT_HEADS  = 4;
constexpr int SG_VIT_LAYERS = 2;
constexpr int SG_VIT_PATCH  = 49;          // patch pixel count (7×7)
constexpr int SG_VIT_NPATCH = 16;          // image patches
constexpr int SG_VIT_SEQ    = SG_VIT_NPATCH + 1;  // 17 (CLS + 16 patches)
constexpr int SG_VIT_DFF    = 4 * SG_VIT_D;       // 512

constexpr int     kVitNumTensors = 32;
constexpr int64_t kVitTotalElems = 418017;

// Per-tensor element offsets into the flat param blob, named_parameters() order.
__device__ __constant__ int kVitOffsets[kVitNumTensors] = {
    0, 128, 6400, 6528, 8704, 57856, 58240, 74624, 74752, 74880,
    75008, 75136, 75264, 140800, 141312, 206848, 206976, 256128, 256512, 272896,
    273024, 273152, 273280, 273408, 273536, 339072, 339584, 405120, 405248, 405376,
    405504, 417920
};

// Per-tensor element sizes (numel), same order.
__device__ __constant__ int kVitSizes[kVitNumTensors] = {
    128, 6272, 128, 2176, 49152, 384, 16384, 128, 128, 128,
    128, 128, 65536, 512, 65536, 128, 49152, 384, 16384, 128,
    128, 128, 128, 128, 65536, 512, 65536, 128, 128, 128,
    12416, 97
};

static_assert(kVitNumTensors == 32,
              "vit_layout: tensor count drifted. Regenerate from "
              "vit_oracle.py::vit_param_layout() (codegen adoption: --vit-layout).");
static_assert(kVitTotalElems == 418017,
              "vit_layout: total param count drifted. Regenerate.");

// Host-constexpr mirrors so a sum/offset cross-check folds at compile time (a
// __constant__ array can't be folded in a constexpr). These guarantee
// offsets/sizes/total agree.
namespace vit_layout_check {
constexpr int kSizes[kVitNumTensors] = {
    128, 6272, 128, 2176, 49152, 384, 16384, 128, 128, 128,
    128, 128, 65536, 512, 65536, 128, 49152, 384, 16384, 128,
    128, 128, 128, 128, 65536, 512, 65536, 128, 128, 128,
    12416, 97
};
constexpr int kOffsets[kVitNumTensors] = {
    0, 128, 6400, 6528, 8704, 57856, 58240, 74624, 74752, 74880,
    75008, 75136, 75264, 140800, 141312, 206848, 206976, 256128, 256512, 272896,
    273024, 273152, 273280, 273408, 273536, 339072, 339584, 405120, 405248, 405376,
    405504, 417920
};
constexpr int64_t sum_sizes() {
    int64_t s = 0;
    for (int i = 0; i < kVitNumTensors; ++i) s += kSizes[i];
    return s;
}
constexpr bool offsets_consistent() {
    int64_t acc = 0;
    for (int i = 0; i < kVitNumTensors; ++i) {
        if (kOffsets[i] != (int)acc) return false;
        acc += kSizes[i];
    }
    return true;
}
// Largest per-tensor numel (folds at compile time from the layout table). The
// d-INDEPENDENT optimizer tails (SuperGrok2's per-CTA workspace stride, sized for
// the LARGEST tensor) re-derive their capacity from THIS instead of a d=128-pinned
// 65536 literal, so the SAME tail code is correct at every ladder width.
constexpr int max_size() {
    int m = 0;
    for (int i = 0; i < kVitNumTensors; ++i) if (kSizes[i] > m) m = kSizes[i];
    return m;
}
static_assert(sum_sizes() == kVitTotalElems,
              "vit_layout: sum(kVitSizes) != kVitTotalElems. Regenerate.");
static_assert(offsets_consistent(),
              "vit_layout: kVitOffsets[i] != sum(kVitSizes[0..i)). Regenerate.");

// ── Per-CTA dynamic-smem budget guard. The ViT per-sample working set
//    (VitSampleSmem, model_stage_vit.cuh) is ≈ 188,080 bytes (≈ 183.67 KB) at
//    seq=17 — FAR over the 48 KB STATIC __shared__ cap (so it MUST be dynamic
//    smem), but comfortably UNDER the sm_90 per-block dynamic cap of 227 KB
//    (232448 B). This bound is the size the launcher passes to
//    cudaFuncSetAttribute(MaxDynamicSharedMemorySize) + <<<dynamicSMemBytes>>>.
//    Computed from the field list (all float, 4 B, no padding):
//      patch 16*49 + layer_in 2*17*128 + final_in 17*128 + qkv 17*384
//      + ctx 17*128 + x1 17*128 + ff0 17*512 + gact 17*512 + attn 4*17*17
//      + n1_xhat 17*128 + n1_inv 17 + n2_xhat 17*128 + n2_inv 17
//      + fn_xhat 17*128 + fn_inv 17 + dh 17*128 + logits 97 + dsc 4*17*17
//      + red 256  = 47020 floats = 188080 bytes.
//    (If VitSampleSmem changes, update BOTH this literal and the sum below;
//    fused_vit_megakernel.cuh static_asserts sizeof(VitSampleSmem) against it.) ─
constexpr int kVitSampleSmemFloats =
    16 * 49            // patch[NPATCH][PATCH]
  + 2 * 17 * 128       // layer_in[LAYERS][SEQ][D]
  + 17 * 128           // final_in[SEQ][D]
  + 17 * 384           // qkv[SEQ][3D]
  + 17 * 128           // ctx[SEQ][D]
  + 17 * 128           // x1[SEQ][D]
  + 17 * 512           // ff0[SEQ][DFF]
  + 17 * 512           // gact[SEQ][DFF]
  + 4 * 17 * 17        // attn[HEADS][SEQ][SEQ]
  + 17 * 128 + 17      // n1_xhat[SEQ][D] + n1_inv[SEQ]
  + 17 * 128 + 17      // n2_xhat[SEQ][D] + n2_inv[SEQ]
  + 17 * 128 + 17      // fn_xhat[SEQ][D] + fn_inv[SEQ]
  + 17 * 128           // dh[SEQ][D]
  + 97                 // logits[VOCAB]
  + 4 * 17 * 17        // dsc[HEADS][SEQ][SEQ]
  + 256;               // red[256]
constexpr int kVitSampleSmemBytes = kVitSampleSmemFloats * (int)sizeof(float);
static_assert(kVitSampleSmemBytes == 188080,
              "vit_layout: VitSampleSmem byte budget drifted from 188080.");
static_assert(kVitSampleSmemBytes < 227 * 1024,
              "vit_layout: VitSampleSmem exceeds the sm_90 227 KB dynamic-smem "
              "per-block cap — the megakernel could not launch.");
}  // namespace vit_layout_check

// Largest per-tensor numel, hoisted to namespace scope. vit_tc_sg2_floats /
// vit_sg2_ws_stride_floats size their per-CTA SuperGrok2 workspace from THIS
// (max tensor numel) rather than a d=128-pinned 65536, so the tail is ladder-correct.
constexpr int kVitMaxTensorNumel = vit_layout_check::max_size();
#endif  // SG_VIT_BENCH_LAYOUT

}}} // namespace sg::fused::sm90

#endif  // SG_FUSED_SM90_VIT_LAYOUT_CUH_
